### ISSUE TITLE
How to deny a group of users to translate specific language?

### ISSUE THREAD

**Issue by ihoru** [nijel/weblate#1002]
I want to be able translating to English only group of Managers. How could I do that?

**Comment by nijel** [comment]
You can remove the ``Can save template`` privilege from the Users group.

**Comment by ihoru** [comment]
Thanks! Great!

**Comment by ihoru** [comment]
I my case it didn't work. It denied to save all translations :(

**Comment by ihoru** [comment]
Thanks
