### ISSUE TITLE
Enabling GroupACL removes permission to add suggestions

### ISSUE THREAD

**Issue by timonreinhard** [nijel/weblate#1004]
### Steps to reproduce
0. Precondition: Have "Suggestions" enabled for your components
1. Create a group "Translators" with permission to add/change translations and _suggestions_ (or stick with the default group "Users").
2. Add a Group ACL thats restricts that group to a certain language
3. Access the translation UI for that language as a user of that group

### Expected behavior
The "Suggest" feature is available as the group has the required permissions assigned and "Suggestions" are enabled for that component.

### Actual behavior
The "Suggest" button is hidden and a message "No permission to add suggestions!" is shown instead. 

### Server configuration
Version 2.5-dev (82918110bcafee29bb3e503ecc1059e8bab31031 on master)

 * Weblate weblate-2.4-1383-g8291811
 * Python 2.7.6
 * Django 1.8.2
 * six 1.10.0
 * python-social-auth 0.2.10
 * Translate Toolkit 1.13.0
 * Whoosh 2.5.7
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.3.3
 * django-crispy-forms 1.4.0
 * compressor 2.0
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 2.8.2
 * Database backends: django.db.backends.mysql

**Comment by timonreinhard** [comment]
Awesome, thanks!

**Comment by nijel** [comment]
I expect there will be more rough edges in the Group ACL code as it didn't yet get much real world testing and the number of combinations this allows is huge to have this fully test covered.
