### ISSUE TITLE
GitHub integration: OSError at /admin/trans/subproject/add/ [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by erictrade** [nijel/weblate#1010]
Hi!

I'm trying to configure github integration to send pull requests instead of direct commits.

I'm already configured hub, created the ~/.config/hub file manually with user name and token, edited the GITHUB_USERNAME variable. Now I see GitHub version control on combobox to select.

But, when I configure everything, it throws this error: http://dpaste.com/3EADF3C

If I use Git instead of GitHub, component is created without error.

Some more info about my environment, created using bitnami image on Amazon AWS:

 * Weblate 2.4
 * Python 2.7.11
 * Django 1.8.7
 * python-social-auth 0.2.1
 * Translate Toolkit 1.13.0
 * Whoosh 2.6.0
 * Git 2.6.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.3.6
 * django-crispy-forms 1.4.0
 * compressor 1.5
 * hub 2.2.3

Any help with this issue is appreciated!
Thanks!

**Comment by nijel** [comment]
The GitHub integration using command line utility is really problematic and we should switch to using the API directly. See also #943.

Anyway your issue seems to be that Weblate can not execute the hub command in the end...

**Comment by erictrade** [comment]
Hi @nijel, please see my last 2 comments on hub project.
https://github.com/github/hub/issues/1164

Do you think it would help weblate project somehow if I send my edits in a PR?

**Comment by nijel** [comment]
See also #1122.

**Comment by nijel** [comment]
Thanks for pointing this out, I've hopefully fixed it in less intrusive way (so that it sets the path only if file exists).

**Comment by erictrade** [comment]
Awesome! Thanks @nijel!
I'll send a PR soon describing the other issue I had. Hope I can help again =)
