### ISSUE TITLE
Context seems broken for xliff in 2.5

### ISSUE THREAD

**Issue by mickeprag** [nijel/weblate#1011]
### Steps to reproduce
1. Upload an xliff file with this tag:
`
    <trans-unit id="hello-world" datatype="plaintext">
    	<source>Hello World</source>
    	<target>Hello World</target>
    </trans-unit>
`

### Expected behaviour
The context property in Weblate should be "hello-world"

### Actual behaviour
The context is set to "Hello World"

This worked fine in 2.4 but is broken in 2.5

**Comment by nijel** [comment]
Did you upgrade something else besides Weblate?

But there indeed seems to be something broken in 2.5, see last comments on #939.

**Comment by mickeprag** [comment]
I installed Weblate (2.4) using pip install in a virtualenv. For upgrading I created a new virtualenv and installed a fresh Weblate (2.5) in it. Then I switched virtualenv path in apache.

**Comment by nijel** [comment]
Can you please check translate-toolkit version in both of them?

**Comment by mickeprag** [comment]
Both uses translate-toolkit 1.14.0_rc1.
If you want access to the system please let me know.

**Comment by nijel** [comment]
Should be fixed by a644d58.
