### ISSUE TITLE
Can't update unit from XLIFF file

### ISSUE THREAD

**Issue by mapx** [nijel/weblate#1021]
### Steps to reproduce
1.Add a project and a component of XLIFF files in admin panel.
2.Choose a language and translate one item.
3.Press `save` button under `Translation` textarea.

### Actual behaviour
The page jumped to the next item with a warning `Message not found in backend storage, it is probably corrupted.` Translation of last item is not saved.

When `save` triggers the POST,
https://github.com/nijel/weblate/blob/master/weblate/trans/models/translation.py#L790 returns `pounit` as `None`

### Server configuration
Weblate==2.5
Babel==2.2.0
chardet==2.3.0
decorator==4.0.9
defusedxml==0.4.1
diff-match-patch==20121119
Django==1.9.4
django-appconf==1.0.1
django-compressor==1.6
django-crispy-forms==1.6.0
ipython==4.1.2
ipython-genutils==0.1.0
lxml==3.5.0
MarkupSafe==0.23
mysqlclient==1.3.7
oauthlib==1.0.3
path.py==8.1.2
pexpect==4.0.1
pickleshare==0.6
Pillow==3.1.1
ptyprocess==0.5.1
py3dns==3.1.0
PyJWT==1.4.0
pyLibravatar==1.7
python-dateutil==2.5.0
python-memcached==1.57
python-social-auth==0.2.14
python3-openid==3.0.9
pytz==2015.7
pyuca==1.1
requests==2.9.1
requests-oauthlib==0.6.1
simplegeneric==0.8.1
six==1.10.0
traitlets==4.1.0
translate-toolkit==1.14.0rc1
Whoosh==2.7.2

**Comment by nijel** [comment]
Indeed there seems to be something wrong with XLIFF support, see also #1011,

**Comment by dinofizz** [comment]
I am also seeing this issue. Without spending too much time debugging and not being too familiar with this project I have made these findings:

- https://github.com/nijel/weblate/blob/7ab3fbd663e545f0efe1ece8cb0450f5aa69f8df/weblate/trans/formats.py#L578
 - The ```ttkit_unit_context``` and the ```context``` passed in are not equivalent.
 - ```ttkit_unit_context``` is retreived from ```getlocations()``` in ```xliff.py``` of translate toolkit, and it's value is **just** that of the trans-unit ID in the XLIFF file.
 - The ```context``` which is passed appears to be a concatenation of the ```original``` attribute of the parent ```file``` element as well as the ```id``` attribute of the ```trans-unit``` element of the string in question.

E.g. when presented with the following XLIFF

```
...
<file original="RootFolder/AnotherFolder/file.xib" source-language="en" datatype="plaintext" target-language="ja">
	<header>
		<tool tool-id="com.apple.dt.xcode" tool-name="Xcode" tool-version="7.2" build-num="7C68"/>
	</header>
	<body>
		<trans-unit id="Pgd-Y4-2Xa.text">
			<source>Original english</source>
			<target></target>
			<note>Class = "UILabel"; text = "Original english"; ObjectID = "Pgd-Y4-2Xa";</note>
		</trans-unit>
	</body>
</file>
...
```

The comparison which is attempted is:

```ttkit_unit_context``` = ```Pgd-Y4-2Xa.text```

and

```context``` = ```RootFolder/AnotherFolder/file.xib///Pgd-Y4-2Xa.text```
