### ISSUE TITLE
Java .properties strings defaulting to English - Weblate confused

### ISSUE THREAD

**Issue by vektor330** [nijel/weblate#1023]
Hello there, first of all, thanks for a great piece of software! Now, my situation is this:
* `Strings.properties` - default strings, contain EN translation.
* `Strings_en.properties` - empty file, "marker" to show we have an EN translation.
* `Strings_fr.properties` - FR translation, some strings are missing - those default to the EN version.

My approach is based on the [SO question](http://stackoverflow.com/questions/36011759/resourcebundle-that-defaults-to-english) I posted a few days ago.

Weblate's config:
* File mask: `src/company/project/resources/Strings_*.properties`
* Monolingual base language file: `src/company/project/resources/Strings_en.properties`

Problem is, Weblate now thinks there are no strings (`Strings_en` is empty), so every other translation pretends to be 100% translated.

If I tell Weblate that the base file is `src/company/project/resources/Strings.properties` (as it actually is), it complaints **"There are more files for single language, please adjust the mask and use components for translating different resources."**.

In the end, Java's system of finding default strings requires me to have the `Strings.properties` in place, while Weblate is confused by this and wants an explicit `Strings_en.properties`. Is there a way out of this? Ideally I would like to avoid having to copy/paste or hard-link `Strings_en` to `Strings`...

Using Weblate 2.5-dev.

**Comment by nijel** [comment]
You can ignore the English language file being loaded by setting ``Language filter`` to ``^(?!en)$``.

**Comment by vektor330** [comment]
Hello, thanks. I've tried your solution - as far as I can tell, nothing has changed.

Even if I succeed, ie. ignore the empty file `Strings_en.properties`, how do I tell Weblate to consider `Strings.properties` to be the base file?

**Comment by nijel** [comment]
Just set ``src/company/project/resources/Strings.properties`` as base file for monolingual translations.

**Comment by vektor330** [comment]
Please see the first comment - if I try it, I get an error.

Problematic setup:
* File mask: `src/company/project/resources/Strings_*.properties`
* Monolingual base language file: `src/company/project/resources/Strings.properties`
* Language filter: `src/company/project/resources/Strings_en.properties`

Error obtained:
<img width="722" alt="screen shot 2016-03-17 at 12 03 44" src="https://cloud.githubusercontent.com/assets/377878/13844164/5289b1ac-ec38-11e5-8ed3-ebf617460fcc.png">

**Comment by nijel** [comment]
Eh, sorry, the regexp should be rather ``^(?!en).*$``.

However indeed there seems to be bug, the validation doesn't honor this setting, I'm looking into that.

**Comment by vektor330** [comment]
Thanks, will

**Comment by vektor330** [comment]
Sorry for the chaotic closure/reopening, GitHub is a bit confusing.

Thanks, I will keep an eye out on the fix.
