### ISSUE TITLE
Highlight changes in Zen mode

### ISSUE THREAD

**Issue by yfdyh000** [nijel/weblate#1030]
### Steps to reproduce
1. Open Zen mode for strings have action is needed.

### Expected behaviour
1. You can aware and view the source changes.

### Actual behaviour
1. No sing, the strings just needs to be updated in the translations, the review checkbox marked by default.

### Server configuration
Please paste here output of ./manage.py list_versions

**Comment by yfdyh000** [comment]
Great improvement. But I noticed, click any .hlcheck will fill it to the first translation field, instead of the string's translation field.

**Comment by nijel** [comment]
Can you please open separate issue for that?

**Comment by yfdyh000** [comment]
ok, it is #1188 now.
