### ISSUE TITLE
Introduce the drop-down box in Dashboard

### ISSUE THREAD

**Issue by yfdyh000** [nijel/weblate#1032]
### Steps to reproduce
1. Open the https://hosted.weblate.org/ with new user (non-essential).

### Expected behaviour
1. Easy to find out the unfinished, interested translation projects.

### Actual behaviour
1. I don't see any introduction after I registered, I found the drop-down box (All projects, Your languages, Your subscriptions) after use the Projects list (at top bar) in many times.

Expected:
1. Adding a prompt to the list below, it does not bother if you have a lot of subscriptions, or allow to remove it.
2. Or, add a mandatory tour when a new user first visit the dashboard page.

**Comment by nijel** [comment]
Since dbb7504c328d2ffdc50609747277fda033053bf3 (Weblate 2.7) there are listed projects in user language where some work can be done.
