### ISSUE TITLE
recommend: allow to switch search filters on translate interfaces

### ISSUE THREAD

**Issue by yfdyh000** [nijel/weblate#1034]
### Steps to reproduce
1. Visit the project page, for example: https://hosted.weblate.org/projects/weblate/master/zh_Hans/.
2. Click the entries on "Strings to check".

### Expected behaviour
I can switch the search filters and refresh the current page in translate interfaces, including Zen view.

### Actual behaviour
I had to back and reopen the desired page.

**Comment by yfdyh000** [comment]
I see it and it work in the translation interface, but it's just a label in Zen mode.
In addition, in the normal translation interface, it is not filling the current filter to these fields as default.

**Comment by nijel** [comment]
Same as in other case - please open separate issue for each problem.
