### ISSUE TITLE
Copy source text without network request

### ISSUE THREAD

**Issue by yfdyh000** [nijel/weblate#1038]
### Steps to reproduce
1. Copy source text.

### Expected behaviour
Instant done locally.

### Actual behaviour
Request to /js/get/[NUMBER]. Wait for the request is complete, then the text has been copied, 'review' checked. It is a long process, since network delay to the website (about 400-500ms, from China). I don't understand why it needs to obtain them from remote, it has been shown in the interface.

https://github.com/nijel/weblate/blob/cdf5978ae39f29741e3118eacd78328b1733bcc6/weblate/static/loader-bootstrap.js#L132

**Comment by nijel** [comment]
It's retrieved again to have verbatim text - without formatting and whitespace changes. However it probably could be included in the first request...
