### ISSUE TITLE
https://git.weblate.org/ not accessible because of HSTS

### ISSUE THREAD

**Issue by rvanlaak** [nijel/weblate#1041]
### Steps to reproduce
goto https://git.weblate.org/

### Expected behaviour
Maybe HSTS should be configurable. We are testing weblate on our DEV environment, where not all projects have ssl-certs.

### Actual behaviour
Git cannot be opened, because Weblate forces HSTS

**Comment by nijel** [comment]
And what is the problem? There is nothing on the http://git.weblate.org/ as well. It is only supposed to work as git://git.weblate.org/...

**Comment by rvanlaak** [comment]
Ah okay, found that link in the documentation so that is why I reported it. As long as it is accessible via git:// that is okay. Did expect to find a website there too :)

**Comment by nijel** [comment]
What did you expect to find there? There is no problem to redirect it somewhere, I just didn't realize somebody would want to use it...

**Comment by rvanlaak** [comment]
Don't really know, some web interface to see details about the git repo. But think redirect will nog work for HSTS.

**Comment by nijel** [comment]
I anyway want to switch exporting Git repos from git protocol to https, so this site will have content in the end, see #1042.

**Comment by rvanlaak** [comment]
Okay that's clear, probably installing something like [GitLab Community Edition](https://about.gitlab.com/features/#community) will be huge overkill? ;)

**Comment by nijel** [comment]
It would be - we need read only access only :-).
