### ISSUE TITLE
No ways to add a subscribe from project pages

### ISSUE THREAD

**Issue by yfdyh000** [nijel/weblate#1043]
### Steps to reproduce
1. View a project page.

### Expected behaviour
I can to add / remove the subscribe at any times.

### Actual behaviour
I had to go to user profile - subscribe, after I read and understand the project.

**Comment by petterreinholdtsen** [comment]
I was confused by this usability issue too.  I expected some 'subscribe to project' button somewhere, but failed to find it.  I ended up giving up and found the profile->subscribe by chance a lot later.
