### ISSUE TITLE
Google Web Translate not working

### ISSUE THREAD

**Issue by WanTanFao** [nijel/weblate#1045]
### Steps to reproduce
1. Activate Google Web Translate from Config (trans.machine.google.GoogleWebTranslation)
2. Load a Translation Page
3. Receive this error: MachineTranslationError: HTTPError: HTTP Error 503: Service Unavailable

### Expected behaviour
Machine-Translation

### Actual behaviour
"MachineTranslationError: HTTPError: HTTP Error 503: Service Unavailable"

### Server configuration
```
* Weblate weblate-2.4-1002-g8d1cba5
 * Python 2.7.3
 * Django 1.7.7
 * six 1.9.0
 * python-social-auth 0.2.2
 * Translate Toolkit 1.13.0-rc1
 * Whoosh 2.5.7
 * Git 1.7.10.4
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.4.2
 * django-crispy-forms 1.4.0
 * compressor 1.6
 * pyuca N/A
 * pyLibravatar N/A
```

**Comment by nijel** [comment]
The web based translation is really not suited for general use, it's better to register by Google and use regular Google Translate by API (https://docs.weblate.org/en/latest/admin/machine.html#google-translate). Maybe this backend should be removed altogether from the codebase to avoid false expectations...
