### ISSUE TITLE
Problem with component links

### ISSUE THREAD

**Issue by acamara7es** [nijel/weblate#1052]
When I try to click on a component link to open and translate it the application sends to the "original site" instead of the weblate component

### Expected behaviour
For example, when I click on component link, it should redirect to:
`localhost:8000/projects/pruebas/main-web/`

### Actual behaviour
The link goes to:
`http://example.com/projects/pruebas/main-web/`
If I replace `http://example.com` with `localhost:8000`  it runs correctly

### Server configuration

>  * Weblate 01808c1
>  * Python 2.7.6
>  * Django 1.9.4
>  * six 1.10.0
>  * python-social-auth 0.2.14
>  * Translate Toolkit 1.14.0-rc1
>  * Whoosh 2.7.3
>  * Git 1.9.1
>  * Pillow (PIL) 1.1.7
>  * dateutil 2.5.2
>  * lxml 3.6.0
>  * django-crispy-forms 1.6.0
>  * compressor 1.6
>  * djangorestframework 3.3.3
>  * pyuca N/A
>  * Mercurial 2.8.2
>  * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
You need to configure site name, see <https://docs.weblate.org/en/latest/faq.html#faq-site>.
