### ISSUE TITLE
Number with lots of decimal places

### ISSUE THREAD

**Issue by pc-jedi** [nijel/weblate#1055]
### Expected behaviour
Only one or two places after the decimal are fine.

### Actual behaviour
![screenshot from 2016-04-05 12 36 38](https://cloud.githubusercontent.com/assets/9032867/14279069/5bede612-fb2b-11e5-8f22-b07512635570.png)

### Server configuration
```
 * Weblate 2.6-dev
 * Python 3.5.1
 * Django 1.9.5
 * six 1.10.0
 * python-social-auth 0.2.14
 * Translate Toolkit 1.14.0-rc1
 * Whoosh 2.7.4
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.2
 * lxml 3.6.0
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * djangorestframework 3.3.3
 * pyuca N/A
 * pyLibravatar N/A
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
Ah, looks like I've missed something when porting to Python 3 :-).
