### ISSUE TITLE
Improvements for translation page UX

### ISSUE THREAD

**Issue by rvanlaak** [nijel/weblate#1057]
Basically we in the near future would like weblate to become our "translation community". Right now we use a lot of files to communicate with our translators, and to explain them the context about a translation. What we would like to see could be a quick-fix to drastically improve translation interaction:

1. While translating, make 'comments' the tab that is selected by default. Right now that is 'nearby messages', which is a bit less useful. Maybe comments always should be visible, and the tabs should be shown #1058
2. Also add the number of nearby messages in the header (as with suggestions) #1059
3. What does the comment scope do? It only shows the gray label at the right of the comment? Do not think people understand that, we think it should always be 'translation comment' right? Would make this a simple toggle next to the 'save' button, or maybe remove it? #1060
4. The location of the 'search' tab is a bit odd, it is not related to that translation string right? Would expect it to be in the page header. We would like to use the search all day if we want to do ad-hoc translations. #1061
4. Let all 'save' buttons float right? People are right action oriented. #1062
5. There is no button to exit 'Zen edit mode'? #1063

Hope you like my positive criticism :+1: The translating experience should be as smooth as possible.

**Comment by nijel** [comment]
Can you please next time file one item per issue? It's way easier to track then...

**Comment by rvanlaak** [comment]
I'd first like to know whether you agree on the items, so shall I make sub-items of each item now then?

**Comment by nijel** [comment]
I think most of them make sense.

**Comment by rvanlaak** [comment]
Check, made separate UX issues of them.

**Comment by nijel** [comment]
Thanks! Closing this in favor of separate issues.
