### ISSUE TITLE
[UX] Translation page: Make comments default

### ISSUE THREAD

**Issue by rvanlaak** [nijel/weblate#1059]
Quick UX improvements to the translation page (see #1057):

* While translating, make 'comments' the tab that is selected by default. Right now that is 'nearby messages', which is a bit less useful. 
* Maybe comments always should be visible, and the tabs should be shown below?
* Add image drag & drop (like here on Github) to easily allow 'managers' to add context to new translations.

**Comment by nijel** [comment]
The tab selection is persistent. Though I've just noticed that it's just persistent per given translation and not for whole Weblate, what makes it quite confusing...

**Comment by rvanlaak** [comment]
What about comments being important, do you agree on that? In that case they always should be visible right, given they "contribute" to the translation process with important information.

Next to that: adding a drag & drop for uploading images (read: screenshots of the translation) would be great! That way we can really show translators the most important context of the translation.

**Comment by nijel** [comment]
I don't agree with that as I really don't see them much being used. It really depends on how given translation team works. Anyway I think that having tab persistent Weblate wide will address your problem as well - if comments are important for given team, it will be just once click.

**Comment by nijel** [comment]
PS: For screenshots see #250.

**Comment by rvanlaak** [comment]
> if comments are important for given team, it will be just once click.

Just a remark on this one, if comments are not visible in the first place then people will not be able to read them. They will not click the comments on every translation they do.

Basically, there should be some way to inform translators about important information related to that specific translation. We think comments + screenshots are able to solve this.

**Comment by nijel** [comment]
I'm not really sure for what are you trying to use comments, but maybe using comments from the translation files will be better fit for your purpose - these are shown prominently next to source string and in in sidebar. See for example here: https://hosted.weblate.org/translate/weblate/master/cs/?checksum=2ea795535324c45544e64abacc014d79

**Comment by nijel** [comment]
I still don't think comments tab should be default as it's usually empty and thus it really brings no value to translators in such case.

Anyway the tab selection will now be persistent for user sitewide, what makes it more intuitive than previous per translation persistence.

**Comment by rvanlaak** [comment]
:+1:
