### ISSUE TITLE
[UX] Move 'search' integration

### ISSUE THREAD

**Issue by rvanlaak** [nijel/weblate#1061]
Quick UX improvements (see #1057):

* The location of the 'search' tab is a bit odd, it is not related to that translation string right?
* Would expect it to be in the page header. 
* Maybe "simple search" is enough for most users, and "advanced filters" can be shown as label

We would like to use the search all day if we want to do ad-hoc translations.

**Comment by nijel** [comment]
Maybe it could be moved to the navigation together with filter switching (see #1034)...
