### ISSUE TITLE
Error on absolute URLs after pulling master

### ISSUE THREAD

**Issue by rvanlaak** [nijel/weblate#1064]
### Steps to reproduce
1. Open project via menu

### Expected behaviour
Open project

### Actual behaviour
* Error, URL is not found. The URL is `/weblate/weblate`, all other URLs seem to work fine.
* Removing one part of URL just opens project
* On project page there are some extra broken URLS on 1) components, 2) commit action

Looks like the relative URLs are correct and the absolute URLs are incorrect?

### Server configuration
 * Weblate weblate-2.5-218-g2bdb46b
 * Python 2.7.3
 * Django 1.9.5
 * six 1.10.0
 * python-social-auth 0.2.12
 * Translate Toolkit 1.14.0-rc1
 * Whoosh 2.7.4
 * Git 1.7.10.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.6.0
 * django-crispy-forms 1.5.1
 * compressor 1.5
 * djangorestframework 3.3.3
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.4.2
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
Maybe your site configuration is invalid? See https://docs.weblate.org/en/latest/faq.html#why-does-links-contain-example-com-as-domain

**Comment by rvanlaak** [comment]
Maybe the upgrade went wrong? This is what's happening after I've pulled master just now:

> $ git pull && ./manage.py migrate

```
/usr/local/lib/python2.7/dist-packages/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/usr/local/lib/python2.7/dist-packages/social/apps/django_app/urls.py:19: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got auth). Pass the callable instead.
  name='begin'),

/usr/local/lib/python2.7/dist-packages/social/apps/django_app/urls.py:21: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got complete). Pass the callable instead.
  name='complete'),

/usr/local/lib/python2.7/dist-packages/social/apps/django_app/urls.py:24: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got disconnect). Pass the callable instead.
  name='disconnect'),

/usr/local/lib/python2.7/dist-packages/social/apps/django_app/urls.py:26: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got disconnect). Pass the callable instead.
  .format(extra), 'disconnect', name='disconnect_individual'),

/usr/local/lib/python2.7/dist-packages/social/apps/django_app/urls.py:26: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  .format(extra), 'disconnect', name='disconnect_individual'),

/usr/local/lib/python2.7/dist-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 89, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 306, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 276, in _reraise_missing_dependency
    raise exc
django.db.migrations.exceptions.NodeNotFoundError: Migration accounts.0016_add-api-keys dependencies reference nonexistent parent node (u'authtoken', u'0001_initial')
```

**Comment by nijel** [comment]
Adjust settings to new version...

**Comment by rvanlaak** [comment]
I'm sorry to be a pain in the ass, but after searching the docs a bit I still have no idea how to adjust the settings to the new version. `settings.py` does not contain such a parameter right?

**Comment by nijel** [comment]
You need to add two new apps:

```
    'rest_framework',
    'rest_framework.authtoken',
```

**Comment by rvanlaak** [comment]
Thanks, but this keeps getting weirder. The link to the project in the menu now is:

    http://https//dev.myhost.nl/weblate/weblate/projects/myproject/

**Comment by nijel** [comment]
I guess it's due to missing ``:`` in the configured URL between ``https`` and ``//``  :-).

**Comment by rvanlaak** [comment]
Yes of course that's clear, but that still does not solve the problem :wink: This still is related to the upgrade attempt I tried to do? I'd really like to help you test the `master` branch once in a while, but given that I'm not known to django we can not solve these upgrade problems on our own.

Does the regular upgrade procedure between stable releases fix these problems by itself?

**Comment by nijel** [comment]
The [ugprade procedure](https://docs.weblate.org/en/latest/admin/upgrade.html#generic-upgrade-instructions) is always the same, it doesn't matter if it's released version or on git. The master branch is usually good for production with very few exceptions which get fixed fast. https://hosted.weblate.org/ follows master branch as well.

**Comment by rvanlaak** [comment]
Additional information on this, it was related to the `django_site` table in my database after upgrading, and to the "ENABLE_HTTPS = True" setting and `URL_PREFIX` setting in `settings.py`.

Removing the protocol from `django_site.domain` row did fix the incorrect URLs:

**Old database value:** https://dev.example.com/weblate
**View value:** https//dev.example.com/weblate/weblate

**New database value:** dev.example.com
**View value:** https://dev.example.com/weblate

**Comment by nijel** [comment]
Thanks, I've clarified the docs.
