### ISSUE TITLE
Different repositories need different SSH keys?

### ISSUE THREAD

**Issue by fisharebest** [nijel/weblate#1072]
There are two projects on my server https://translate.webtrees.net
* https://github.com/fisharebest
* https://github.com/JustCarmen

I have added the weblate SSH public key to the first account, and can commit changes OK.

But github does not allow the same SSH key to be used on two different accounts.
Therefore I cannot commit changes to the second repository.

Does weblate need to have one SSH key per project - instead of one SSH key per site?

**Comment by nijel** [comment]
You can create separate user for Weblate pushes and add it as a collaborator. This is how Hosted Weblate works. I think I've documented this somewhere, but I can not find it in the documentation right now, so it was probably just in the issue tracker and should be probably documented properly.

**Comment by fisharebest** [comment]
Thanks.  This works.  I have created a new github account, which is a collaborator on all repositories.

**Comment by nijel** [comment]
Documented here: https://docs.weblate.org/en/latest/admin/projects.html#github-repositories
