### ISSUE TITLE
msgctxt missing when downloading .PO files

### ISSUE THREAD

**Issue by fisharebest** [nijel/weblate#1076]
### Steps to reproduce

My .PO files contain translations with contexts.  e.g. <https://github.com/fisharebest/webtrees/blob/master/language/fr.po>
Weblate can display/edit/save these correctly.

```
msgid "Friend"
msgstr "Ami(e)"

msgctxt "FEMALE"
msgid "Friend"
msgstr "Amie"

msgctxt "MALE"
msgid "Friend"
msgstr "Ami"
```

If I download the .PO file from weblate, e.g. <https://translate.webtrees.net/projects/webtrees/webtrees/fr/> then the contexts are missing.

```
msgid "Friend"
msgstr "Ami(e)"

msgid "Friend"
msgstr "Amie"

msgid "Friend"
msgstr "Ami"
```

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

```
$ ./manage.py list_versions
 * Weblate weblate-2.5
 * Python 2.7.9
 * Django 1.9.5
 * six 1.10.0
 * python-social-auth 0.2.16
 * Translate Toolkit 1.13.0
 * Whoosh 2.7.4
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.2
 * lxml 3.6.0
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.3.2
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
Confirmed with current master, though the code to include context is there...

**Comment by sveinki** [comment]
My experience is that in downloaded PO-files, msgctxt is present, but not correctly escaped (missing ""). This makes my editors either ignore the msgctxt lines or fail to open. Direct gettext commands all fail (msgmerge, etc.).
Probably relates also to bug 1183.
My sample file: https://hosted.weblate.org/download/f-droid/f-droid/is/po/

**Comment by nijel** [comment]
Hmm, this really looks like some issue in the translate-toolkit.

**Comment by sveinki** [comment]
Some further testing:
Uploads of modified PO-files don't work, "no strings detected" message.
Uploads via XLIFF don't work either.
Downloading original Android strings XML only give me already translated strings (I can add strings by copying and adding <string name="msgctxt_value">translated_string</string>, and the upload works).
Escaping all msgctxt "msgctxt_value" in the PO-file (50/50 Search/Replace and loads of manual work) makes uploads work as intended.

So, the mechanism which prepares the downloadable PO-file permits non-escaped msgctxt messages (keywords?) but insists on them to be escaped while uploading.

**Comment by sveinki** [comment]
Just a bit more: I just uploaded a PO-file with escaped msgctxt messages - redownloading as a po file has all the quotes stripped from the msgctxt keywords.

**Comment by nijel** [comment]
Okay, this was caused by improper workaround for https://github.com/translate/translate/issues/3441 (see also https://github.com/translate/translate/pull/3433). Fixed in git now.
