### ISSUE TITLE
http links on https page

### ISSUE THREAD

**Issue by fisharebest** [nijel/weblate#1079]
### Steps to reproduce

Visit <https://translate.webtrees.net/widgets/webtrees/>

The browser shows a "security error".

![screen shot 2016-04-18 at 22 09 31](https://cloud.githubusercontent.com/assets/2306088/14619964/27e0f30a-05b2-11e6-8b3f-326faf5fd64b.png)

This is because the server uses HTTPS, but the links to the images are HTTP://

The URLs for the images should use the same protocol as the URL for the page.

**Comment by nijel** [comment]
Please set [ENABLE_HTTPS](https://docs.weblate.org/en/latest/admin/config.html#std:setting-ENABLE_HTTPS), see also https://docs.weblate.org/en/latest/admin/install.html#production-site

**Comment by fisharebest** [comment]
Thanks!

Perhaps add to `settings_example.py`?

**Comment by nijel** [comment]
Good idea.
