### ISSUE TITLE
All translations were marked as fuzzy after reload 

### ISSUE THREAD

**Issue by murhafh** [nijel/weblate#1081]
### Steps to reproduce
1.Add a new translation project
2.Point to the correct translation files (in my case .xliff files)
3.Load the files

### Actual behaviour
After all the translations were loaded, they all showed as fuzzy, even though in the xliff file they didn't have a status

### Expected behaviour
show the status from the xliff files

### Server configuration
 Weblate weblate-2.1-148-g7e86d1f
 * Python 2.7.3
 * Django 1.7.2
 * python-social-auth 0.2.1
 * Translate Toolkit 1.12.0
 * Whoosh 2.5.7
 * Git 2.2.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.0
 * lxml 3.4.1
 * django-crispy-forms 1.4.0
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.2.4

**Comment by nijel** [comment]
This is known problem with xliff files. The library we use for parsing the files needs approved="yes" on the units in the xliff file. Probably should be documented as this comes up quite often...

**Comment by nijel** [comment]
See also https://github.com/nijel/weblate/issues/751 or https://github.com/nijel/weblate/issues/1040

**Comment by murhafh** [comment]
Is there a way to change this behaviour after the import?

**Comment by murhafh** [comment]
And actually it is not even possible to remove it
I get an error "Message not found in backend storage, it is probably corrupted."

**Comment by nijel** [comment]
I just now noticed that you're using quite old version. I'm not really sure how well XLIFF worked there, there has been recently quite a lot of fixes, eg. #939.

**Comment by murhafh** [comment]
OK, thanks for the quick feedback.

**Comment by murhafh** [comment]
I'm running the version 2.5 now but I still get the same error when I try to save the translation
"Message not found in backend storage, it is probably corrupted."
on the logs it prints the following:

ERROR message xxxxxxxsx on xxxxx-language disappeared!

**Comment by murhafh** [comment]
Is there anyway I can see more logs?

**Comment by murhafh** [comment]
Actually it is worth mentioning that those xliff files that were added replaced old po files

**Comment by murhafh** [comment]
Is it possible that the strings have IDs that are still cached?

**Comment by nijel** [comment]
I'm not really sure if changing file format won't cause troubles. Changing file formats can lead to issues as each format is handled differently. I remember I've recently fixed some similar issue, but I'm unable to find it right now (I'll try to look it up later). I'd rather delete the old translation component and create new one in such case.

**Comment by nijel** [comment]
Okay what I meant was #991, but it probably doesn't apply here...

**Comment by murhafh** [comment]
Is there a safe way to mark all fuzzy entries as translated after import? I mean not having to go through the translations one by one?

**Comment by nijel** [comment]
Not yet.

**Comment by nijel** [comment]
But you can use Django shell to do that (``./manage.py shell``):

```python
from weblate.trans.models import Unit
Unit.objects.filter(
    translation__subproject__project__slug='project',
    translation__subproject__slug='component'
).update(fuzzy=False)
```

However this will have to be done after every import.

**Comment by murhafh** [comment]
Thank you, I tried doing that but it didn't have any effect, is there anything I need to run after updating the fuzzy flag? loadpo didn't help much either.

**Comment by nijel** [comment]
Did it update any units? It will return number of objects changed...

**Comment by murhafh** [comment]
That's true it writes what seems to be the number of units, though if I check the DB the flag is still set to 1

**Comment by nijel** [comment]
Heads up: Weblate 2.18 will come with proper approved flag handling (see 657edddcf) so workarounds mentioned here will no longer be necessary.
