### ISSUE TITLE
Add language deletion

### ISSUE THREAD

**Issue by nijel** [nijel/weblate#1083]
Managers should be able to delete translation from the UI. It would just delete the file from VCS. This is just a convenience to avoid need to do to VCS if you notice wrongly added language in Weblate.

**Comment by filipef101** [comment]
how to use this?

**Comment by nijel** [comment]
It's in the repository management tab for the language (probably not the best place, but it's there).

**Comment by ieugen** [comment]
Is there a complement to "Start new translation"? I'm looking for "Remove translation" that will remove the translation for one language from weblate but leave the VCS files intact. 

This is a way to _RESET_ translations. Sometimes translations get 0 strings instead. 
Now I have to go to VCS, remove translation file, push. 
Go to weblate, pull, start new translation. 

Having Remove will allow Non Developers (people without git access) to perform these maintenance operations.
