### ISSUE TITLE
Using --language-filter parameter

### ISSUE THREAD

**Issue by collex100** [nijel/weblate#1085]
### Steps to reproduce

I want to get from the listed languages only Russian.
I use the documentation I understood it so.
./manage.py import_project --language-filter  'addons/**/i18n/^(ru)$.po' odoo-80 https://github.com/name1/name2.git  8.0 'addons/**/i18n/*.po'

### Actual behaviour

Usage: ./manage.py import_project [options] <project> <gitrepo> <branch> <filemask>

imports projects with more components

./manage.py: error: no such option: --language-filter

### Expected behaviour
How can I give the command to filter the desired language to me.

### Server configuration
 * Weblate weblate-2.5
 * Python 2.7.3
 * Django 1.8.5
 * six 1.10.0
 * python-social-auth 0.2.13
 * Translate Toolkit 1.13.0
 * Whoosh 2.7.0
 * Git 1.7.10.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.4.4
 * django-crispy-forms 1.5.2
 * compressor 1.5
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.5.2
 * Database backends: django.db.backends.mysql
You have new mail in /var/mail/wblate

**Comment by nijel** [comment]
Sorry, the documentation is wrong - it should be ``--language-regex``. Also the filter is matched against language only, so it should be ``--language-regex=^(ru)$``.

**Comment by collex100** [comment]
Thank you very much!

**Comment by moylop260** [comment]
@collex100 
Do you have public the scripts to use weblate with odoo?
(I can help to integrate for continuos translation)
