### ISSUE TITLE
[Q] Save translation without change

### ISSUE THREAD

**Issue by whedro** [nijel/weblate#1087]
I instaled new instance weblate on UBUNTU+NGINX+USWGI
everything works fine, but when I want to save translation for source, not is save .. :(
what I works wrong ?

Thanks

### Steps to reproduce
1. change or add translation
2. save

### Actual behaviour
not save and still is selected translated source

### Expected behaviour
save translated source

### Server configuration
 * Weblate weblate-2.5-296-g71464b2
 * Python 2.7.6
 * Django 1.9.5
 * six 1.10.0
 * python-social-auth 0.2.14
 * Translate Toolkit 1.14.0-rc1
 * Whoosh 2.7.4
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.2
 * lxml 3.6.0
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * djangorestframework 3.3.3
 * pytz 2016.3
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.7.3
 * Database backends: django.db.backends.mysql

**Comment by whedro** [comment]
I forget .....  I import data from other weblate instance ... (only DB) .. settings.py is created newly

**Comment by nijel** [comment]
Do you get some error? It might be permission related, but you should get error message about that...

**Comment by whedro** [comment]
1. I don't have any error ... everything looks good ...
UWSGI log
[pid: 20586|app: 0|req: 9/22] XXXXXXXXXXX () {44 vars in 1084 bytes} [Tue Apr 26 00:06:59 2016] GET /translate/resitnow/mobile-staff/en/?sid=d344e6aa-0b31-11e6-948a-93046404e097&offset=0 => generated 26556 bytes in 410 msecs (HTTP/1.1 200) 5 headers in 263 bytes (1 switches on core 0)

NGINX log is empty

WEBLATE log is empty

**Comment by nijel** [comment]
This is really strange. Do you get to next unit after sending the form?

PS: The log you show is for GET request, so not for submitting translation....

**Comment by whedro** [comment]
one of error 

2016-04-27 23:53:59,712 DEBUG Exception while resolving variable 'title' in template 'translate.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [title] in u"[{'False': False, 'None': None, 'True': True}, {'rollbar_environment': None, u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f7c63c8a410>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f7c63c944d0>, u'request': <WSGIRequest: GET '/translate/resitnow/mobile-staff/en/?sid=186cc8ce-0cc2-11e6-ac60-f54aa2bb502e&offset=0'>, 'piwik_url': None, 'weblate_url': 'https://weblate.org/?utm_source=weblate&utm_term=2.6-dev', 'offer_hosting': False, 'acl_projects': [<Project: Resitnow>], u'LANGUAGE_CODE': u'en', 'donate_url': 'https://weblate.org/donate/?utm_source=weblate&utm_term=2.6-dev', 'description': u'This site runs Weblate for translating various software projects.', 'google_analytics_id': None, 'site_url': 'http://weblate.XXXXXXXXXXXXXX', 'current_date': '2016-04-27', 'version': '2.6-dev', 'site_title': u'Weblate', 'registration_open': True, 'login_redirect_url': u'/translate/resitnow/mobile-staff/en/?sid=186cc8ce-0cc2-11e6-ac60-f54aa2bb502e&offset=0', 'demo_server': False, 'rollbar_token': None, 'current_month': '04', 'subscribed_projects': [<Project: Resitnow>], u'LANGUAGES': ((u'az', u'Az\\u0259rbaycan'), (u'be', u'\\u0411\\u0435\\u043b\\u0430\\u0440\\u0443\\u0441\\u043a\\u0430\\u044f'), (u'be@latin', u'Bie\\u0142aruskaja'), (u'br', u'Brezhoneg'), (u'ca', u'Catal\\xe0'), (u'cs', u'\\u010ce\\u0161tina'), (u'da', u'Dansk'), (u'de', u'Deutsch'), (u'en', u'English'), (u'el', u'\\u0395\\u03bb\\u03bb\\u03b7\\u03bd\\u03b9\\u03ba\\u03ac'), (u'es', u'Espa\\xf1ol'), (u'fi', u'Suomi'), (u'fr', u'Fran\\xe7ais'), (u'fy', u'Frysk'), (u'gl', u'Galego'), (u'he', u'\\u05e2\\u05d1\\u05e8\\u05d9\\u05ea'), (u'hu', u'Magyar'), (u'id', u'Indonesia'), (u'it', u'Italiano'), (u'ja', u'\\u65e5\\u672c\\u8a9e'), (u'ko', u'\\ud55c\\uad6d\\uc5b4'), (u'ksh', u'K\\xf6lsch'), (u'nl', u'Nederlands'), (u'pl', u'Polski'), (u'pt', u'Portugu\\xeas'), (u'pt-br', u'Portugu\\xeas brasileiro'), (u'ru', u'\\u0420\\u0443\\u0441\\u0441\\u043a\\u0438\\u0439'), (u'sk', u'Sloven\\u010dina'), (u'sl', u'Sloven\\u0161\\u010dina'), (u'sr', u'\\u0421\\u0440\\u043f\\u0441\\u043a\\u0438'), (u'sv', u'Svenska'), (u'tr', u'T\\xfcrk\\xe7e'), (u'uk', u'\\u0423\\u043a\\u0440\\u0430\\u0457\\u043d\\u0441\\u044c\\u043a\\u0430'), (u'zh-hans', u'\\u7b80\\u4f53\\u5b57'), (u'zh-hant', u'\\u6b63\\u9ad4\\u5b57')), 'user': <SimpleLazyObject: <User: whedro>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'piwik_site_id': None, 'hooks_enabled': True, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f7c63cd1610>, 'current_year': '2016', 'enable_avatars': True, 'enable_sharing': True, u'LANGUAGE_BIDI': False}, {}, {u'filter_name': u'All strings', u'object': <Translation: Resitnow/Mobile Staff - English>, 'description': u'Resitnow is translated into 8 languages using Weblate. Join the translation or start translating your own project.', u'form': <TranslationForm bound=False, valid=Unknown, fields=(checksum;target;fuzzy)>, u'offset': 0, u'update_lock': False, u'project_locked': False, u'prev_unit_url': u'http://weblate.XXXXXXXXXXXXXX/translate/resitnow/mobile-staff/en/?sid=186cc8ce-0cc2-11e6-ac60-f54aa2bb502e&offset=-1', u'comment_form': <CommentForm bound=False, valid=Unknown, fields=(comment;scope)>, u'filter_pos': 1, u'total': 20, u'unit': <Unit: 89b11352b6e9cb819774ba5b49bfa844 on Resitnow/Mobile Staff - English>, u'secondary': [], u'locked': False, u'last_unit_url': u'http://weblate.XXXXXXXXXXXXXX/translate/resitnow/mobile-staff/en/?sid=186cc8ce-0cc2-11e6-ac60-f54aa2bb502e&offset=19', u'filter_count': 20, u'first_unit_url': u'http://weblate.XXXXXXXXXXXXXX/translate/resitnow/mobile-staff/en/?sid=186cc8ce-0cc2-11e6-ac60-f54aa2bb502e&offset=0', u'glossary': [], u'search_query': u'', u'search_form': <SearchForm bound=False, valid=Unknown, fields=(q;search;source;target;context;location;comment;type;ignored)>, u'addword_form': <InlineWordForm bound=False, valid=Unknown, fields=(source;target)>, u'project': <Project: Resitnow>, u'next_unit_url': u'http://weblate.XXXXXXXXXXXXXX/translate/resitnow/mobile-staff/en/?sid=186cc8ce-0cc2-11e6-ac60-f54aa2bb502e&offset=1', u'user_locked': False, u'this_unit_url': u'http://weblate.XXXXXXXXXXXXXX/translate/resitnow/mobile-staff/en/?sid=186cc8ce-0cc2-11e6-ac60-f54aa2bb502e&offset=0', u'antispam': <AntispamForm bound=False, valid=Unknown, fields=(content)>, u'search_id': u'186cc8ce-0cc2-11e6-ac60-f54aa2bb502e', u'others': []}, {}]"



Could by problem that I have utl to weblate with HTTPS, but in log is HTTP ?

Forgot I something in config ?

Thanks ..

PS I have NGINX

**Comment by nijel** [comment]
The http/https is based on [ENABLE_HTTPS](https://docs.weblate.org/en/latest/admin/config.html#enable-https) setting, but that should not cause this problem.

Also the warning should be harmless, the code is testing whether title is set before using:

```
{% if title %}{{ title }}{% else %}...
```

**Comment by whedro** [comment]
hmm . I don't know, where is problem ..

**Comment by whedro** [comment]
LOL ... again .... if is DEBUG = True, everything is OK .. by if is value False, problem is like above ..
I was same problem before. .. #966 .... DEBUG value

**Comment by nijel** [comment]
There has to be something weird in your setup, I've never seen such issues...

**Comment by whedro** [comment]
hmm .. ok .. I close it....
