### ISSUE TITLE
Add component for project with Push on commit

### ISSUE THREAD

**Issue by martinpucik** [nijel/weblate#1091]
When the project has `Push on commit` turned on, creation of component for this project will fail with error below. Weblate log only this message:

```
weblate[15786]: INFO project-name/component-name: updating repository
weblate[15786]: INFO project-name/component-name: update took 0.28 seconds:

```

After disabling `Push on commit` for project, component creation will succeed with the same configuration.

### Steps to reproduce
1. Create new project
2. Check on `Push on commit`
3. Save Project
4. Create new component for project

### Actual behaviour

Component creation fails with error:

`Failed to update repository: fatal: bad revision 'origin/master..' (128)`

### Server configuration

Weblate version: `2.6`

**Comment by nijel** [comment]
I've hit this today as well, already fixed in 6390eb9f09269f8154f13d2bc365fcfcd3ae3d5e.
