### ISSUE TITLE
getting an error when trying to delete a component 

### ISSUE THREAD

**Issue by murhafh** [nijel/weblate#1095]
### Steps to reproduce
1.admin UI
2. Select components 
3. Select a component and chose delete -> go

### Actual behaviour
After a long wait I get are you sure UI, then when I select yes there is also a long wait and then I get internal server error. 
The apache Error log showing the following error:
Premature end of script headers: wsgi.py,  

This sounds like Django error?

### Expected behaviour
Be able to delete the component 

### Server configuration
 * Weblate weblate-2.5
 * Python 2.7.3
 * Django 1.8
 * six 1.10.0
 * python-social-auth 0.2.18
 * Translate Toolkit 1.13.0
 * Whoosh 2.7.4
 * Git 2.8.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.6.0
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.2.4
 * Database backends: django.db.backends.mysql

**Comment by murhafh** [comment]
Note that I recently updated to 2.5 version

**Comment by nijel** [comment]
Can you please provide backtrace you get with the error (eg. from admin mails or server logs)?

**Comment by murhafh** [comment]
Nothing is printed on Apache error.log more than this, and the log file looks empty, I have DEBUG set to true in the settings.py but that doesn't help much, any idea what could be happening?

**Comment by nijel** [comment]
With DEBUG enabled, you should get error in the web as well.

What might be the problem is that the request simply takes too long. The admin interface lists all items which will be deleted for confirmation and if these components contain many translations, it might simply just take too long...

**Comment by murhafh** [comment]
Is there a way around that?

**Comment by nijel** [comment]
You can also delete them from Django shell (``./manage.py shell``):

```py
from weblate.trans.models import SubProject
component = SubProject.objects.get(project__slug='project', slug='component')
component.delete()
```

**Comment by murhafh** [comment]
Thank you! this works.

**Comment by nijel** [comment]
Great, there really should be CLI for this as well, see #1092
