### ISSUE TITLE
Memory leak while trying to delete language (en)

### ISSUE THREAD

**Issue by ihoru** [nijel/weblate#1097]
### Steps to reproduce
1. Create project with source language en (for example), it will have source_language_id=31 (from migration)
2. Go to /admin/lang/language/?p=0 (list of languages)
3. Select English in the list and choose to delete it.

### Actual behaviour
You will wait loading till memory on your server finish and worker will be killed.

### Expected behaviour
Show error, that this language is in use with a project.

### Server configuration
 * Weblate weblate-2.6
 * Python 2.7.11+
 * Django 1.9.5
 * six 1.10.0
 * python-social-auth 0.2.18
 * Translate Toolkit 1.14.0-rc1
 * Whoosh 2.7.4
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.6.0
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * djangorestframework 3.3.3
 * pytz 2016.4
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.7.3
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
30. dubna 2016 18:04:49 SELČ, Ihor Polyakov <notifications@github.com> napsal:
>### Steps to reproduce
>1. Create project with source language en (for example), it will have
>source_language_id=31 (from migration)
>2. Go to /admin/lang/language/?p=0 (list of languages)
>3. Select English in the list and choose to delete it.
>
>### Actual behaviour
>You will wait loading till memory on your server finish and worker will
>be killed.
>
>### Expected behaviour
>Show error, that this language is in use with a project.
>
>### Server configuration
> * Weblate weblate-2.6
> * Python 2.7.11+
> * Django 1.9.5
> * six 1.10.0
> * python-social-auth 0.2.18
> * Translate Toolkit 1.14.0-rc1
> * Whoosh 2.7.4
> * Git 2.7.4
> * Pillow (PIL) 1.1.7
> * dateutil 2.5.3
> * lxml 3.6.0
> * django-crispy-forms 1.6.0
> * compressor 1.6
> * djangorestframework 3.3.3
> * pytz 2016.4
> * pyuca N/A
> * pyLibravatar N/A
> * Mercurial 3.7.3
> * Database backends: django.db.backends.mysql
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nijel/weblate/issues/1097

It's not a memory leak, it's just Django trying to show you all objects it is going to delete. I'm not sure if there is way to disable this.

**Comment by ihoru** [comment]
There were no much items there (I've deleted it with queries to database), less than 100 affected rows.

**Comment by nijel** [comment]
Including units and all other stuff?

**Comment by ihoru** [comment]
Yes. I know it, because when I tried to delete parent item (language) it was saying what I should delete first (in other table).
