### ISSUE TITLE
Update behavior when value in source language is changed

### ISSUE THREAD

**Issue by myrnazhou** [nijel/weblate#1105]
### Steps to reproduce
1. Change value of old string in source language
2. Save it
### Actual behaviour

Value for that string in other languages remain the same
### Expected behaviour

Other languages should automatically use new value from the source language. Is there any setting to enable this?
### Server configuration

I'm using the hosted.weblate.org
##

**Comment by nijel** [comment]
It is really expected to work like this and it works correctly in my tests.

**Comment by nijel** [comment]
I've finally understood the concern:

>> You've updated ``Language.resx`` with English strings and you expect Weblate
>> to update all ``Languge.*.resx`` with new string as **translation**, am I
>> right? 

Weblate will not do this by default, but there could be integrated to existing hook (examples/hook-update-resx)

**Comment by Antonyo** [comment]
Hello, just as a more clarifying example. Assuming we have just 2 languages, french and spanish, and our source language is english, we would need an option so then an string is updated in the source language, the same string in english is copied into french and english. So imagine we have the string named welcome_message:

Source                                       ES                                            FR
-----------------------------------------------------------------------------------------------
"Welcome message"                 "Mensaje de bienvenida"        "Message de bienvenue"

And we change the same string into:

Source                                       ES                                            FR
-----------------------------------------------------------------------------------------------
"Hello user"                                "Mensaje de bienvenida"        "Message de bienvenue"

We would require an option so the rest of the languages are updated to the same value:

Source                                       ES                                            FR
-----------------------------------------------------------------------------------------------
"Hello user"                                "Hello user"                            "Hello user"

**Comment by nijel** [comment]
Fix is now deployed on Hosted Weblate as well.

**Comment by myrnazhou** [comment]
Thanks @nijel
