### ISSUE TITLE
Getting an error when trying to update translations

### ISSUE THREAD

**Issue by murhafh** [nijel/weblate#1107]
### Steps to reproduce
1. Created a new project with xliff file format
2. After the project was added I tried to update any of the strings and save 

### Actual behaviour
All strings marked as fuzzy and not translated
When I try to update a string I got the following message
"Message not found in backend storage, it is probably corrupted."
And on the server I got an error 
"message 71a95cc84cee748b2857e095866bea93 on project/component disappeared!"

### Expected behaviour
Should be able to change the translation 

### Server configuration
 * Weblate weblate-2.5
 * Python 2.7.3
 * Django 1.8
 * six 1.10.0
 * python-social-auth 0.2.18
 * Translate Toolkit 1.13.0
 * Whoosh 2.7.4
 * Git 2.8.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.6.0
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.2.4
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
Please upgrade to 2.6, 2.5 has several bugs with xliff (see #939 and #1021).

**Comment by murhafh** [comment]
I tried doing that but I got a migration error when running ./manage.py migrate:

"django.db.migrations.graph.NodeNotFoundError: Migration accounts.0016_add-api-keys dependencies reference nonexistent parent node (u'authtoken', u'0001_initial')"

Any idea why this is happening?

**Comment by nijel** [comment]
Yes, please adjust settings.py to new version, there are new apps which need to be included there.

**Comment by murhafh** [comment]
Thank you, it started running after I updated the settings file but now it is stuck at the step:

Applying accounts.0016_add-api-keys
It says: ValueError: Cannot query "User object": Must be "User" instance.

**Comment by murhafh** [comment]
Actually second time I run it, it says ok

**Comment by murhafh** [comment]
I got the update to work finally but now when I try to change any string, I get no error, the page seems to refresh and the change I made gets reverted. I got no errors on the server side either

**Comment by nijel** [comment]
Hmm, that sounds a bit similar to #1103...

**Comment by murhafh** [comment]
Yeah basically nothing happens when the form is submitted, but in my case I cannot edit anything in the translations

**Comment by murhafh** [comment]
Actually on some browsers I get this message "This form will be sent in a way that is not secure. Are you sure you want to send it?"

But that seems related to https I don't think it is relevant

**Comment by murhafh** [comment]
Also the page doesn't go to the next translation, it just stays in the same page

**Comment by nijel** [comment]
It is probably causing the problems, as you web server is most likely set to redirect to HTTPS, so what happens:

1. HTTP POST with translation
2. Web server redirects to SSL
3. Browser does HTTP GET on current translation

See https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-2-5-to-2-6 and https://docs.weblate.org/en/latest/admin/install.html#production-site for instructions.

**Comment by murhafh** [comment]
Thank you, I think I have the correct site name set up. Is there a way to double check this

**Comment by murhafh** [comment]
I actually activated HTTPS and then it started working as expected.

**Comment by murhafh** [comment]
Thanks for your help!
