### ISSUE TITLE
Add multi language status widget

### ISSUE THREAD

**Issue by nijel** [nijel/weblate#1109]
In addition to overall progress widgets it would be interesting to have widget showing status in all languages.

It can be either created as SVG or use Google Charts API to render them...

Example:

![68747470733a2f2f7777772e7472616e73696665782e636f6d2f70726f6a656374732f702f726963696e2f7265736f757263652f726963696e706f742f63686172742f696d6167655f706e67](https://cloud.githubusercontent.com/assets/212189/15173217/2c488b28-175b-11e6-8f47-e0bae33f09c0.png)

**Comment by PopAdi** [comment]
Hi!
Is there a page or a specific place where this widget should be? I worked with Google Charts API and I would like to try to do it. Thanks!

**Comment by nijel** [comment]
There is already generic code for generating widgets: https://github.com/nijel/weblate/blob/master/weblate/trans/widgets.py

However I'd prefer to generate SVG directly without relying on third party service for this.

**Comment by dg0yt** [comment]
Nice widget, but some remarks:
- It seems to use a global interpretation of 100%. (In [my project](https://hosted.weblate.org/widgets/openorienteering/), languages have different numbers of source strings. But there are too many languages which exceed 100%, while English has only 0% in this widget.
- I actually like the bars being colored according to completeness (cf. [this status page](https://github.com/OpenOrienteering/mapper/wiki/Translation#next-release-mapper-064-and-unstable-development-snapshot)).
- I'm not an SVG expert... Would it be possible to have direct per-language-bar translation links?

**Comment by nijel** [comment]
Links should be doable, colors based on status as well. Can you please open separate issues for that?
