### ISSUE TITLE
[ts] Request to collapse empty XML elements

### ISSUE THREAD

**Issue by bjorn** [nijel/weblate#1118]
### Steps to reproduce
1. Have a project using the .ts format
2. Notice that Weblate writes location info like `<location line="+83"></location>`
3. Since this is different from what Qt Linguist does (`<location line="+83"/>`), it leads to huge diffs when Weblate and Qt Linguist are used interchangeably.

### Expected behaviour
Collapsing empty XML elements makes sense both for avoiding these huge diffs as well as for space-saving reasons, since it is unnecessary verbosity.

There are some other differences in the output (another example below), but the expanded XML elements are causing by far the most changes.
```
-<?xml version="1.0" encoding="utf-8"?> (Qt Linguist)
+<?xml version='1.0' encoding='utf-8'?> (Weblate)
```
### Server configuration
Using hosted Weblate (https://hosted.weblate.org/projects/tiled/)

**Comment by nijel** [comment]
This behavior comes from translate-toolkit, library we use for manipulation with the files.

The closing tags were added intentionally in https://github.com/translate/translate/commit/e2b714eb02d88fb3c995bfd0296272409a9709e0, see also https://github.com/translate/translate/issues/1420.

For the header this was already discussed in https://github.com/nijel/weblate/issues/462, but I don't think anybody has talked with translate-toolkit upstream to address this.

**Comment by bjorn** [comment]
Ah, thanks for the pointers! It's interesting that they already tried to match the Qt Linguist format better, but the "Pretty-print empty tags without self-closing them" is only half the story, since while Qt Linguist does not self-close the `translation` element, it does self-close the `location` element. I'll see if I can do a pull request against translate.

**Comment by bjorn** [comment]
I've opened translate/translate#3443 for this.

**Comment by dg0yt** [comment]
Updated in translate/translate#3465. The difference which is left open is the handling of '/" vs. &apos;/&quot;.

**Comment by dg0yt** [comment]
The first PR to translate got merged. Now i submitted translate/translate#3470 for writing quotes as entities. Since this requires postprocessing of the XML output, it somewhat slows down saving as .ts.

**Comment by nijel** [comment]
Closing this issue as there is nothing what could be done on Weblate side to improve this.

**Comment by bjorn** [comment]
@nijel You mean Weblate will automatically pick up this improvement once translate/translate#3470 is merged?

**Comment by bjorn** [comment]
Is Weblate already updated to use the improvements submitted in translate/translate#3465?

**Comment by nijel** [comment]
Weblate will use installed translate-toolkit, so whatever fixes it has, those will work in Weblate.
