### ISSUE TITLE
Difference in projects list between "My subscriptions" and "My Dashboard"

### ISSUE THREAD

**Issue by ldmpub** [nijel/weblate#1124]
### Steps to reproduce
It may be a bug coming from my account history.

### Actual behaviour
There is a difference in projects list between "My subscriptions" and "My Dashboard"; see 2 attached screen shots => for instance Freeplane is missing on my dashboard.

### Expected behaviour
Same project list on both sides.

![1 my subscriptions](https://cloud.githubusercontent.com/assets/1452146/15422740/388487ae-1e7a-11e6-9b0f-09832f5d56b9.jpg)
![2 my dashboard](https://cloud.githubusercontent.com/assets/1452146/15422739/3883d4f8-1e7a-11e6-8804-eb226c61135e.jpg)

**Comment by nijel** [comment]
Disable "Hide completed translations on dashboard" to see them all :-).

**Comment by ldmpub** [comment]
So easy! => it's now ok and I have improved the french translation.

Many thanks
