### ISSUE TITLE
Weblate does not remove obsolete strings from translations (android resources)

### ISSUE THREAD

**Issue by pavolzibrita** [nijel/weblate#113]
Weblate does not remove existing obsolete strings that are in translations and not in the template file.
It could remove them upon first commit, or directly change the files when the files are loaded and compared with the template. Or I don't know. Is there some command for this?

Part of compiler warnings when there are obsolete strings in translations:
```
     [aapt] aapt: warning: string 'simulate_route_progression_manually' has no default translation in /var/lib/jenkins/workspace/Osmand-default/OsmAnd/res; found: af bg bs cs de es eu fr hi hu hy id it ka ko lt lv mr nl pl pt ru uk
     [aapt] aapt: warning: string 'tip_app_mode_t' has no default translation in /var/lib/jenkins/workspace/Osmand-default/OsmAnd/res; found: af bg bs cs es eu fr hi hu hy id it jp ka ko lt lv mr nl pl pt ru sk uk vi
     [aapt] aapt: warning: string 'tip_day_night_mode_t' has no default translation in /var/lib/jenkins/workspace/Osmand-default/OsmAnd/res; found: af bg bs cs es eu fr hi hu hy id it jp ka ko lt lv mr nl pl pt ru sk uk vi
     [aapt] aapt: warning: string 'tip_map_switch_t' has no default translation in /var/lib/jenkins/workspace/Osmand-default/OsmAnd/res; found: af bg bs cs es eu fr hi hu hy id it jp ka ko lt lv mr nl pl pt ru sk uk vi
     [aapt] aapt: warning: string 'tip_rotation_switching_t' has no default translation in /var/lib/jenkins/workspace/Osmand-default/OsmAnd/res; found: af bg bs cs es eu fr hi hu hy id it jp ka ko lt lv mr nl pl pt ru sk uk vi
     [aapt] aapt: warning: string 'use_transparent_map_theme_descr' has no default translation in /var/lib/jenkins/workspace/Osmand-default/OsmAnd/res; found: af bg bs cs de es eu fr hi hu hy id it ka ko lt lv mr nl pl pt ru sk uk
```

**Comment by nijel** [comment]
I've just got another request for such cleanup, this time for Resx, so it probably makes sense to introduce something like this and have that configurable.

**Comment by nijel** [comment]
Okay, I think the best approach to do this is in the post update VCS hook. For now I've implemented it for resx including adding of missing strings (see 64a21ae). Something like this can be implemented for every format, the only problem is that there is no API in translate toolkit to remove unit, so this has to be done by manipulating underlaying storage and thus will be always file format specific.
