### ISSUE TITLE
PRE_COMMIT_SCRIPTS are not updated

### ISSUE THREAD

**Issue by stanislav-brabec** [nijel/weblate#1130]
When editing PRE_COMMIT_SCRIPTS, only first change is reflected.

### Steps to reproduce
1. Configure in settings.py
PRE_COMMIT_SCRIPTS = (
    '/usr/share/weblate/examples/hook-generate-mo',
)
2. Restart web server
3. Go to any sub-project admin interface
4. Change it to:
PRE_COMMIT_SCRIPTS = (
    '/usr/share/weblate/examples/hook-update-linguas',
)
5. Restart web server
6. Go to the sub-project admin interface as above

### Actual behaviour
Only hook-generate-mo pre-commit script is allowed

### Expected behaviour
Only hook-update-linguas pre-commit script should be allowed

### Server configuration
 * Weblate 2.6
 * Python 2.7.9
 * Django 1.8.4
 * six 1.9.0
 * python-social-auth 0.2.7
 * Translate Toolkit 1.14.0-rc1
 * Whoosh 2.7.0
 * Git 1.8.5.6
 * Pillow (PIL) 1.1.7
 * dateutil 2.1
 * lxml 3.2.3
 * django-crispy-forms 1.5.2
 * compressor 1.5
 * djangorestframework 3.3.3
 * pytz 2013.9
 * pyuca N/A
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
Are you sure you've restarted the web server and it using the settings you have changed? I've done this many times and it has always worked fine....

**Comment by stanislav-brabec** [comment]
Yes, verified my current config:

PRE_COMMIT_SCRIPTS = (
    '/usr/share/weblate/examples/hook-update-linguas',
)

Did
rcapache2 restart

Verified that all httpd-prefork PIDs changed before and after restart.

Shift-Reloaded https://l10n.opensuse.org/admin/trans/subproject/10/

hook-generate-mo is the only item.

**Comment by stanislav-brabec** [comment]
My mistake. The configuration line was added twice.
