### ISSUE TITLE
Weblate changes repository filemodes to 0755

### ISSUE THREAD

**Issue by jtiai** [nijel/weblate#1133]
### Steps to reproduce
1.Import mercurial project to weblate
2.files have changed their file mode to 0755
3.

### Actual behaviour
files have changed their file mode to 0755

### Expected behaviour
files should keep their filemode as is.

### Server configuration
 * Weblate 2.4
 * Python 2.7.9
 * Django 1.8.3
 * python-social-auth 0.2.12
 * Translate Toolkit 1.13.0
 * Whoosh 2.7.0
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.4.0
 * django-crispy-forms 1.5.2
 * compressor 1.5
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.1.2

**Comment by jtiai** [comment]
I could find at least one occurence which does that for apparent no reason.

[/weblate/trans/management/commands/import_project.py#L186](https://github.com/nijel/weblate/blob/fa41f13e7115949ee208a0a6d0d93cbd6d7c4b1a/weblate/trans/management/commands/import_project.py#L186)

**Comment by nijel** [comment]
Are you running weblate as uwsgi?

**Comment by nijel** [comment]
And that one is there for reason - it changes permissions in temporary directory, which is created as 0700, so it would not be accessible to others.

**Comment by jtiai** [comment]
I'm running it in a container as instructed in https://docs.weblate.org/en/latest/admin/deployments.html#weblate-and-docker  only change I did was to map /app/data to host filesystem.

**Comment by nijel** [comment]
And what is the host filesystem?

**Comment by jtiai** [comment]
ext4, host running ubuntu 16.04.

**Comment by nijel** [comment]
That shouldn't cause any problems. Anyway Weblate does nothing special in this case, so I really wonder why the modes are changed (it really does just hg clone in the end without doing anything with the files).

**Comment by jtiai** [comment]
I'll keep investigating. If nothing comes back in few days close the issue.

**Comment by nijel** [comment]
Have you figured out anything?
