### ISSUE TITLE
Export statistics as CSV

### ISSUE THREAD

**Issue by shanewims** [nijel/weblate#1136]
At the start of the project, we need to gather wordcount statistics in order to determine how much the translations will cost.

On pages where wordcount statistics are displayed, can there be a button that enables the Language Project Manager to export the wordcounts to a spreadsheet or csv text file?
##

**Comment by shanewims** [comment]
It makes sense because the Project Manager will need to gather statistics for 16 languages across many packages in our case.

**Comment by nijel** [comment]
Use [statistics API](https://docs.weblate.org/en/latest/api.html#get--api-translations-%28string-project%29-%28string-component%29-%28string-language%29-statistics-), it provides all the information.

**Comment by shanewims** [comment]
Our vendor program managers need a way to do this in the user interface.

**Comment by nijel** [comment]
The same data is currently also available from the UI, see https://docs.weblate.org/en/latest/api.html#exports

**Comment by shanewims** [comment]
We really need some simple way to quickly export localisation statistics such as a button on the page that exports to csv or some standard format. Our vendor is not in a position to program Weblate.

**Comment by nijel** [comment]
It used to be there (though in JSON), but it got deprecated in favor of API. Exporting stats in some end user accessible format might make sense as well.

**Comment by shanewims** [comment]
Hi, I just want to give an example of the statistics reporting our current tool provides. The project manager is concerned with totals. The localisation engineer is interested in file by file analysis, in order to pinpoint any files with unusually high wordcounts for example. Please see the attached report.

[de_wordcount.zip](https://github.com/nijel/weblate/files/285913/de_wordcount.zip)

**Comment by wandeg** [comment]
Hi, is it ok if I try this?

**Comment by nijel** [comment]
Yes, you're welcome :-).

**Comment by wandeg** [comment]
Should this use the stats api? If so, is there an existing example of where it is used. 
Also are the stats being exported the same as the ones on the stats page?

**Comment by nijel** [comment]
The stats are calculated on the model level, so there should not be need to do anything specific here. Pretty much all what is needed is to aggregate per component stats and make them available as CSV.
