### ISSUE TITLE
How to run Weblate behind nginx Reverse Proxy

### ISSUE THREAD

**Issue by dangkiena3** [nijel/weblate#1138]
I builded a weblate proxy, but when I run it behind a nginx reverse proxy, it's not work:

![image](https://cloud.githubusercontent.com/assets/18433986/15624766/88a68b46-24bb-11e6-85e9-6bdb490c1926.png)

This is my nginx config:

 location /weblate {       
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;    
            proxy_redirect   off;
            proxy_pass       http://10.0.25.118:80;
        }

Please help me to run it. Thank you very much

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/install.html#sample-configuration-for-nginx
