### ISSUE TITLE
[Banner] RTL text is reversed

### ISSUE THREAD

**Issue by GreenLunar** [nijel/weblate#1140]
See
https://hosted.weblate.org/widgets/weblate/he/287x66-grey.png
https://hosted.weblate.org/widgets/weblate/he/88x31-grey.png
https://hosted.weblate.org/widgets/weblate/he/status-badge.png

Instead of "RTL text is reversed", it reads as "desrever si txet LTR".

To fix this, I suggest to pass an LRO (`U+202D LEFT-TO-RIGHT OVERRIDE`) invisible character at start of each line.  LTR texts should not be affected.

Subject tested: https://hosted.weblate.org/widgets/weblate/he/88x31-grey.png

As is:
Weblate
תירבעל םוגרת
ומלשוה 64%

With LRO at start of every line:
‭Weblate
‭תירבעל םוגרת
‭ומלשוה 64%

**Comment by nijel** [comment]
Not sure if used renderer supports LRO, but definitely worth trying.

**Comment by GreenLunar** [comment]
It might not be; for example, to translate an RTL string that appears in console (does not support UTF-8) and graphical UI (supports UTF-8), I translate it reversely and add LRO at its start so it would appear properly on both.
