### ISSUE TITLE
Zen mode for suggestions and different translations

### ISSUE THREAD

**Issue by stanislav-brabec** [nijel/weblate#1144]
### Steps to reproduce
1. Have hundreds of suggestions of strings with different translations.

### Actual behaviour
Hundreds of dialogs, needs to click hundreds of times.

### Expected behaviour
Have a Zen mode, where I can review everything on one page, and either decide which one to select (by a check box), or click to Accept to all.

### Server configuration
Weblate 2.6
Python 2.7.9
Django 1.8.4
six 1.9.0
python-social-auth 0.2.7
Translate Toolkit 1.14.0-rc1
Whoosh 2.7.0
Git 1.8.5.6
Pillow (PIL) 1.1.7
dateutil 2.1
lxml 3.2.3
django-crispy-forms 1.5.2
compressor 1.5
djangorestframework 3.3.3
pytz 2013.9
pyuca N/A
Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
See https://github.com/nijel/weblate/issues/671
