### ISSUE TITLE
New feature: comment editing

### ISSUE THREAD

**Issue by matejcik** [nijel/weblate#1148]
it could be useful to have the option to delete or edit comments

**Comment by nijel** [comment]
There is option to delete comments, you just need permission to do that :-).

**Comment by matejcik** [comment]
oh, ok :e)

i guess i will leave this open for the "edit comments" part, until we clarify whether we actually need that

**Comment by nijel** [comment]
I don't find editing comments that useful, it's IMHO cleaner approach to delete obsolete one and add new one.

**Comment by nijel** [comment]
Closing for now, feel free to comment if you have good reason for editing comments :-).
