### ISSUE TITLE
php strings error 'NoneType' object has no attribute 'isfuzzy'

### ISSUE THREAD

**Issue by badconker** [nijel/weblate#1149]
Hi,
For several hours, i try to make weblate work with my laravel project but i can't do it. Maybe i missed something.

So i have a first php file with french strings : 

```php
<?php
$lang = array(
    'nb_stats'                   => ':nb statistique|:nb statistiques',
    'nb_recompenses'             => ':nb récompense|:nb récompenses',
    'nb_points'                  => ':nb point|:nb points',
    'nb_joueurs'                 => ':nb joueur|:nb joueurs',
    'contacts'                   => 'contacts',
    'contact_already_up_to_date' => 'Déjà mis à jour il y a moins de :hours heures',
    'tous_les_jeux'              => 'tous les jeux',
    'pictos'                     => 'pictos',
    'connexion'                  => 'connexion',
    'deconnexion'                => 'déconnexion',
    'categories'                 => "Catégories",
    'recherche'                  => "Recherche",
    'toutes-categories'          => "toutes",
);
return $lang;
```
And i create an english file because i have read in documentation : 

> Following things are known to be broken:
> Adding new units to translation, every translation has to contain all strings (even if empty).

```php
<?php
$lang = array(
    'nb_stats'                   => '',
    'nb_recompenses'             => '',
    'nb_points'                  => '',
    'nb_joueurs'                 => '',
    'contacts'                   => '',
    'contact_already_up_to_date' => '',
    'tous_les_jeux'              => '',
    'pictos'                     => '',
    'connexion'                  => '',
    'deconnexion'                => '',
    'non_officiel'               => '',
    'categories'                 => '',
    'recherche'                  => '',
    'toutes-categories'          => '',
);
return $lang;
```
The two languages appear in Weblate, no problem but when i want to translate a string for english language, i get error : 

`'NoneType' object has no attribute 'isfuzzy'`

[Traceback](https://framabin.org/?3ddc3128d74caf68#Okw9IiIyKx5H8uNPmwEzE7BknQWWNvvNXPQvbrrJKuM=)

![Screen](http://g.recordit.co/fl0fWab513.gif)

I noted that the error disappear if english strings are not empty, but i cannot fill them with french text by default otherwise i can not see them as not translated strings on weblate

(sorry for my english)

### Server configuration
 * Weblate weblate-2.6-237-g6e024a2
 * Python 2.7.6
 * Django 1.9.7
 * six 1.10.0
 * python-social-auth 0.2.19
 * Translate Toolkit 2.0.0b2
 * Whoosh 2.7.4
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.3.3
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * djangorestframework 3.3.3
 * pytz 2012c
 * pyuca N/A
 * pyLibravatar N/A
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
The support for PHP files in translate-toolkit (library we use for manipulating with files) is indeed problematic...

**Comment by badconker** [comment]
After searchs, i found this linked issue : #910 
If i remove your workaround, i have exactly the same format issue.
Have you read this ? : https://github.com/nijel/weblate/issues/910#issuecomment-154852926
Because i confirm this code works : https://github.com/nijel/weblate/issues/910#issuecomment-153318297

**Comment by nijel** [comment]
Okay, then let's discuss it there and I'll close this one as duplicate.

**Comment by lighter** [comment]
Hello @nijel 

I had the same problem. My language resource is php. And I tried to modify the language is *Thai*. How can I fix it? Thanks your help.

This is my Traceback [http://dpaste.com/33T5FRX](url)

This is my Input data, original `$lang['plz_contact_service_with_deposit_bank_info']`, translate `ข้อมูลเงินฝากธนาคาร`

**Comment by nijel** [comment]
There is workaround mentioned in https://github.com/WeblateOrg/weblate/issues/910, I don't know if somebody is working on improving PHP support...
