### ISSUE TITLE
How to limit users to a certain language?

### ISSUE THREAD

**Issue by TTmiro** [nijel/weblate#1152]
Hi folks,

I try to achieve the following:

I want to work with several translators, each translator should be able to save translations for his/her language but not for any other language.

I created the following groups

	translators_chinese
	translators_french
	translators_german
	translators_russian
	translators_spanish
	translators_vietnamese

with the following rights

trans | translation | Can change translation
trans | translation | Can save translation
trans | Project | Can access project Project Name

in Group ACL I created the following languages and linked it to the corresponding group

        Vietnamese	Project Name/messages	translators_vietnamese
	Spanish	Project Name/messages	   translators_spanish
	Russian	Project Name/messages	   translators_russian
	German	Project Name/messages	   translators_german
	French	Project Name/messages	   translators_french
	Chinese	Project Name/messages	   translators_chinese
	German	Project Name/messages	   translators_german

Finally I linked users to groups (e.g.):

user.name
       translators_french
       Users
       Project Name

By logging in as user.name I can access all languages (this is fine) without save or suggest button - but these buttons are as well missing for French. 

How can I enable these buttons for certain languages? 

Thank you for reading my question - your help his highly appreciated.

Kind regards,
Michel

**Comment by nijel** [comment]
Most likely related to #1024, maybe @matejcik has some hints on this.

**Comment by matejcik** [comment]
@TTmiro are you sure you are using the permission "trans | **unit** | Can save translation" ? Your mesasge says "trans | _translation_ | Can save translation"; no such permission exists AFAICT, and the important one is in the "unit" category.

This could certainly use some usability improvements.

**Comment by TTmiro** [comment]
@matejcik thanks for reply. my current configuration is:

user.name has
- Chosen groups: translators_french
- Chosen user permissions: trans | Project | Can access project Project Name

translators_french has
- trans | Project | Can access project Project Name
- trans | Component | Can lock translation for translating
- trans | unit | Can save translation

Group ACL has
French  Project Name/messages      translators_french

Now the save button is shown and usable but the user can see and user the save button for all other languages as well (expect English - which is source).

What do I need to change to let all save buttons disappear except the one for french?

Thank you in advance for you support!

Best,
Michel

**Comment by matejcik** [comment]
languages (and projects, subprojects) that are not covered by Group ACL use the old permission rules

so if you don't want your user to have the ability to save other languages, you can, for example, remove the user from the Users group.
or remove the "trans | unit | Can save translation" from Users
