### ISSUE TITLE
Cannot see machine translation menu

### ISSUE THREAD

**Issue by desmax** [nijel/weblate#1159]
Hello.

Somehow I cannot see machine translation tab, although I enabled it in settings.. Where actually look for it?
I use weblate as an admin.

```

MT_GOOGLE_KEY = 'xxxxx'

MACHINE_TRANSLATION_SERVICES = (
'weblate.trans.machine.google.GoogleTranslation',
'weblate.trans.machine.weblatetm.WeblateSimilarTranslation',
'weblate.trans.machine.weblatetm.WeblateTranslation',
)
```

Please help

**Comment by nijel** [comment]
That should be enough. What Weblate version is that?

**Comment by desmax** [comment]
@nijel latest master

**Comment by desmax** [comment]
I expect to see new tab here, right?
<img width="1280" alt="screen shot 2016-06-29 at 21 14 50" src="https://cloud.githubusercontent.com/assets/656393/16463464/a2c152d0-3e3e-11e6-8e21-ed252ca633a4.png">

**Comment by nijel** [comment]
No, on the translation page: 
![weblate_master_-_czech_ _hosted_weblate_-_2016-06-29_20 16 40](https://cloud.githubusercontent.com/assets/212189/16463504/695f0a9e-3e36-11e6-9bd4-f5b056cb348d.png)

**Comment by desmax** [comment]
@nijel ok, but can't see it there either..
<img width="1053" alt="screen shot 2016-06-29 at 21 26 43" src="https://cloud.githubusercontent.com/assets/656393/16463837/3cd98454-3e40-11e6-9d6f-506bcc2ebaa7.png">

**Comment by nijel** [comment]
Are you sure you're using Weblate as admin? It doesn't seem from lacking privilege for suggesting. There is permission for machine translations as well, which you might also lack (by default it's enabled for authenticated users only).

**Comment by desmax** [comment]
Yes, sure. Privilege for suggestions is not there because suggestions are disabled for that particular component

**Comment by desmax** [comment]
Ehm, today its there. Not sure why.
