### ISSUE TITLE
Encoding problem with first msgid in po file is getting worse after every file saving

### ISSUE THREAD

**Issue by ihoru** [nijel/weblate#1169]
### Steps to reproduce
After every editing of the po file the first msgid becomes more and more uglier!

![2016-07-06_20 07 08](https://cloud.githubusercontent.com/assets/361908/16627502/9e26d85a-43be-11e6-84b7-4d65607c8155.png)
![2016-07-06_20 06 59](https://cloud.githubusercontent.com/assets/361908/16627504/a0d38bca-43be-11e6-8219-e29ec93832e2.png)

### Server configuration
```
$ ./manage.py list_versions
 * Weblate weblate-2.6
 * Python 2.7.11+
 * Django 1.9.5
 * six 1.10.0
 * python-social-auth 0.2.18
 * Translate Toolkit 1.14.0-rc1
 * Whoosh 2.7.4
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.6.0
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * djangorestframework 3.3.3
 * pytz 2016.4
 * pyuca N/A
 * pyLibravatar N/A
 * Database backends: django.db.backends.mysql

$ pip freeze | egrep -i 'pyLibravatar|pyuca'
pyLibravatar==1.7
pyuca==1.1
```

**Comment by nijel** [comment]
That's [bug in translate-toolkit](https://github.com/translate/translate/issues/3450), which I've already fixed there: https://github.com/translate/translate/pull/3455

Either apply that fix on your copy or checkout current translate-toolkit to fix this.
