### ISSUE TITLE
SVN support has 'trunk' hardcoded

### ISSUE THREAD

**Issue by roidelapluie** [nijel/weblate#1175]
Hi,

Thanks for merging and improving svn version.

I am however worried to see trunk several times. Trunk refers to the 'master' branch in git. It probably means that the code does not work with a different branch.

**Comment by nijel** [comment]
No it currently does not, but patches are welcome to fix that :-).

**Comment by roidelapluie** [comment]
I will as its my primary usecase... :)

**Comment by nijel** [comment]
Merged #1176
