### ISSUE TITLE
Allow exact search for a single letter

### ISSUE THREAD

**Issue by dg0yt** [nijel/weblate#1179]
### Steps to reproduce
1. Open search
2. Enter a single letter as query, and select "exact match" as search type
3. Click "Search"

### Actual behaviour
There is an error message: "Error in parameter q: Ensure this value has at least 2 characters (it has 1)." The result browser has all strings.

### Expected behaviour
The exact match should accept single letters, and return the actual result.

Single letter translations are useful for units of measurement ("m") and for shortcut keys ("X"). For cleanup and corrections, it would be helpful if they could be searched.

BTW, users might be unable to recognize that "parameter q" refers to the "Query" field.

**Comment by nijel** [comment]
The limit was there for performance reasons, but indeed it's probably okay to enabled it at least for exact match....
