### ISSUE TITLE
[Android strings.xml] Weblate adds XML namespace in the wrong place, causing Gradle build to fail

### ISSUE THREAD

**Issue by vickychijwani** [nijel/weblate#1181]
### Steps to reproduce

1. Create an Android project with a `tools:ignore` attribute on a string, like [this](https://github.com/vickychijwani/quill/blob/master/app/src/main/res/values/strings.xml#L34). Example:

  ```xml
  <resources xmlns:tools="http://schemas.android.com/tools">
      <string name="string1" tools:ignore="PluralsCandidate">string1</string>
      <string name="string2">string2</string>
  </resources>
  ```

2. Translate the string via Weblate
3. Try to build the project with the translated strings file

### Actual behaviour

Weblate moves the `xmlns:tools="http://schemas.android.com/tools"` part to the string that uses the `tools` namespace, instead of attaching it to the root element `<resources>`.
```xml
<resources>
      <string xmlns:tools="http://schemas.android.com/tools" name="string1" tools:ignore="PluralsCandidate">string1</string>
      <string name="string2">string2</string>
</resources>
```

This causes Gradle build to fail with this error:
```
Building 71% > :app:processDebugResources/home/.../values-ja.xml:2: AAPT: Error parsing XML: prefix must not be bound to one of the reserved namespace names
```

You can see a real failure of this sort here (Ctrl + F for "Error parsing XML"): https://circleci.com/gh/vickychijwani/quill/106

### Expected behaviour

The attribute `xmlns:tools="http://schemas.android.com/tools"` should be on the root `<resources>` element, not on the individual string.

### Server configuration

N/A (using Hosted Weblate)

**Comment by nijel** [comment]
This seems to happen only when adding string which was not originally present in the resource and has the namespace which is not present in the resource.

**Comment by vickychijwani** [comment]
Yes that seems likely. The [commit which failed](https://github.com/vickychijwani/quill/commit/4f3e80863804f2209e50e48f344ae8ae580760f1) was similarly created. However, note that the previous commit with the empty strings.xml was also created by Weblate, so I'm guessing this will happen every time a new language translation is introduced via Weblate.

**Comment by nijel** [comment]
Created pull request on translate-toolkit which fixes this: https://github.com/translate/translate/pull/3468
