### ISSUE TITLE
No context headline when browsing "all" changes

### ISSUE THREAD

**Issue by dg0yt** [nijel/weblate#1184]
### Steps to reproduce
1. Open some project overview. The headline shows the project name.
2. Select "History". The headline still shows the project name.
3. Click button "Browse all project changes" (at page bottom).

### Actual behaviour
The head of the browser page shows only the headline "Changes" which is a link to a browser for changes in **all** projects. The web browser's back button is the only way back to the current project's overview. This is inconvenient especially after browsing forward some pages.

### Expected behaviour
The head of the browser page shall show the headline with the project name like before, as a link. The headline will indicate the context, and the link allows to navigate back to the **current** project's overview from any page in the changes browser.

### Server configuration
hosted.weblate.org

### Variants
For the history of a particular component ("Browse all component changes") or translation ("Browse all translation changes"), there is the same problem.

**Comment by dg0yt** [comment]
The headline now properly shows "Changes in PROJECT[/COMPONENT [- LANGUAGE]]", but the link always points to https://hosted.weblate.org/changes/, i.e. there it doesn't provide the expected navigation.

Example: https://hosted.weblate.org/changes/?project=openorienteering

PS: Just returned from Cesky Raj ;-)

**Comment by nijel** [comment]
True, it's missing there.

**Comment by dg0yt** [comment]
I am sorry, please reopen, prosím.

**[Current behaviour](https://hosted.weblate.org/changes/?page=4&project=openorienteering)**
The headline links to the *first changes page*. This has no extra value over the first browsing button below the headline ( |< ).

**Expected behaviour**
The headline links to the current project's / component's / translation *overview*. There is no other navigation link for this step. Ideally, the headline would look similar to the [translation browser](https://hosted.weblate.org/translate/openorienteering/mapper/cs/?type=nottranslated) i.e.

   [Project](https://hosted.weblate.org/projects/openorienteering/) /  [ [Component](https://hosted.weblate.org/projects/openorienteering/mapper/) / [ [Translation](https://hosted.weblate.org/projects/openorienteering/mapper/cs/) / ]] Changes

with Project, Component, Translation linking to the corresponding overview.

It is really needed. I regularly try to review changes this way, and I am annoyed by the lack of direct navigation from the e.g. page 5 to the overview.
