### ISSUE TITLE
Can't choose Friulian (fur) as Translated language in my dashboard

### ISSUE THREAD

**Issue by klenje** [nijel/weblate#1185]
### Steps to reproduce
1. Go to user profile
2. Languages
3. Translated languages

### Actual behaviour
Friulian not visible

### Expected behaviour
I expect to be able to choose Friulian (ISO code: fur). I've checked the source code and it seems to be there, feel free to point any missing stuff and I can provide a PR ;)

Thanks!

**Comment by nijel** [comment]
The dialog allows to choose only existing translations, so if there is nothing to translate into Friulian, it will not present this option....

**Comment by klenje** [comment]
Thanks for the answer. So should I just request to add Friulian for at least one project and then I will see Friulian in the list? 
Sorry for the dumb question, but I didn't find much in the docs about this use case

**Comment by nijel** [comment]
Yes, the translation has to first exist in Weblate, so ask project where you want to translate to add it (or add it directly Weblate if that is supported and enabled for that project).
