### ISSUE TITLE
Error on access to user profile

### ISSUE THREAD

**Issue by webs86** [nijel/weblate#1186]
### Steps to reproduce
1. Login to Weblate
2. Access to user profile
3. I'm get this error:
`TypeError at /accounts/profile/
render_options() takes exactly 3 arguments (2 given)`

### Actual behaviour
Weblate return 
`TypeError at /accounts/profile/
render_options() takes exactly 3 arguments (2 given)`

### Expected behaviour
I should see the user's profile

### Server configuration
 * Weblate weblate-2.7-188-gcc06fc6
 * Python 2.7.9
 * Django 1.10
 * six 1.10.0
 * python-social-auth 0.2.19
 * Translate Toolkit 2.0.0b3
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.6.1
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * djangorestframework 3.4.3
 * git-svn 2.1.4
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Indeed the code is not compatible with Django 1.10.

This should be fixed and added testcase to cover this situation, so that it's visible from automated tests next time.
