### ISSUE TITLE
[proposed question] Manual commit

### ISSUE THREAD

**Issue by uolter** [nijel/weblate#1191]
### Manual Commit only

I would like to disable automatic commit to reduce the number of them.
- I am already using a weblate to translate a django application, but po files are created with a post update script straight on the weblate box. This reduces a lot numbers of conflicts, but increased the number of commits since it happens very often that the only change in po files is in the "POT-Creation-Date" header.
- It would be acceptable for us to run manual commits.

Is it possible to configure weblate to allow only manual commit?

Any drawback in doing that? Any better change to avoid commit where only the po file header has small changes?

Thanks a lot.
Uolter

**Comment by nijel** [comment]
Weblate does by default commit only when needed, see [documentation](https://docs.weblate.org/en/latest/admin/continuous.html#lazy-commits). There is not much room to reduce (besides grouping commits from same author done on different files or not consequentially, see #1157 and #126).

If you often regenerate po files to avoid merge conflict, you might better try to update only when needed and pull changes from Weblate before doing that to avoid merge conflicts, there is [sample script in our docs to do that](https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts).

**Comment by uolter** [comment]
Thanks a lot. 
So far I don't have anymore issue with conflicts, what I would like to avoid is to commit files where only the header changes. 
My po file are generated automatically with a script running in weblate post event: basically I do not commit them manually so I don't what exactly changes

**Comment by nijel** [comment]
But the header changes are caused by the script, not by Weblate...

**Comment by uolter** [comment]
Yes, sure. Thank you. I've perfectly get the point. 

Cheers,
Walter
