### ISSUE TITLE
Gravatar not showing

### ISSUE THREAD

**Issue by HaaiHenkie** [nijel/weblate#1192]
### Steps to reproduce
1. I work as a translator on https://hosted.weblate.org/projects/freeplane/
2. I added a gravatar for the e-mail address I use on this site: h.n.van.den.akker+freeplane@gmail.com
3. I waited a day

### Actual behaviour
The gravatar is not shown, only a random chosen avatar.

### Expected behaviour
The gravatar shows. According to the manual you can use gravatar: http://docs.weblate.org/en/latest/user/profile.html#avatar

### Server configuration
I have no access to the server

**Comment by nijel** [comment]
There is currently 7 days cache for avatars on Hosted Weblate, what is clearly not working well in such case. It's probably time to decrease cache timeout to something more reasonable...

**Comment by nijel** [comment]
Should be fixed now. There were actually two levels of caching without good reason....
