### ISSUE TITLE
python-social-auth 0.2.20 compatibility: `Dependency on unknown app: default` with migrations

### ISSUE THREAD

**Issue by nikonikoniko** [nijel/weblate#1193]
### Steps to reproduce
1. Install weblate with the current requirements.txt
2. try to run migrations
3. see this error: `ValueError: Dependency on unknown app: default`

python-social-auth seems to have changed the app name to `social_auth` instead of `default` in version `0.2.20`, which will mean rewriting a lot of the migrations in weblate/accounts app.

reverting python-social-auth to version `0.2.19` worked for me.

**Comment by nijel** [comment]
This should be fixed in next python-social-auth release, see https://github.com/omab/python-social-auth/issues/991 and https://github.com/clintonb/python-social-auth/commit/361f42235fe51f422af029f325d041407a16036c

**Comment by nijel** [comment]
Okay, it seems that this issue is really not fully fixed....

**Comment by nikonikoniko** [comment]
thanks! [party]
