### ISSUE TITLE
Failed to update lock, probably session has expired.

### ISSUE THREAD

**Issue by marcperrin** [nijel/weblate#1197]
Hello,
Been seeing this message "Failed to update lock, probably session has expired." a lot recently 
(easier to trigger in zen mode (but not limited to it); generally to reproduce I just go to zen mode and wait stg. like 15 seconds => got the message)
What's the best way I could investigate to find the reason behind this?
Thanks!

**Comment by nijel** [comment]
I've seen this as well, but didn't find time to dig deeper. Definitely worth investigating.
