### ISSUE TITLE
Repo IP change

### ISSUE THREAD

**Issue by Mikanoshi** [nijel/weblate#1209]
### Steps to reproduce
Tools - Push (or any action with repo), change component settings

### Actual behaviour
"Failed to fetch repository: ssh: connect to host 188.120.251.238 port 1022: Connection refused fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. error: Could not fetch origin (1)"

### Expected behaviour
Source and push fields contain ssh:// URL with a repo domain name. Host keys are added for both IP and domain. But IP above is incorrect, because repo was moved to another server days ago and got new IP.

### Server configuration
 * Weblate weblate-2.7-354-g57f4e0c
 * Python 2.7.12
 * Django 1.9.7
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0b4
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.9.2
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.6.4
 * django-crispy-forms 1.6.0
 * compressor 2.1
 * djangorestframework 3.4.6
 * pytz 2016.6.1
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * Mercurial 3.9
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
Then change the repository location in component settings...

**Comment by Mikanoshi** [comment]
Weblate settings are ok, problem was with ssh, I forgot to change hostname in ~/.ssh for git user.
