### ISSUE TITLE
No way to specify a default format in PO files?

### ISSUE THREAD

**Issue by Changaco** [nijel/weblate#1210]
Hi. In [Liberapay](https://github.com/liberapay/liberapay.com) our i18n functions use what gettext calls `python-brace-format`. Unfortunately Weblate doesn't know about it and thus cannot run the appropriate format check. (We use Babel to extract messages, and it doesn't have built-in support for the brace format yet: <https://github.com/python-babel/babel/issues/333>.)

Is there a way to tell Weblate that an entire PO file uses a specific default format? Something like a `Default-Format` header. Or is adding `#, python-brace-format` before every message the only solution?

**Comment by nijel** [comment]
It's currently only possible from admin interface. I've done the change for your project now, the checks are being recalculated.

However this really should be editable by project admins...
