### ISSUE TITLE
New Feature: possibility of having one branch per language in a project

### ISSUE THREAD

**Issue by emmapeel2** [nijel/weblate#1214]
Would it be hard to have branches per language?

With one project, being able to commit the different files to different git branches (Spanish, French, etc)

**Comment by nijel** [comment]
It would be quite hard, because it would need repository working copy for every language. I don't think this is something reasonable. What are you trying to achieve?

**Comment by emmapeel2** [comment]
I would like for the different language teams to be able to review their specific language.

**Comment by nijel** [comment]
That's pretty easy to do in git on file basis as well, I'm afraid that introducing so many branches would lead to quite some mess...

**Comment by emmapeel2** [comment]
OK... Thanks for the explanation!
