### ISSUE TITLE
Whiteboard message shows in all components despite having set component

### ISSUE THREAD

**Issue by paour** [nijel/weblate#1215]
### Steps to reproduce
1. In the admin interface, I created a single whiteboard message and set the component but not the language
2. I tried keeping the project to `---` but it was automatically set from the component and I couldn't remove it

![change_whiteboard_message___django_site_admin](https://cloud.githubusercontent.com/assets/90963/18195532/512dd138-70ec-11e6-9fa2-ff0306548979.png)

After save:
![select_whiteboard_message_to_change___django_site_admin]
(https://cloud.githubusercontent.com/assets/90963/18195535/5650fb4a-70ec-11e6-9555-817bbdbc13f0.png)

### Actual behaviour
The whiteboard message is displayed in all components, not just the one I selected.

### Expected behaviour
It should be displayed only on the component I selected.

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

 * Weblate weblate-2.7
 * Python 2.7.9
 * Django 1.9
 * six 1.10.0
 * python-social-auth 0.2.19
 * Translate Toolkit 2.0.0b4
 * Whoosh 2.7.4
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.6.4
 * django-crispy-forms 1.6.0
 * compressor 2.1
 * djangorestframework 3.4.6
 * pytz 2016.6.1
 * pyuca N/A
 * pyLibravatar N/A
 * Database backends: django.db.backends.mysql

**Comment by lomaster1** [comment]
Repeats in 2.17.1 - [new issue](https://github.com/WeblateOrg/weblate/issues/1677)
