### ISSUE TITLE
adding new subproject error

### ISSUE THREAD

**Issue by glensc** [nijel/weblate#1220]
I'm really new to this project and kickstarting first project + vcs seems very hard.

currently i'm stuck with subproject (`/admin/trans/subproject/add/`)

it gives me error:
`Format of base file for new translations was not recognized!`

i can not decipher it even after looking sourcecode of that error:
https://github.com/nijel/weblate/blob/weblate-2.8/weblate/trans/models/subproject.py#L1202-L1205

it doesn't even hilite which field has the invalid value

ps: it would probably ease setting up if basic (required) fields are asked first, and then optional fields can be modified/added from separate page.
##

**Comment by nijel** [comment]
What is wrong is 'Base file for new translations'.

**Comment by glensc** [comment]
and what is wrong with it? it is not clear
- i tried to leave field empty
- i tried to input `.pot` there (literally)

**Comment by glensc** [comment]
so, as it was not clear (to me) what to put there, seems it wanted existing file from project repository (and i mistyped it). the error message should be improved saying `no such file: xxx.pot found` or similar, not `format not recognized`

**Comment by nijel** [comment]
Indeed error reporting could be more precise here.

**Comment by nijel** [comment]
Error messages should be better since #1257 and #1238. Please try with just released 2.9 and report if there is still something to improve.

**Comment by nijel** [comment]
Closing as I think it's fixed by #1257 and #1238.
