### ISSUE TITLE
Profile -> Languages not intuitive

### ISSUE THREAD

**Issue by glensc** [nijel/weblate#1221]
on `/accounts/profile/#languages` page

there's `Translated languages` and `Secondary languages` multiple selects.

but there's no indication which of the columns is "selected ones"

also it's not clear how to add more languages to the "available languages" box (whichever it is) -- by default all 4 are empty!

**Comment by nijel** [comment]
It lists only actively used translations, so as long as there is nothing imported in Weblate, it's empty. The selected languages are shown in the right list:

![user_profile_ _weblate_demo_-_2016-09-06_16 04 40](https://cloud.githubusercontent.com/assets/212189/18276546/a20f6a64-744b-11e6-8d39-28a48624ed98.png)

**Comment by glensc** [comment]
the "Selected" vs "Available" is not intuitive. consider adding some label to each box. I noticed same UI flaw in other views as well.

**Comment by glensc** [comment]
thanks!
