### ISSUE TITLE
Upgrade from 2.4 to 2.8 fails

### ISSUE THREAD

**Issue by evfool** [nijel/weblate#1223]
### Steps to reproduce
1. Install weblate 2.4
2. Create a project with ACL's enabled
3. Try to upgrade to Weblate 2.8

### Actual behaviour
Migration fails in weblate/trans/migrations/0059_auto_20160303_0934.py
Cause is Group.DoesNotExist

### Expected behaviour
Migration should not fail. The workaround (and probably the fix) is adding a try..except  block for Group.DoesNotExist around the code in the migrate script if project.enable_acl block.

The steps to reproduce are only an assumption, the migration failed for me, and this seemed to be a reason, I have a fairly complex database setup. If you consider my DB to be the problem somehow getting in an inconsistent state, feel free to close this.

### Server configuration
 * Weblate 2.8
 * Python 2.7.12
 * Django 1.10.1
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0b5
 * Whoosh 2.5.7
 * defusedxml 0.4.1
 * Git 2.9.2
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.6.4
 * django-crispy-forms 1.6.0
 * compressor 2.1
 * djangorestframework 3.4.6
 * pytz 2016.6.1
 * pyuca N/A
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
AFAIK all releases have automatically created groups for ACL enabled project, so this was most likely caused by removal of given group manually. Anyway the migration indeed should not fail.

**Comment by evfool** [comment]
I don't remember removing any groups manually, but nevermind, with the migration fixed weblate is up and running again. Thanks for the fix.
