### ISSUE TITLE
inappropriate organisation of vcs directory

### ISSUE THREAD

**Issue by opensuse-i18n** [nijel/weblate#1226]
### Steps to reproduce
1. Have a project with many pot files. Example: https://github.com/yast/yast-translations
2. Create one project for it, add subprojects per on po directory
or
3. Create many projects, add single subproject for each of them

### Actual behaviour
However all projects use exactly the same git repository and the same branch, repository is checked out many times. After a push, it is synced across all instances using GitHub webhooks. It is both disk space ineffective and network ineffective.

### Expected behaviour
Check-out identical repositories only once.
Instead of vcs/&lt;project&gt;/&lt;component&gt; use vcs/&lt;repo&gt;/&lt;branch&gt;, or even two level pushing (clone and push branches locally to master bare git repo, and then from master bare git repo to remote).

### Server configuration
 * Weblate 2.6
 * Python 2.7.9
 * Django 1.8.4
 * six 1.9.0
 * python-social-auth 0.2.7
 * Translate Toolkit 1.14.0-rc1
 * Whoosh 2.7.0
 * Git 1.8.5.6
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.2.3
 * django-crispy-forms 1.5.2
 * compressor 1.5
 * djangorestframework 3.3.3
 * pytz 2013.9
 * pyuca N/A
 * Database backends: django.db.backends.mysql

**Comment by mvidner** [comment]
> Instead of vcs// use vcs//

It seems your point got lost in the formatting.

**Comment by stanislav-brabec** [comment]
> It seems your point got lost in the formatting.
Fixed.

**Comment by nijel** [comment]
I guess you are looking for [Weblate internal URLs](https://docs.weblate.org/en/latest/vcs.html#weblate-internal-urls).
