### ISSUE TITLE
Error in fresh install

### ISSUE THREAD

**Issue by royalterra** [nijel/weblate#1230]
### Steps to reproduce
1. I install all dependence according the Installation instructions
2.Simple I can start the installation I have always the seam error

### Actual behaviour
File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### Expected behaviour
Start setup 

### Server configuration
Command can be execute 
 File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by royalterra** [comment]
update

**Comment by nijel** [comment]
See #1077 - upgading python-social-auth should fix this.
