### ISSUE TITLE
Subversion autentication

### ISSUE THREAD

**Issue by webs86** [nijel/weblate#1231]
### Steps to reproduce
We have SVN repository for many projects. Any project have its directory within standard layout (eg: example.com/repository/project1/trunk, example.com/repository/project1/branches, example.com/repository/project1/tags). To access repository you must authenticate with user/password credentials via Basic Authentication.

1. Add new component with svn repository need authentication (I have used a URL in format http://user:password@example.com/repository/dir/)
2. Save component configuration
3. I have this error: 

`Failed to fetch repository: Authentication realm: <http://example.com:80> SVN Password for 'weblate': Authentication realm:  <http://example.com:80> SVN Username: Use of uninitialized value in concatenation (.) or string at /usr/share/perl/5.20.2/Git/SVN/Prompt.pm line 20. Password for '': Authentication realm:  <http://example.com:80> SVN Username: Use of uninitialized value in concatenation (.) or string at /usr/share/perl/5.20.2/Git/SVN/Prompt.pm line 20. Password for '': Authentication failed: Unable to connect to a repository at URL 'http://user:password@example.com/repository/dir': No more credentials or we tried too many times. Authentication failed at /usr/share/perl/5.20.2/Git/SVN.pm line 148. (1)`

I have this issue always, also with previous versions of weblate.

### Server configuration
* Weblate weblate-2.8-89-ge25c878
 * Python 2.7.9
 * Django 1.10
 * six 1.10.0
 * python-social-auth 0.2.19
 * Translate Toolkit 2.0.0b3
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.10.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.6.1
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * djangorestframework 3.4.3
 * git-svn 2.10.0
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/vcs.html#credentials

**Comment by webs86** [comment]
Hi @nijel, thanks for your reply.
I have tried with:

`HOME=<path to data dir> svn co http://svn.example.com/project/trunk`

but when add component I get the same error. Also our repository is not in HTTPS.

**Comment by nijel** [comment]
Okay, the docs was wrong here, it should be:

```
HOME=<path to data dir>/home svn co http://svn.example.com/project/trunk
```
