### ISSUE TITLE
ugly GUI: project list generated long scroller on large sites

### ISSUE THREAD

**Issue by stanislav-brabec** [nijel/weblate#1235]
If a site hosts many projects, the drop down list is a long and very ugly scroller.

### Steps to reproduce
1. Go to https://l10n.opensuse.org/
2. Click to Projects

### Actual behaviour
4 screens long drop down menu

### Expected behaviour
better looking menu

### Server configuration
Weblate 2.6
Python 2.7.9
Django 1.8.4
six 1.9.0
python-social-auth 0.2.7
Translate Toolkit 1.14.0-rc1
Whoosh 2.7.0
Git 1.8.5.6
Pillow (PIL) 1.1.7
dateutil 2.4.2
lxml 3.2.3
django-crispy-forms 1.5.2
compressor 1.5
djangorestframework 3.3.3
pytz 2013.9
pyuca N/A
Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
Hmm, probably it's not really needed. Maybe it would be good enough to list users subscriptions there.
