### ISSUE TITLE
Bitbucket URL login changed

### ISSUE THREAD

**Issue by blackspotent** [nijel/weblate#1236]
Hi, I've been using Weblate v2.3 for sometime. Recently, Bitbucket changed their login with using email address. 

This prevent me using weblate as login url has ilegal address, for example, Source Code Repository in setting subproject, it will look like

https://foo@nobody.com:foobar@bitbucket.org/myteam/translation.git

How should I change the url so that it's recognized by weblate as proper url?

Thank you very much.

Cheers!
##

**Comment by nijel** [comment]
What kind of error do you get?

**Comment by nijel** [comment]
There is no validation on Weblate side, I've just tested that such repository works fine.

**Comment by nijel** [comment]
PS: In order to make these URLs work with Git, the both username and password has to be url encoded, for example:
```
 https://user%40example.com:%24password%23@bitbucket.org/...
``
