### ISSUE TITLE
Limit languages per user

### ISSUE THREAD

**Issue by efdee** [nijel/weblate#1237]
It might be interesting to have the ability to (as an administrator) limit the languages in which a user is allowed to edit translations. This is currently available as an option to the user himself (through his preferences screen) but we would like to enforce it on a higher level.

I don't think this is currently possible?

**Comment by nijel** [comment]
This is possible using group ACLs, see https://docs.weblate.org/en/latest/admin/access.html#group-based-access-control.

PS: I have no personal experience with that.
