### ISSUE TITLE
Files mask .po issues

### ISSUE THREAD

**Issue by royalterra** [nijel/weblate#1238]
Can any help me here Thanks in advance 

### Steps to reproduce
1. Setup Component 
2.add git https://github.com/BlaBlaNet/Translations
3. Setup mask BlaBla.hmessagespo/*.po

### Actual behaviour
The mask did not match any files!

### Expected behaviour
Add all the files front that folder

### Server configuration
Please paste the output of command `./manage.py list_versions` over here
 * Weblate weblate-2.8-103-gef67710
 * Python 2.7.9
 * Django 1.10.1
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0b5
 * Whoosh 2.5.7
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.2
 * lxml 3.4.0
 * django-crispy-forms 1.6.0
 * compressor 2.1
 * djangorestframework 3.4.6
 * pytz 2016.6.1
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * Mercurial 3.1.2
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
Hmm, it works fine for me. Are you sure you didn't mistype the mask (eg. wrong uppercase or additional space)?

**Comment by royalterra** [comment]
Hmm I try with a version using bitnamy and owith one normal install in the server . I select Gettex Po files and both Installations say Format of base file for new translations was not recognized!

**Comment by nijel** [comment]
Indeed the error message is confusing in this case - the problem is that you have selected (or rather kept default) choice to let Weblate add new translations without providing it base file to do so.
