### ISSUE TITLE
incorrect information in the "engage" page

### ISSUE THREAD

**Issue by stanislav-brabec** [nijel/weblate#1239]
If the translation of a particular project does not exist, but the translation is valid, the engage page reports 100% instead of 0%.
The information in the "engage" page falsely declares 100%.

### Steps to reproduce
1. Go to https://l10n.opensuse.org/engage/skelcd-opensuse/tr/
2. Go to https://l10n.opensuse.org/projects/skelcd-opensuse/master/

### Actual behaviour
1. declares 100% Turkish translation
2. shows that no Turkish translation exist.

### Expected behaviour
1. Should show 0% or not existing translation.

### Server configuration
Weblate 2.6
Python 2.7.9
Django 1.8.4
six 1.9.0
python-social-auth 0.2.7
Translate Toolkit 1.14.0-rc1
Whoosh 2.7.0
Git 1.8.5.6
Pillow (PIL) 1.1.7
dateutil 2.4.2
lxml 3.2.3
django-crispy-forms 1.5.2
compressor 1.5
djangorestframework 3.3.3
pytz 2013.9
pyuca N/A
Database backends: django.db.backends.mysql

**Comment by lnussel** [comment]
I tried to create an overview page so I can see the status of the important translations. This bug spoils that approach: https://en.opensuse.org/openSUSE:Localization_status
