### ISSUE TITLE
Two Indonesian languages

### ISSUE THREAD

**Issue by jayvdb** [nijel/weblate#1240]
### Steps to reproduce
1. Go to user profile at https://hosted.weblate.org/accounts/profile/
2. Scroll down "Translated languages" to "Indonesian"
3. Select both Indonesians to make them Translated languages
4. Save

### Actual behaviour
There are two indistinguishable "Indonesian" entries

### Expected behaviour
There should only be one Indonesian, or they should be somehow distinguishable

### Server configuration
https://hosted.weblate.org/accounts/profile/

**Comment by nijel** [comment]
This has been fixed in code by 60f56791, but the duplicate language was not yet removed on Hosted Weblate. Fixed now.

**Comment by jayvdb** [comment]
Thank you. Looks good now.

**Comment by jayvdb** [comment]
There are also a bunch of projects using the wrong code at https://l10n.opensuse.org/languages/in/ .  Is there an easy way to fix that?

**Comment by nijel** [comment]
I don't think there is anything better than reporting to them :-). Recent Weblate versions will map the language codes in case the language does not exist.

**Comment by jayvdb** [comment]
Report against six repos?
Or, do you happen to know who is an admin/committer across their weblate repos who might be able to help fix it?

**Comment by nijel** [comment]
Try asking @stanislav-brabec who maintains Weblate instance at openSUSE :-).

**Comment by stanislav-brabec** [comment]
nijel: Already in progress: https://progress.opensuse.org/issues/14280
