### ISSUE TITLE
State of weblate.db vs. po files

### ISSUE THREAD

**Issue by marcperrin** [nijel/weblate#1249]
Hello,

I've got a weird situation:

Some translation units have (intentionally) disappeared from po files; 
Weblate's repository (data/vcs) is (after the pull) nice and up-to-date, but for some languages, the django db still has those disappeared translation units. 
Those languages don't show "Resource update" in their recent history, as opposed to those who look correct.
So it looks like a kind of merge problem (?) when the db has been refreshed with respect to new repository files... how can I diagnose / fix this issue? Is there a command I can run to try and re-refresh db from files? 
Can you point me to some functions in the code that do this operation? I think check_sync but...

Maybe I can try to make some dummy changes in a .po file, do a new pull and check if it automatically gets fixed...

Thanks!

**Comment by marcperrin** [comment]
OK, making a dummy change (in po headers) and re-doing a pull solves the issue.
I'm not sure I have a way to find out what went wrong in the first place (there were HTTP error 500 on wlc pull (and lock, unlock) but I'm not sure I've got logs anywhere about those errors).

**Comment by nijel** [comment]
Most likely the update did silently fail in the background. This has been already discussed in  #1233 and it should at least end up with user visible error.
