### ISSUE TITLE
Feature: Hide translated components from the 'my translations' menu list

### ISSUE THREAD

**Issue by emmapeel2** [nijel/weblate#1251]
### Steps to reproduce
1. Select 'hide translated components from Dashboard'
2. Hover over the list of My translations
3. The already finished translations keep appearing
### Expected behaviour

It would be great if they also dissapear from the 'My translations' list.
##

**Comment by harikv** [comment]
@nijel Can I take this on instead? Any pointers?

**Comment by nijel** [comment]
Hmm, reading again the report, I somehow don't know where it should be fixed. @emmapeel2 can you please clarify?

**Comment by emmapeel2** [comment]
Here:

![screenshot from 2016-10-23 18 35 31](https://cloud.githubusercontent.com/assets/11485015/19628566/31b0ef48-9950-11e6-95ab-7835084130fe.png)

**Comment by nijel** [comment]
Okay, this was changed to list subscribed *projects* in 07862201, so I don't think the filtering makes sense here...

**Comment by nijel** [comment]
Closing as this menu is no longer there since 2.8.
