### ISSUE TITLE
github oauth fails with a 404

### ISSUE THREAD

**Issue by working-name** [nijel/weblate#1256]
### Steps to reproduce
1. deploy weblate from github
2. run behind apache, wsgi
3. load up the page, and try to login using github in an incognito browser. You'll be able to log in but upon redirect github.com's 404 page shows up.

### Actual behaviour
tries to load this: `https://github.com/login/oauth/authorize?scope=user:email&state=otaXFx65aSRIasr6sXyuXrbY0JMMkbDV&redirect_uri=https://domain.name/accounts/complete/github/?redirect_state=otaXFx65aSRIasr6sXyuXrbY0JMMkbDV&response_type=code&client_id=` but bumps into a 404 error

### Expected behaviour
python-social-auth should have properly completed the task

### Server configuration
```
 * Weblate weblate-2.8-175-gb38b896
 * Python 2.7.9
 * Django 1.10.2
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0b6
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.6.4
 * django-crispy-forms 1.6.0
 * compressor 2.1
 * djangorestframework 3.4.7
 * pyuca N/A
 * pyLibravatar N/A
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
The URL works fine if you provide correct credentials, are you sure your SOCIAL_AUTH_GITHUB_KEY and SOCIAL_AUTH_GITHUB_SECRET are correctly set?

**Comment by working-name** [comment]
You're right, that was it. So sorry about that, I thought I had copied `settings.py` from the previous deployment.
