### ISSUE TITLE
"Add Component" View shows misleading error message

### ISSUE THREAD

**Issue by AWessel77** [nijel/weblate#1257]
### Steps to reproduce
1. In the Django Administration navigate to the components overview
2. Click 'Add component'
3. Fill out the required fields.
4. Chose 'Simple csv' as file format 
5. Chose 'Automatically add language file' for 'New translation'
6. Click the save button

### Actual behaviour
Following error message comes up 'Chosen file format does not support adding new translations as chosen in project settings.'. This was misleading for me as I thought I would have to change something in the project settings. Also I had some difficulties to puzzle out that the input 'New translation' was the one to change.

### Expected behaviour
Display of error message that is more clear and directs me to the misconfiguration. Maybe some higlighting of the input field would help. Obviously this is difficult as it is the mismatching of two inputs that leads to this error.

### Server configuration
* Weblate weblate-2.8-168-gec95259
 * Python 2.7.12
 * Django 1.10.1
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0b5
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.6.4
 * django-crispy-forms 1.6.0
 * compressor 2.1
 * djangorestframework 3.4.6
 * pytz 2016.6.1
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * Mercurial 3.9.1
 * Database backends: django.db.backends.mysql
![shotweblatefalsecomponentconfigerror](https://cloud.githubusercontent.com/assets/10668162/19561072/6bb5b76c-96d7-11e6-8987-af82e54538bc.png)

**Comment by nijel** [comment]
It seems that since Django 1.7 it's possible to assign error to more fields in the validation, will adjust code to that.

**Comment by AWessel77** [comment]
Thanks for the quick reaction. 👍
