### ISSUE TITLE
Warn users & project owners against starting translations to deprecated codes

### ISSUE THREAD

**Issue by Artoria2e5** [nijel/weblate#1258]
There are a few language codes that, in general, should be avoided. This includes old Norwegian (`no`) and "Chinese" without script/region specifiers (`zh`). Under certain conditions, there are a few more language codes to avoid:
* "Chinese simplified" (`zh_Hans`) when a `zh_CN` translation exists. The opposite should apply as long as nobody is translating for `zh_SG`.
* "Chinese traditional" (`zh_Hant`) when either `zh_TW` or `zh_HK` exists.
* "Chinese simplified" (`zh_Hans`) and "Chinese traditional" (`zh_Hant`) in general as script-based division for Chinese is not a good idea. `Hant` is especially problematic as two major variants are written in that script.
* "English (United States)" when the source itself is in English. Only applies to users.

With that in mind, some warnings should be given to users when they try to use these deprecated language codes. `zh` is an especially great headache for me -- I always have to view the strings to figure out which script a translation is in. 

### Steps to reproduce
1. Open a project page, say, https://hosted.weblate.org/projects/wincompose/master/
2. Try to create a deprecated language. I tried with old Norwegian, so please delete that afterwards...

### Actual behaviour
Translation successfully created without warnings.

### Expected behaviour
Weblate should tell me that I am doing something silly.

### Server configuration
Hosted.

**Comment by Artoria2e5** [comment]
Seriously, [QT4-fsarchiver/master](https://hosted.weblate.org/projects/qt4-fsarchiver/master/)?

![image](https://cloud.githubusercontent.com/assets/6459309/19621738/56ef5c80-9866-11e6-8b6b-11a17757560c.png)

**Comment by nijel** [comment]
Duplicate https://github.com/nijel/weblate/issues/1172
