### ISSUE TITLE
Multi language status widget: Make the language labels and bars a link to the translation

### ISSUE THREAD

**Issue by dg0yt** [nijel/weblate#1265]
### Actual behaviour

The widget is just a static image ([example](https://hosted.weblate.org/widgets/openorienteering/)). It can be linked only to a single target, by means of HTML.
### Expected behaviour

The languages' labels and bars link to their actual translations, by means of SVG. Potential contributors could easily get to the translations of the language they know. This would allow the widget to replace individual lists of languages ([example without bars](https://github.com/OpenOrienteering/mapper/wiki/Translation##translation-issues)).
### Server configuration

Hosted.
### Remark

Follow-up from #1109.
##

**Comment by nijel** [comment]
To make this really useful, we first need per language overview within project (see https://github.com/nijel/weblate/issues/1093).
