### ISSUE TITLE
rare git race causing conflicts

### ISSUE THREAD

**Issue by stanislav-brabec** [nijel/weblate#1266]
I just experienced a conflict in the commit attempt. The conflict seems to happened before commit. I guess that while Weblate was preparing a commit, GitHub hook called pull/fetch (that probably failed). As a result, commit failed, and all subsequent commit faled as well.

Note that it happened on a repository that has many linked projects, and this type of conflict happened for a very first time. Files in the repository have '<<<' marks.

It should be either documented how to fix it (https://docs.weblate.org/en/weblate-2.6/faq.html#merge does not work), or it should be prevented.

### Steps to reproduce
1. Not reproducible.

### Actual behaviour

 Hi,

There has been a merge failure on yast-base/master at openSUSE Weblate.

Error message

Auto-merging po/base/id.po
CONFLICT (content): Merge conflict in po/base/id.po
Automatic merge failed; fix conflicts and then commit the result. (1)

Repository status

On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 4 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

You have unmerged paths.
  (fix conflicts and run "git commit")

Changes to be committed:

	modified:   po/add-on/ar.po
	modified:   po/base/fa.po
	modified:   po/gtk/de.po
	modified:   po/gtk/id.po
	modified:   po/kdump/af.po
	modified:   po/kdump/am.po
	modified:   po/kdump/ar.po
	modified:   po/kdump/ast.po
	modified:   po/kdump/be.po
	modified:   po/kdump/bg.po
	modified:   po/kdump/bn.po
	modified:   po/kdump/bs.po
	modified:   po/kdump/ca.po
	modified:   po/kdump/cs.po
	modified:   po/kdump/cy.po
	modified:   po/kdump/da.po
	modified:   po/kdump/de.po
	modified:   po/kdump/el.po
	modified:   po/kdump/en_GB.po
	modified:   po/kdump/en_US.po
	modified:   po/kdump/eo.po
	modified:   po/kdump/es.po
	modified:   po/kdump/et.po
	modified:   po/kdump/eu.po
	modified:   po/kdump/fa.po
	modified:   po/kdump/fi.po
	modified:   po/kdump/fr.po
	modified:   po/kdump/gl.po
	modified:   po/kdump/gu.po
	modified:   po/kdump/he.po
	modified:   po/kdump/hi.po
	modified:   po/kdump/hr.po
	modified:   po/kdump/hu.po
	modified:   po/kdump/id.po
	modified:   po/kdump/it.po
	modified:   po/kdump/ja.po
	modified:   po/kdump/jv.po
	modified:   po/kdump/ka.po
	modified:   po/kdump/kdump.pot
	modified:   po/kdump/km.po
	modified:   po/kdump/kn.po
	modified:   po/kdump/ko.po
	modified:   po/kdump/ku.po
	modified:   po/kdump/lo.po
	modified:   po/kdump/lt.po
	modified:   po/kdump/lv.po
	modified:   po/kdump/mk.po
	modified:   po/kdump/mr.po
	modified:   po/kdump/ms.po
	modified:   po/kdump/my.po
	modified:   po/kdump/nb.po
	modified:   po/kdump/nds.po
	modified:   po/kdump/ne.po
	modified:   po/kdump/nl.po
	modified:   po/kdump/nn.po
	modified:   po/kdump/pa.po
	modified:   po/kdump/pl.po
	modified:   po/kdump/ps.po
	modified:   po/kdump/pt.po
	modified:   po/kdump/pt_BR.po
	modified:   po/kdump/ro.po
	modified:   po/kdump/ru.po
	modified:   po/kdump/si.po
	modified:   po/kdump/sk.po
	modified:   po/kdump/sl.po
	modified:   po/kdump/sq.po
	modified:   po/kdump/sr.po
	modified:   po/kdump/sr@Latn.po
	modified:   po/kdump/sv.po
	modified:   po/kdump/sw.po
	modified:   po/kdump/ta.po
	modified:   po/kdump/tg.po
	modified:   po/kdump/th.po
	modified:   po/kdump/tk.po
	modified:   po/kdump/tr.po
	modified:   po/kdump/uk.po
	modified:   po/kdump/vi.po
	modified:   po/kdump/wa.po
	modified:   po/kdump/xh.po
	modified:   po/kdump/zh_CN.po
	modified:   po/kdump/zh_TW.po
	modified:   po/kdump/zu.po

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both modified:      po/base/id.po

### Expected behaviour
This should never happen.

### Server configuration
 * Weblate 2.6
 * Python 2.7.9
 * Django 1.8.4
 * six 1.9.0
 * python-social-auth 0.2.7
 * Translate Toolkit 1.14.0-rc1
 * Whoosh 2.7.0
 * Git 1.8.5.6
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.2.3
 * django-crispy-forms 1.5.2
 * compressor 1.5
 * djangorestframework 3.3.3
 * pytz 2013.9
 * pyuca N/A
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
There should be filesystem level lock held when manipulating with the repository to prevent this, maybe it was omitted in some operations...

**Comment by nijel** [comment]
I couldn't find anything obviously wrong in the locking which could lead to this. I've found one minor race condition which can lead to losing translations done while merge is in progress (or rather between commit and merge, what is really tiny window).

Maybe this is something what was fixed since 2.6 you're using, I really didn't dig into code from that time...

**Comment by nijel** [comment]
I've rewritten the VCS integration that it would fail without held lock, that should make any remaining locking issues easier to discover. There was one locking missing in the translation removal, but that could not cause the problem for you as it's not present in your version.
