### ISSUE TITLE
Source node in XLIFF shows as context

### ISSUE THREAD

**Issue by eakkas** [nijel/weblate#1267]
### Steps to reproduce
1. Create a new project with XLIFF source/target
2.
3.

### Actual behaviour
Content from the source node appears in context

If I use the "Monolingual base language file" option, the source node's content seem to go to the Context field instead of the Source. Is this expected?
![2016-11-01_22-07-23](https://cloud.githubusercontent.com/assets/2618752/19917338/a52357aa-a07f-11e6-92a0-454fc484f71b.png)

[en.txt](https://github.com/nijel/weblate/files/565705/en.txt)

What is the proper config for XLIFF? If I leave the "Monolingual base language file" empty, am I expected to update the XLIFF files outside of Weblate when there is a change to the English source (ie an iOS project where you export xliff from xcode?). 

### Server configuration
Weblate 2.8

**Comment by nijel** [comment]
It really depends on your setup, whether it's monolingual (one file contains only one language and message IDs) or bilingual (one file contains both source and translated string). With bilingual files, you are expected to update the source strings.

**Comment by eakkas** [comment]
Thanks for the quick response. Which tool do you recommend for updating the source in bilingual format? I have been using okapi but it doesn't retain that line breaks which is problematic. 

And what do you think is incorrect with the xliff that I attached that causes my source string to appear as context? 

Thanks again

**Comment by nijel** [comment]
Sorry, I don't have much experience with XLIFF to help with updating it.

The file looks correct, it's bilingual, so don't use monolingual base file at all.
