### ISSUE TITLE
weird api root url

### ISSUE THREAD

**Issue by glensc** [nijel/weblate#1275]
### Steps to reproduce
1. setup weblate 2.9 to run with docker
2. go to http://localhost/accounts/profile/#api

### Actual behaviour

> API root URL:	http://http://localhost//api/

### Expected behaviour

> API root URL:	http://localhost/api/

**Comment by nijel** [comment]
Set correct [site name](https://docs.weblate.org/en/latest/admin/install.html#set-correct-site-name) (it should be just localhost in this case).

**Comment by glensc** [comment]
thanks! i assumed it takes value from docker env, did not even remembered i had setup some "sites" option.

still evaluating weblate to migrate from pootle 2.1.6 :)
