### ISSUE TITLE
YAML files are not parsed

### ISSUE THREAD

**Issue by tadejstanic** [nijel/weblate#1278]
### Steps to reproduce

Here is a screenshot from the admin panel to show steps to reproduce the issue.

![yaml-error](https://cloud.githubusercontent.com/assets/7260332/20170882/5fafd328-a72e-11e6-99c4-72cc9f411f10.png)

In the  Webplate container (I'm using Weblate Docker image) I've checked what version of translation-toolkit am I using and got the latest one. 

```
weblate@549a7ccd02af:/$ prop2po --version
prop2po 2.0.0b7
```
I did notice this in the docs: 

> You currently need patched version of translate-toolkit to support YAML. Check translate-toolkit issue tracker for more details.

but I think this instruction is somehow obsolete regarding that I'm using the latest version of the toolkit. Or am I missing something...

### Actual behaviour
See the error in the screenshot above.

### Expected behaviour
Weblate should recognise YAML files and parse them in the provided directory.

### Server configuration
 * Weblate 2.9
 * Python 2.7.9
 * Django 1.10.3
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0b7
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.2
 * lxml 3.4.0
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * pytz 2016.7
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.9.1
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Is YAML shown as option in file formats? If not, then it's not supported on your system. Maybe PyYAML library in not installed?

**Comment by tadejstanic** [comment]
I found that PyYAML library was not installed. I modified the Weblate Dockerfile to include the required package and now YAML files are ready to be parsed.

I've also made a PR here https://github.com/WeblateOrg/docker/pull/24
