### ISSUE TITLE
Weblate not pulling changes from GitHub when receiving notification

### ISSUE THREAD

**Issue by criezy** [nijel/weblate#1279]
Hello,

I followed the instruction at https://docs.weblate.org/en/latest/admin/continuous.html?highlight=updategit#automatically-receiving-changes-from-github to add the weblate service to my repository so that my test weblate installation gets notified when changes are pushed to GitHub. I would have expected Weblate to then automatically pull the changes on the server, but this is not happening.

The log on the server indicate that Weblate receives the notification. But then nothing happens:
`weblate[2084]: INFO received GitHub notification on repository https://github.com/criezy/scummvm, branch weblate-test`

Using `manage.py updategit --all` does work though. So I am using a crontab with this command for now. But it would be nice to have updates when receiving the notifications instead.

I am wondering if this might be related to using an access token in the repository URL. I followed the instruction from https://docs.weblate.org/en/latest/vcs.html#https-repositories and as a result my repository URL looks  like https://criezy:token@github.com/criezy/scummvm.git

### Server configuration
 * Weblate 2.9
 * Python 2.7.9
 * Django 1.10.3
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0b7
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * Database backends: django.db.backends.sqlite3

**Comment by nijel** [comment]
Does [project](https://docs.weblate.org/en/latest/admin/projects.html#project-configuration) have enabled hooks? Without that the hook requests are ignored.

Also what Git URL do you have set on the component? Maybe Weblate is not smart enough to recognize it (there are several ways to specify URL for GitHub repository).

**Comment by criezy** [comment]
To answer the questions:
* Yes hooks are enabled in the project settings.
* The Git URL in the Component is of the form https://criezy:access_token@github.com/criezy/scummvm.git (with a valid access token obviously)

**Comment by criezy** [comment]
With the more verbose logging I get:
`weblate[14428]: INFO received GitHub notification on repository https://github.com/criezy/scummvm, branch weblate-test,0 matching components, 0 to process
`

**Comment by nijel** [comment]
Okay, this code does not work for repos cloned with the access token.

**Comment by criezy** [comment]
Thank you for the quick fix!

As a follow up if somebody stumble upon this issue and uses Weblate code prior to the fix: if the repository is public and only requires authentication to push (but anybody can clone and pull), a solution is to use the access token only in the `Repository push URL:` (and not use it in the `Source code repository:`). Then Weblate properly pulls changes when receiving a GitHub notification.
