### ISSUE TITLE
Initiating a password reset immediately clears the current password

### ISSUE THREAD

**Issue by timonreinhard** [nijel/weblate#1280]
### Steps to reproduce
1. Click on the "Forgot your password" link on the login page.
2. Enter an email address of an existing user and submit the form.
3. Do _not_ use the confirmation link sent via email to set a new password.

### Actual behavior
The existing password for the user that initiated (but not yet completed) the password reset process is removed ("no password set"). The previously valid credentials can no longer be used to login.

### Expected behavior
The existing password remains intact until the confirmation link is used to set a new password.

### Server configuration
```
$ ./manage.py list_versions
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS, TEMPLATE_DEBUG.
 * Weblate weblate-2.8
 * Python 2.7.6
 * Django 1.9.6
 * six 1.10.0
 * python-social-auth 0.2.10
 * Translate Toolkit 2.0.0b7
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.6.0
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * djangorestframework 3.3.3
 * pytz 2012c
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 2.8.2
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
Fixed in git.
