### ISSUE TITLE
Translations do not get enough visibility

### ISSUE THREAD

**Issue by nijel** [nijel/weblate#1283]
Originally reported at https://github.com/phw/peek/issues/36#issuecomment-261744730 by @mohamedsakhri

> 
>  I'm no UX expert neither and I've only used Weblate for a short time till now.
> For me I have the impressions that there is too much items/entries in the interfaces. It is nice to have many features but than can be disturbing and prevent the user from doing the main work he wants to do: translating.
> So my suggestion would be to define a few main goals/features and make them accessible to the user easily in a user friendly interface, simple and clean.
> In the screenshot below you can see how "messy" the interface can get. In this case I think "Translations" is the most important part of the page and it should be in focus.

![002cc498-aeb2-11e6-8812-9a4c6592d898](https://cloud.githubusercontent.com/assets/212189/20531999/c4e9842e-b0d8-11e6-8d9a-97bb37218fa4.png)

**Comment by nijel** [comment]
Proposed fix is 09f079f3c436809bbe92e87edc283c880cafbd29

**Comment by nijel** [comment]
Well, this is good point, the translations really do not get enough space. I've changed this (and hidden remaining information to tabs), please check:

* Demo (running new code): https://demo.weblate.org/projects/hello/master/
* Hosted Weblate (running old code): https://hosted.weblate.org/projects/weblate/master/

What do you think about this @mohamedsakhri?

**Comment by mohamedsakhri** [comment]
It does look much better :+1: 

Here are some thoughts about the new interface:

1. The icon to configure columns isn't "self explicable" enough. I couldn't figure out what it is for before moving the mouse over it and reading its text "configure columns".
2. In the demo checking/unchecking columns doesn't seem to change anything (maybe a bug?)
3. Having two columns "Translated" and "Untranslated" seems redundant. You can figure out one by knowing the other.
4. The last column with the translate button/link is confusing. It only appears for languages which haven't reach 100% translation yet. I wanted to change a string for a project which its Arabic translation was already 100%. For a moment I thought there is no way to do it, as there is no "translate"-button.. and than "Oh, just click on the language name!"
5. The overview of each language might need a clean up as well. But I think you haven't changed it yet with this fix.

Keep up the good work :+1:

**Comment by nijel** [comment]
Ad 1 - true, however I have troubles finding better one

Ad 2 - bug, fixed in 434b14d

Ad 3 - yes it's redundand, that's why one of these is hidden by default, see https://github.com/nijel/weblate/issues/710

Ad 4 - hmm, true, probably the link should be there in all cases

Ad 5 - I didn't touch another page than project and component so far.

**Comment by mohamedsakhri** [comment]
1. You can think about displaying in another way than an icon. In my opinion this feature can be deleted because there aren't too many columns which cannot fit in one page. But it makes sense to keep it if you plan to add more columns because in this case the user may want to decide which ones they want to display.
4. Or you can delete it! The user would intuitively on the language ling if they don't see a translate button.

It's obvious that I prefer clean and simple designs, but that's only me :wink: 

I tried modifying and hiding some CSS attributes using my browser Dev tools and end up with this :blush:  What do you think about it?

![weblate-css-modified](https://cloud.githubusercontent.com/assets/2544216/20602251/bcb0f1e0-b25c-11e6-86a0-7cfda7441232.png)

**Comment by nijel** [comment]
The idea behind the button was to add direct link to strings needing action. Maybe it could be done only by listing the untranslated entries directly:

![hello_weblate_ _weblate_-_2016-11-24_16 31 47](https://cloud.githubusercontent.com/assets/212189/20603824/9e067b5a-b263-11e6-9dd7-2cfd04be92bb.png)

**Comment by mohamedsakhri** [comment]
As a translator or Admin I would use this overview to keep an eye on the project's progress. I wouldn't mind clicking the language I'm interested in first to have all the features I want to begin to continue translating. That bring us to the interface I mentioned in 5) in my first comment.

BTW: Is the demo automatically running the latest code?

**Comment by nijel** [comment]
But as frequent visitor, you want quick access to get the translations done. At least this is how I work and that's why there is translate button in the listings.

The deployment is manually triggered, I've pushed latest code to both demo and hosted few hours ago.

**Comment by burner1024** [comment]
I agree that translate button is very important. It's in fact the very first thing I want the users to do after opening a page - see a suitable translation, and jump at it. I don't think removing it is a good idea. (Or, at least, it could be left as an option for the administrator to switch on/off).

And, if you excuse me for slight hijacking, that's actually what I'm struggling with. For anonymous user, the default is to show "suggested translations", which has the translate button. But for a registered one, it defaults to "your subscriptions", which for some reason doesn't have the button.
It's actually taken me quite a lot of time to find this option and switch. I would like all new users to have suggested translations on the dashboard by default, is there any way that could be achieved?

**Comment by nijel** [comment]
@burner1024 The translate button should be there in all cases (before daacd33 it was shown only in case there is something untranslated).

**Comment by nijel** [comment]
I've read the comments here and I don't see consensus on any further changes here. I'll close this issue now and in case you want to push some suggestions, please create separate issue for each suggestion, so that it's easier to track the discussion. Thanks!
