### ISSUE TITLE
2.9: Amagama not working

### ISSUE THREAD

**Issue by burner1024** [nijel/weblate#1286]
### Steps to reproduce
1. add trans.machine.tmserver.AmagamaTranslation to MACHINE_TRANSLATION_SERVICES.
2. restart uwsgi
3. go to translation / machine transation tab

### Actual behaviour
See "The request for machine translation using Amagama has failed: MachineTranslationError: HTTPError: HTTP Error 404: Not Found"

### Expected behaviour
Provide some machine translation

### Server configuration

> 
> System check identified some issues:
> 
> WARNINGS:
> ?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_LOADERS.
>  * Weblate weblate-2.9
>  * Python 2.7.5
>  * Django 1.10.3
>  * six 1.10.0
>  * python-social-auth 0.2.21
>  * Translate Toolkit 2.0.0b6
>  * Whoosh 2.7.4
>  * defusedxml 0.4.1
>  * Git 1.8.3.1
>  * Pillow (PIL) 1.1.7
>  * dateutil 2.6.0
>  * lxml 3.6.4
>  * django-crispy-forms 1.6.1
>  * compressor 2.1
>  * djangorestframework 3.5.3
>  * pytz 2016.7
>  * pyuca N/A
>  * python-bidi 0.4.0
>  * pyLibravatar N/A
>  * PyYAML 3.12
>  * Mercurial 4.0
>  * Database backends: django.db.backends.mysql

**Comment by WorldCodeCentral** [comment]
Hello, since Amagama is similar to tmserver (says so in the docs) maybe you need to do the rest you have to do for tmserver that's not listed under Amagama for Amagama as well? See https://docs.weblate.org/en/latest/admin/machine.html#tmserver

Do you get tmserver or Weblate built-in machine translation to work? Because I don't (see my issue https://github.com/nijel/weblate/issues/1285)

**Comment by burner1024** [comment]
I don't believe it's needed. Amagama is basically a hosted tmserver, so tmserver's instructions apply to them.
I didn't try tmserver

**Comment by nijel** [comment]
It seems the public API URL has changed..

**Comment by burner1024** [comment]
That was fast. Thank you, will try once 2.10 is out.

**Comment by nijel** [comment]
You can also use tmserver backend right now and set URL to `https://amagama-live.translatehouse.org/api/v1`, that should work.
