### ISSUE TITLE
When using API and try to go to next component, next button redirects to weblate:8000

### ISSUE THREAD

**Issue by hbto** [nijel/weblate#1292]
https://FQAN/api/components/

https://weblate.vauxoo.com/api/components/

If there are more buttons 

We have set the correct name according to
https://docs.weblate.org/en/latest/admin/install.html#set-correct-site-name

and allowed_host according to documenation for docker and settings.py

https://hub.docker.com/r/nijel/weblate
       - WEBLATE_ALLOWED_HOSTS=your hosts
settings.py 
ALLOWED_HOST=[ ] (default)

Having all that said

when we try to reach the second page we are redirected to

http://weblate:8000/api/components/?page=2

https://lh3.googleusercontent.com/-Rh-Y3fskGjc/WEN_V2EJpvI/AAAAAAAAEb4/-9pXU2soGW8HHOFeF2XcwV1p1lEqupY6gCL0B/h1352/2016-12-03.png

Is there something else that we are overlooking.

Regards.

**Comment by nijel** [comment]
Indeed the Docker image is broken in this. I've tried to fix this in WeblateOrg/docker@0cc8545, can you please try if that helps?

**Comment by hbto** [comment]
Thanks a lot, @nijel 

We will check and let you know our findings.

Best Regards

**Comment by hbto** [comment]
@moylop260 & @ruiztulio Be aware.

Regards

**Comment by hbto** [comment]
Thanks a Lot @nijel 
It is working like expected.
I will be closing the Issue as It was solved with  WeblateOrg/docker@0cc8545
Best Regards.
