### ISSUE TITLE
Download translation files through API

### ISSUE THREAD

**Issue by pchinery** [nijel/weblate#1293]
We would like to establish a workflow where we have more control over the time when translations are pulled into the main project and would find it handy to use wlc to download the files.

Right now, we use a seperate git repo that is included through a submodule, but submodules always need a bit more attention than a simple folder would.

How are the ideas on implementing this?

**Comment by nijel** [comment]
There is API on the server for this, it's just not implemented in wlc:

https://docs.weblate.org/en/latest/api.html#get--api-translations-(string-project)-(string-component)-(string-language)-file-

**Comment by nijel** [comment]
Moving to https://github.com/WeblateOrg/wlc/issues/5

**Comment by pchinery** [comment]
Ah, thank you for pointing this out, we will have a look at it.

**Comment by nijel** [comment]
The download command will be part of wlc 0.7 (will be released today or tomorrow).

**Comment by pchinery** [comment]
Great, thank you very much!
