### ISSUE TITLE
Web API shows incorrect paths

### ISSUE THREAD

**Issue by pchinery** [nijel/weblate#1294]
### Steps to reproduce
1. Create a clean install of weblate 2.9 on port 8083
2. Configure a Site translate.mydomain.com
3. Access weblate through 127.0.0.1:8083

I don't know if the host/ip situation is important, so I am adding it here. I still find it cumbersome that I access weblate through an IP and port and the API responds with a different port and host name.

Any ideas on this? Will it disappear when we can actually use the domain?

### Actual behaviour
The call to http://127.0.0.1:8083/api/ gives this JSON:

```
{
    "projects": "http://weblate:8000/api/projects/",
    "components": "http://weblate:8000/api/components/",
    "translations": "http://weblate:8000/api/translations/",
    "languages": "http://weblate:8000/api/languages/"
}
```

### Expected behaviour
Something like this:

```
{
    "projects": "http://127.0.0.1:8083/api/projects/",
    "components": "http://127.0.0.1:8083/api/components/",
    "translations": "http://127.0.0.1:8083/api/translations/",
    "languages": "http://127.0.0.1:8083/api/languages/"
}
```

### Server configuration

 * Weblate 2.9
 * Python 2.7.9
 * Django 1.10.3
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0b7
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.2
 * lxml 3.4.0
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * pytz 2016.7
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.11
 * Mercurial 3.9.1
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
I guess you're using Docker image? This bug has been fixed there, please pull new version. See https://github.com/nijel/weblate/issues/1292
