### ISSUE TITLE
Enabling per-project ACL disables API access regardless of user's permissions

### ISSUE THREAD

**Issue by timonreinhard** [nijel/weblate#1296]
### Steps to reproduce
1. Enable ACL on a project
2. Grant a user permission to access that project
3. Call the API endpoint `/api/projects/` using that user's API token

### Actual behavior
The project with ACL enabled is not listed in the response.

### Expected behavior
All projects the user (identified by its API key) has permissions for are returned.

### Server configuration
```
 * Weblate weblate-2.9
 * Python 2.7.6
 * Django 1.9.6
 * six 1.10.0
 * python-social-auth 0.2.10
 * Translate Toolkit 2.0.0b7
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.6.0
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * djangorestframework 3.3.3
 * pytz 2012c
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 2.8.2
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
That might be caching issue as I can not reproduce this and there were no changes in the relevant code, probably cache cleanup is missing somewhere. I will look if caching at this scope is really good idea.

**Comment by timonreinhard** [comment]
Thanks for your fast response. I just checked out `master` but still the issue occurs to me. I did some basic debugging of `api/views.py#ProjectViewSet` and noticed that `self.request.user` is `AnonymousUser` while `self.request.META['HTTP_AUTHORIZATION']` contains the correct API key (prefixed with `Token`).

**Comment by nijel** [comment]
Hmm, seems that the Authorization header doesn't get to Django. What is your webserver setup?

In case you're using Apache ``WSGIPassAuthorization On`` is needed, see http://www.django-rest-framework.org/api-guide/authentication/#apache-mod_wsgi-specific-configuration

**Comment by timonreinhard** [comment]
`WSGIPassAuthorization` is `on` and since `self.request.META['HTTP_AUTHORIZATION']` contains the value of the `Authorization` header I expected my server setup to be correct.

**Comment by nijel** [comment]
Do you have REST_FRAMEWORK in settings.py as shown in Weblate example? I'm not sure if token based auth is enabled by default....

**Comment by timonreinhard** [comment]
I just added those settings and it works now as expected. Sorry for all the hassle, I missed this part when diffing the config.
