### ISSUE TITLE
Microsoft xml application resources (.resx files) support

### ISSUE THREAD

**Issue by stefanb** [nijel/weblate#153]
It would be interesting (not a must) to support those.
An [overview](http://www.alchemysoftware.ie/livedocs/cat9/alchemy_net_component/a_closer_look_at_.resx_files.htm) and [.resx xml file description](http://msdn.microsoft.com/en-us/library/ekyft91f%28v=vs.80%29.aspx).

**Comment by stefanb** [comment]
it looks like the upstream issue https://github.com/translate/translate/issues/396 was resolved in January with pull request https://github.com/translate/translate/pull/3242

Has anyone tried it in weblate already, or something needs to be done in weblate first?

**Comment by nijel** [comment]
As they don't have enabled autodetection in translate-toolkit, Weblate needs stub to find these files. I'll commit it now, but still it needs some testing afterwards. Also it's not yet in any released version of translate-toolkit...

**Comment by nijel** [comment]
Basic support is in git, it's not yet covered by testsuite as it depends on translate-toolkit from git. It would be great if somebody could test it.

**Comment by jmaxxz** [comment]
Has anyone successfully used a .resx file with web-late?

**Comment by jmaxxz** [comment]
Whenever I attempt to use weblate with a resx file I get a 500 internal server error.
```
Info: merging remote into repo
Exception occurred processing WSGI script
Trace back (most recent call last):
File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/hadlers/wsgi.py", line 189, in __call__
response = self.get_response(request)
File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/hadlers/wsgi.py", line 218, in get_response
```

**Comment by nijel** [comment]
Can you please get full traceback for the error?

**Comment by jmaxxz** [comment]
@nijel I am not sure where I can find that.

**Comment by nijel** [comment]
Either set ``ADMINS`` so that you get email with it or enable ``DEBUG``. See https://docs.weblate.org/en/latest/admin/install.html#installation

**Comment by jmaxxz** [comment]
```
IndexError at /admin/trans/subproject/add/
string index out of range
Request Method:	POST
Request URL:	http://.../admin/trans/subproject/add/
Django Version:	1.8.2
Exception Type:	IndexError
Exception Value:	
string index out of range
Exception Location:	/opt/bitnami/apps/weblate/weblate/lang/models.py in sanitize_code, line 115
Python Executable:	/opt/bitnami/python/bin/python
Python Version:	2.7.9
Python Path:	
['/opt/bitnami/python/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg',
 '/opt/bitnami/python/lib/python2.7/site-packages/django_crispy_forms-1.4.0-py2.7.egg',
 '/opt/bitnami/python/lib/python27.zip',
 '/opt/bitnami/python/lib/python2.7',
 '/opt/bitnami/python/lib/python2.7/plat-linux2',
 '/opt/bitnami/python/lib/python2.7/lib-tk',
 '/opt/bitnami/python/lib/python2.7/lib-old',
 '/opt/bitnami/python/lib/python2.7/lib-dynload',
 '/opt/bitnami/python/lib/python2.7/site-packages',
 '/opt/bitnami/python/lib/python2.7/site-packages/PIL',
 '/opt/bitnami/python/lib/python2.7/site-packages',
 '/opt/bitnami/apps/django/lib/python2.7/site-packages',
 '/opt/bitnami/apps/weblate',
 '/opt/bitnami/apps/weblate/weblate',
 '/opt/bitnami/common/lib/python2.7/site-packages']
Server time:	Tue, 7 Jul 2015 17:29:16 +0200
```

**Comment by jmaxxz** [comment]
Looking through the debug information I have diagnosed the issue. .Net resources normally follow this structure:
```
Solution/Project/Resources.resx (default language)
Solution/Project/Resources.de.resx
Solution/Project/Resources.es.resx
```

Web can not handle the default language scenario because the language code pulled from the file name is an empty string. This approach is acceptable for non default langues, however the default langues will not have a code and therefor is not usable by weblate at this time.

**Comment by nijel** [comment]
What filemask did you specify in this case? I guess it was ``Solution/Project/Resources*.resx`` while the correct one in this case would be ``Solution/Project/Resources.*.resx`` and to use ``Solution/Project/Resources.resx`` as monolingual base file.

Anyway I've fixed code to handle this situation gracefully in 5889ed4 with proper error message.

**Comment by jmaxxz** [comment]
I am using a filemask of `Solution/Project/Resources.*.resx` and a mono base of Solution/Project/Resources.resx

**Comment by jmaxxz** [comment]
My work around at weblate 2.3 is to add 
```
echo f| xcopy "$(ProjectDir)Resources.resx" "$(ProjectDir)Resources.en.resx" /Y
``
as a prebuild step to any project with resources, and use this copy of the real base file as the base file for weblate. (This is a hack, as it requires duplication of source, and does not support the editing of the base translation in weblate)

**Comment by nijel** [comment]
Thanks for clarification! I hope I've fixed this now.

**Comment by jmaxxz** [comment]
@nijel Patched our instance with 1f703ac088c2d871c22afc615d94dc1c9199d10b worked like a charm.

Thank you!

**Comment by nijel** [comment]
Great, just let me know if you see some other problems with this format.

**Comment by meeximum** [comment]
What about .resw files :-)

**Comment by stefanb** [comment]
It shouldn't be too much work with .resw files as their syntax seems identical to .resx.

**Comment by nijel** [comment]
If the syntax is same, it should work without any changes. So just try it :-). In case it won't work, please open separate bug.

Anyway resx should now work, so closing this one.
