### ISSUE TITLE
Visual string context/Celebrity strings

### ISSUE THREAD

**Issue by yarons** [nijel/weblate#250]
The problem:
When the translator gets the strings for translation they all appear as a list.
Although there's a reference to the source code it's not always helpful.

Suggested solution:
Adding a screenshot library that allows the user (or developer) to tag the strings to the screenshot, this way the user can use the screenshot to translate strings or the list and when there's a difficulty the translator can simply look at the screenshot with the tag and see the original context.
Another advantage is that one can tag the same string in different places (same way as you tag people in Facebook), this way the context is handled correctly in all cases.

Kind regards,
Yaron Shahrabani.
##

**Comment by algazarra** [comment]
Sorry for the dupe. This would be nice. Amateur translators need help. Being able to upload screenshots would make things much easier.

**Comment by nijel** [comment]
I see the use case here and it's indeed interesting, but somehow there are always things I see even more important. I'll see if I can do something about this during upcoming SUSE HackWeek, but I can't promise anything.

**Comment by marcodinissantos** [comment]
This is highly important for us as we want to improve the context of the translations. My suggestion is that  the project admin has the possibility to add a field to every string, where you can add the URL of an image. This way you wouldn't have storage issues.

**Comment by yarons** [comment]
Unless you put it as a comment it could be very problematic, I thought about adding this as a unit testing feature.

**Comment by rvanlaak** [comment]
Big :+1: on adding more translator context, where comments (with drag & drop screenshots à la Github) probably are able to help translators most.

Outdated comments (and so it's screenshots) could be detected based on the "date last changed" of the translation key. We don't think they change that often though, at least for our project.

**Comment by ta** [comment]
I hope this will not block the 2.9 release - much anticipated features in there :)

**Comment by nijel** [comment]
It's blocked rather by myself not feeling well than anything else :-). Anyway this feature will be in 2.9 and it will be released this week.

**Comment by dg0yt** [comment]
Will this be supported in the hosted version?

(I was thinking about providing links to screenshots or even more instruction by upstream source comments.)

**Comment by nijel** [comment]
Yes, it will be (later today). Screenshots can be uploaded only by projects admins.

**Comment by yarons** [comment]
I just saw this feature active in Crowdin when translating Xabber.

**Comment by nijel** [comment]
Weblate can now also automatically recognize source strings in uploaded images (see #1356 and #1366).
