### ISSUE TITLE
Please export comments to .po files

### ISSUE THREAD

**Issue by jan-hudec** [nijel/weblate#407]
Comments written in the web interface are only stored in the database, but not available from the repository for offline use.

It would be nice if Weblate wrote the comments entered over web to the translation files in format `(username) comment` or `(username) date: comment`. Translate-toolkit has support for searching comments by the parenthesized tag. That's why the date probably should not be part of the tag.

**Comment by nijel** [comment]
I don't think this is really good idea as in case some bigger discussion this would just pollute the po file.

**Comment by jan-hudec** [comment]
Even in case of some bigger discussion, I would prefer to have them in the `.po` file. Because:

 - Some translators may work by downloading the `.po` files, editing them in some local tool (like poedit) and uploading/sending them back. They may add comments and should see the comments made by previous translators.
 - The authors may want to do the review on the checkout as well.
 - It makes the weblate database a primary store of some information. I would prefer to have all the information in one place, the version controlled tree.

**Comment by justhamade** [comment]
+1 I agree with jan-hudec.

Another issue is from a UX perspective it is confusing to a user (me) which 'comments' go where.  If weblate comments are not written to the PO file then at a minimum I think it would to make sense that "Weblate Comments" are labeled differently from "PO File Comments" so that users understand that the comments they enter on weblate will not get added to the PO File and that they can not add comments to the PO File.
![screen shot 2015-04-15 at 9 11 42 am](https://cloud.githubusercontent.com/assets/110945/7163748/86cf0c92-e350-11e4-890b-a18e82ffba68.png)

**Comment by nijel** [comment]
Having the discussion in one place is indeed a good idea, however I see several issues with that:

- How to handle source string comments/feedback? Should it be added to all .po files in given component?
- Weblate would have to be able to parse the comments back, so it would have to add some markup to the comment to distinguish comments coming from it from other sources. I see this as biggest problem as many tools reformat .po file and creating something what will survive all this is non-trivial.
- Weblate currently shows only extracted comments from .po file, which are coming from source code (after `#.` in .po file), not translator comments (after `# `).
- This would be .po file only feature making most of other file formats behave differently.

**Comment by Rvanlaak** [comment]
We do not think the discussion should be saved in the source file, but being able to add a node (as supported by xliff) will improve the developer/translator interaction.

**Comment by jan-hudec** [comment]
The translate toolkit framework also treats the notes in po and xliff very similarly (with the difference, that in xliff there is explicit list of them while in po they are just added to one text block, because they are simply comment block). So it would be all formats that support notes behaving the same way.
