### ISSUE TITLE
API for controlling translations

### ISSUE THREAD

**Issue by nijel** [nijel/weblate#416]
In some cases it is useful to be able to control translations remotely, so far Weblate only provides hooks for pulling remote repository.

Scope of API planned for 2.6 is to be able to handle basic translation wide operations:

* [x] Commit all changes.
* [x] Trigger pull.
* [x] Locking/unlocking translations.
* [x] Download translation file.
* [x] Download monolingual base.
* [x] Download new translation template.
* [x] Upload translation file.
* [x] Listing of translation projects and components.
* [x] Token based authentication.
* [x] Include stats in API
* [x] Complete documentation for API
* [x] Rewrite data exports page to point to new APIs

This however needs some protection, OAuth is probably overkill here (and hard to manage for scripts), generating API key for each user should be good enough.

**Comment by huftis** [comment]
It would be nice if it was also possible to download translation *template* files (i.e. .pot files) using this API. I often find it useful to do manual merging of translation files with templates (perhaps using a custom compendium, or custom line-wrapping options), and this would enable this.

**Comment by nijel** [comment]
I've just started implementation of the API in the ``api`` branch: https://github.com/nijel/weblate/tree/api

**Comment by nijel** [comment]
Merged to master.

**Comment by nijel** [comment]
Documentation is available on usual place: https://docs.weblate.org/en/latest/api.html

Please comment if you miss something, but please note that there is no plan to go beyond translation objects in the API for 2.6.

**Comment by nijel** [comment]
Now deployed to demo server as well. Hosted Weblate will follow later (most likely next week).
