### ISSUE TITLE
URL validation does not allow non-FQDN

### ISSUE THREAD

**Issue by nblock** [nijel/weblate#499]
When configuring the repository URL, one can't add an URL without a FQDN. For example, if the repository server is reachable via https://scm, this URL can't be used for the repository browser. One has to add the local domain suffix (eg. '.lan') to get the URL accepted at the Subproject configuration interface. Is there a way to enable non-FQDN that I might have missed?

```
$ ./manage.py list_versions
 * Weblate 1.9
 * Python 2.7.3
 * Django 1.6.5
 * python-social-auth 0.1.26
 * Translate Toolkit 1.12.0-rc1
 * Whoosh 2.6.0
 * GitPython 0.3.2 RC1
 * gitdb 0.5.4
 * Git 1.7.10.4
 * South 1.0
 * Pillow (PIL) 1.1.7
 * lxml 3.3.5
 * ICU 1.8
```

**Comment by nijel** [comment]
There is no way around that in Django and I don't feel like workarounding this in Weblate, just specify FQDN.
