### ISSUE TITLE
Adding a new language (Qt Linguist)

### ISSUE THREAD

**Issue by nijel** [nijel/weblate#501]
AFAIK, in Weblate 1.9, adding a new translation file for a subproject
using Qt Linguist ts files is not supported.

In my oppinion, the best approach to implement this would be as follows:
 - Copy the base translation file.
 - Replace all translated strings in the copied file with empty ones:
   <translation>foo</translation> -> <translation type="unfinished"/>
 - Commit the new language file.

This approach allows the creation of an already up-to-date, empty
translation. Using this approach, there is no need to call lupdate
directly.

Another approach might be to simply create an empty ts file such
as seen in AndroidFormat [1] and commit it. The new translation file is
valid, but no source strings are available. Furthermore, there is not
enough information available to call lupdate directly from weblate (as
seen in PoFormat [2]).

What do you think? Is one of the approaches suitable or do I completely
miss the point?  I'm planning to provide you with a PR, once a good
approach for this is found.

[1] http://github.com/nijel/weblate/blob/master/weblate/trans/formats.py#L803
[2] https://github.com/nijel/weblate/blob/master/weblate/trans/formats.py#L685

PS: Originally sent by email to me, but I believe it's better to have the discussion in the issue tracker.

**Comment by ejjoman** [comment]
I don't think, Weblate has to change the *.pro file at all.
At first, it would be nice, if Weblate was generally able to add a new language to a project, so no one has to manually add it if it is requested by a user.

See Transifex for a example: It just adds a new .ts file and the dev has to add it manually to the .pro file, to include it into the project.

Sure, it would be better/nice to have if it got added to the .pro file automatically, but I don't think it's a big deal if the dev has to do it manually.
On the other hand, if a user has to request a new language and can not start translating directly, he loses his interest and never comes back.

Maybe, if you could give me some instructions where to start, I could add it this functionality by myself :)

**Comment by nijel** [comment]
Thanks for the pull request, looks good.

BTW: For PO files, I'd like to get rid of the msginit dependency :-), see #883.

**Comment by nijel** [comment]
PR merged.

**Comment by nijel** [comment]
Actually using lupdate for this is wrong - in way you've implemented it it always generates empty file.

**Comment by ejjoman** [comment]
What does empty mean? For me it worked absolutely correctly with this command - lupdate generated a file, based on the base file with empty (unfinished) translations.
Which version of lupdate did you use? I tested this with the version shipped with the package Qt5-Tools on Ubuntu.

But to use translation toolkit seems to be the better solution :)

**Comment by nijel** [comment]
I was using the Qt4 one (I happened to have installed that one and didn't actually care about version when testing)...
