### ISSUE TITLE
Add SVN support

### ISSUE THREAD

**Issue by nijel** [nijel/weblate#572]
Adding SVN support should be quite easy when using git-svn, basically just push, rebase and pull need to be adjusted, rest works same as git. This backend would obviously loose authorship, so it might be good idea to add author to commit message.

**Comment by mistic100** [comment]
Any evolution on this ?
We would like to use Weblate for the translation of Piwigo project and its plugins but most plugins are hosted on our Subversion repository.

**Comment by nijel** [comment]
AFAIK currently nobody is working on this.

**Comment by mistic100** [comment]
Can you point me out where VCS are managed ?
I like to take a look if I can add basic support

**Comment by nijel** [comment]
It's here: https://github.com/nijel/weblate/blob/master/weblate/trans/vcs.py

**Comment by mistic100** [comment]
I don't have patience to work with Python. It would be great if you could do it someday.

**Comment by roidelapluie** [comment]
I am starting on this.

**Comment by nijel** [comment]
See https://github.com/nijel/weblate/pull/1171

**Comment by nijel** [comment]
Added git-svn support based on #1171.
