### ISSUE TITLE
Not being able to upload new keys using file upload

### ISSUE THREAD

**Issue by mmahawar** [nijel/weblate#644]
Hi All,

I am getting "There were no new strings in uploaded file, processed 3 strings." error when I am trying to upload the a files with new translations.

Sample File
---------------
source,target
manisha,test
manisha1,test1
manisha2,test2
manisha3,test3

Thanks
Manisha

**Comment by nijel** [comment]
The problem is that translate-toolkit supports slightly different format, see http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/csv.html

But anyway I think Weblate should be handle this format as well.
