### ISSUE TITLE
Support ruby/rails i18n yml files

### ISSUE THREAD

**Issue by brauliobo** [nijel/weblate#645]
I really missed the support for ruby/rails i18n yml format. Do you have any milestone planned to support it?

Example file: https://github.com/noosfero/noosfero/blob/master/config/locales/en-US.yml

**Comment by nijel** [comment]
This really depends on translate-toolking supporting this format...

**Comment by brauliobo** [comment]
@nijel opened an issue on it

**Comment by nijel** [comment]
Initial support is there, it depends on https://github.com/translate/translate/pull/3500
