### ISSUE TITLE
Could not find template unit for new unit!   when switching from po bilingual to po monolingual

### ISSUE THREAD

**Issue by paulpach** [nijel/weblate#647]
I am not sure you want to classify this as a bug,  or just simply add to the documentation somewhere.

I created a project, and imported some po files as bilingual.   But after reviewing the code,  It was clear I was using the po files in monolingual mode,  so I tried to switch the component.

This left all the translation units in the database with empty context,  so every time I tried to update a translation it gave me this error:   Could not find template unit for new unit!

The solution was to delete the component completely and create it again as monolingual.

**Comment by nijel** [comment]
Switching the mode was not really tested, but I think it should work (it's just matter of forcing saving all units even if the content was not changed).
