### ISSUE TITLE
Leading new line in translations

### ISSUE THREAD

**Issue by Mikanoshi** [nijel/weblate#651]
If source string has a leading ↵ and you (or weblate) add it to a translated string, then translated string is displayed with two new lines instead of one in textarea.

**Comment by nijel** [comment]
What browser do you use? Mostly browsers AFAIK strip one newline,
that's why Weblate adds one extra. This code is there intentionally
since d8d01d8f.

**Comment by Mikanoshi** [comment]
All browsers. At least IE11, FF 35.0.1, Chrome 40, Opera 29.

**Comment by nijel** [comment]
Hmm strange, will look at it, probably somewhere we add one more \n...
