### ISSUE TITLE
Adding new unit to json fails

### ISSUE THREAD

**Issue by nijel** [nijel/weblate#654]
When translating unit which is not existing in json, the translate-toolkit backend does not properly add unit to storage, so it's stored only in Weblate database, but not in backend file.

**Comment by nijel** [comment]
Reported upstream at https://github.com/translate/translate/issues/3249

**Comment by SirAnthony** [comment]
Thanks for workaround. It seems I do not need to keep all those hacks with runtime patching of translate toolkit in my code anymore.

**Comment by nijel** [comment]
Hopefully they will merge the PRs as well (at least they have promised to do so).
