### ISSUE TITLE
Github integration

### ISSUE THREAD

**Issue by nijel** [nijel/weblate#656]
It would be nice to have better integration with Github, so even when users don't give Weblate access to push directly to the repository, it would create pull request for the translations.

**Comment by nijel** [comment]
Actually it could be implemented as another VCS backend, that would do fork/pull request instead of pushing changes upstream.

**Comment by fwalch** [comment]
@nijel Hi, just wanted to ask whether this feature is available on Hosted Weblate (not sure how I can check it myself)? :-)

**Comment by nijel** [comment]
Not yet there (mostly due to lack of time to configure and test it).
