### ISSUE TITLE
Usability issue in zen. People translate the message id instead of source

### ISSUE THREAD

**Issue by paulpach** [nijel/weblate#659]
I am finding that a few of my translators are translating the message id instead of the source in monolingual.

I believe the root cause is that in zen mode:
http://weblate-blockstory.rhcloud.com/projects/block-story/items/pt/zen/?sid=1b7daf22-b946-11e4-9ccc-22000b6b07c4

it is not very clear if it is the id or the source that needs translation.

Please consider rearranging so that the id is off to the side or even collapsed.

**Comment by paulpach** [comment]
The way I see it,  zen mode is useful for translators to quickly work on several strings quickly with minimal clicking. Essentially lets them focus just on translating with no distractions.

For these users,  I don't think the context is useful at all and is evidently causing confusion.  Perhaps it would be best to get rid of it altogether.   There is always the edit button available to see full details on a particular translation unit if needed.

**Comment by paulpach** [comment]
Just a comment,  if you click on the provided link,  you will no longer see the issue.   I patched my install and removed the context so only the source is visible.

**Comment by nijel** [comment]
Actually importance of context heavily depends on used translation format, so it should be rather shown or not depending on it and not unconditionally.

For example with Gettext, the context is used for differentiating same string which can be translated in different context, see for example here, where translation in many languages depends on gender:
https://hosted.weblate.org/projects/phpmyadmin/master/fr/zen/?q=None&search=exact&source=on&type=all&ignored=False

**Comment by paulpach** [comment]
I see,  fair enough.

Feel free to close this if you don't think this is an issue.   I'll just
keep mine patched and be done with it.

**Comment by nijel** [comment]
I've implemented hiding context for monolingual translations, where it indeed is not that useful.
