### ISSUE TITLE
Cannot add or remove a newline from translation

### ISSUE THREAD

**Issue by lleoha** [nijel/weblate#660]
Adding or deleting a newline (by ENTER) in the translation text followed by clicking Save button does nothing. When I get back to the translation text no newline changes are preserved.
Using po files.

**Comment by nijel** [comment]
Does the original message have newline as well? In case it does not, it's probably because of automatic fixups (see http://docs.weblate.org/en/latest/admin/config.html#std:setting-AUTOFIX_LIST). Do you get message about automatic fixup being applied?

**Comment by lleoha** [comment]
Yes, The original message does contain newlines, and the translation test in the .po file looks ok (newlines-wise) but it is redered with extra newlines in the translated message on the web.

**Comment by nijel** [comment]
Then I guess this is just duplicate of https://github.com/nijel/weblate/issues/651

**Comment by lleoha** [comment]
Yes, looks like a duplicate of #651.
