### ISSUE TITLE
Weblate updates 2 translation units simultaneously.

### ISSUE THREAD

**Issue by paulpach** [nijel/weblate#662]
I have 2 po-mono subprojects inside the same project.

the 2 po-mono subprojects have the same msgid,  but different texts.   The file structure is:

ItemNames.pot
en/ItemNames.po (source)
es/ItemNames.po
...

Items.pot
en/Items.po (source)
es/Items.po
...

Sometimes, updating a translation unit in ItemNames also updates the translation unit in Items.

here is an example:
http://weblate-blockstory.rhcloud.com/projects/block-story/itemnames/en/translate/?sid=2ff2c6c2-bc57-11e4-a600-22000b6b07c4&offset=247
http://weblate-blockstory.rhcloud.com/projects/block-story/items/en/translate/?sid=7617cb8e-bc57-11e4-a600-22000b6b07c4&offset=176

If I change either one,  they both change.

**Comment by paulpach** [comment]
Seems to happen when I am editing the source (english),  I don't know if it happens when editing anything else.

**Comment by nijel** [comment]
It happens for all languages as Weblate by default does push changes made in one component to others. If you are using monolingual translation it's usually good idea to disable it. Just uncheck "Allow translation propagation" in component settings.

See also our documentation for more information:
https://docs.weblate.org/en/latest/admin/projects.html#component-configuration
https://docs.weblate.org/en/latest/faq.html#how-do-i-translate-several-branches-at-once
