### ISSUE TITLE
Subproject.branch default value is master

### ISSUE THREAD

**Issue by OleLaursen** [nijel/weblate#663]
When I tried to set a test instance up with Mercurial, the first thing I bumped into was that the default value for the branch is set to "master". I suppose this works with Git, but with Mercurial I bump into configure_branch in vcs.py that complains that the branch must be "default". Took a while to figure out that one of the fields I hadn't touched had an incompatible default value.

Perhaps you could use use empty string as default and treat it specially, or treat "default" specially for git? If you aren't already, I suppose this could just be a bug. :)

Another thing that I couldn't figure out initially is that the intro docs talks about creating a component, but the model is actually subproject.

Otherwise, thanks for Weblate, it's awesome!

**Comment by nijel** [comment]
Indeed having default as empty and set it according to used VCS sounds like a good idea.

**Comment by nijel** [comment]
Changed, it now defaults to empty string and is filled in based on used VCS.
