### ISSUE TITLE
It is not possible to create new translations using java property files

### ISSUE THREAD

**Issue by WTBenjamin** [nijel/weblate#665]
I've successfully set up weblate for my translation projects.
But when i try to create a new translation, that is not already present as an empty file in the repository, i get an error.

I tied to set the base file for new translations in the according sub-project. Unfortunately i get the following error when i try to save the sub project:

Base file for new translations is not used because of project settings.

**Comment by nijel** [comment]
Support for creating new translations using Java properties has been merged today, see #664.
