### ISSUE TITLE
Missing list of available checks in documentation

### ISSUE THREAD

**Issue by WTBenjamin** [nijel/weblate#666]
It would be really nice if the documentation:
https://docs.weblate.org/en/latest/admin/config.html#check-list
would have a list of available checks to be configured like:
https://docs.weblate.org/en/latest/admin/config.html#autofix-list

Most appreciated would be a gui to configure which checks will get executed on project basis. ;)

**Comment by nijel** [comment]
The full list is available in configuration sample: https://docs.weblate.org/en/latest/admin/sample.html

Also you can disable individual checks per component, see https://docs.weblate.org/en/latest/admin/checks.html#fine-tuning-existing-checks

But indeed the documentation should be more clear on this:

*  [ ] Document all ways of customizing (source string customization in Weblate is not currently documented)
* [ ] List all checks in the configuration
* [ ] List all check IDs for ignoring

**Comment by WTBenjamin** [comment]
Thank you very much for your repeatedly super fast response!
I read the docs you stated but i still have an issue ignoring a spezific check.
I tried to disable the "same check" per component. According to https://docs.weblate.org/en/latest/admin/checks.html#fine-tuning-existing-checks i tried the following strings:

ignore-SameCheck
ignore-weblate.trans.checks.same.SameCheck

but in both cases i got the error "Invalid check flag". Maybe an explicit example for this case (in addition to "ignore-*") in the documentation would be helpful.

**Comment by nijel** [comment]
You need to use short check name, which is indeed not documented. In this particular case it should be ```ignore-same```.

**Comment by WTBenjamin** [comment]
Works like a charm! :smiley:
Thank you very much!

**Comment by nijel** [comment]
I've updated documentation to cover all these.
