### ISSUE TITLE
Sources in monolingual po showing failing checks

### ISSUE THREAD

**Issue by paulpach** [nijel/weblate#667]
The sources (english) of my monolingual pos are showing failing checks, 
http://weblate-blockstory.rhcloud.com/projects/block-story/stores/en/

When I click on "Strings with any failing check",  I see the strings,  but there is no failed check:
http://weblate-blockstory.rhcloud.com/projects/block-story/stores/en/translate/?type=allchecks

Perhaps sources should be exempt from checks altogether?

**Comment by nijel** [comment]
Were you running version from Git in past? If so I think this issue has been fixed meanwhile. Can you please try whether running ```./manage.py updatechecks --all``` makes the flag go away?

**Comment by paulpach** [comment]
I'll pull and updatechecks...

**Comment by paulpach** [comment]
I pulled, and ran updatedchecks
I also needed to run fixup_flags

it now works,  thanks.
