### ISSUE TITLE
link to source edit in monolingual

### ISSUE THREAD

**Issue by paulpach** [nijel/weblate#669]
When I am translating something,  sometimes I spot a typo in the source.

It would be great if there was a link to jump to the source where I can fix the typo.
Right now I have to search for it.

**Comment by algazarra** [comment]
+1

**Comment by comradekingu** [comment]
@nijel I am not seeing this for Android string resources, even when monolingual string base file and source code repo is filled out. https://hosted.weblate.org/settings/trebleshot/strings/#files https://hosted.weblate.org/settings/trebleshot/strings/#vcs and the context is listed next to the string translation too.

**Comment by nijel** [comment]
I can see it there - pencil icon just next to "Source" label.

**Comment by comradekingu** [comment]
@nijel
As the case may be, I am not, but then again I might be the actual problem.
Missing:
![image](https://user-images.githubusercontent.com/13802408/68078102-9adced80-fdc7-11e9-9647-83625f2d6fd7.png)
https://hosted.weblate.org/translate/trebleshot/strings/nb_NO/?checksum=326d66e3c8b0986

---

Present:
![image](https://user-images.githubusercontent.com/13802408/68078189-e217ae00-fdc8-11e9-986e-4ead6e9a930a.png)
https://hosted.weblate.org/translate/dino/translations/nb_NO/?checksum=dd9a74c58633f9d9

I see the pencil where I can change things, but I want to get to https://github.com/genonbeta/TrebleShot/blob/master/app/src/main/res/values/strings.xml more easily than clicking through the link in https://hosted.weblate.org/projects/trebleshot/#information

**Comment by nijel** [comment]
Okay, this issue is about editing source string within Weblate. The edit link is not present in the zen mode.

The linking to repository was already discussed in https://github.com/WeblateOrg/weblate/issues/2106. We could probably do something with that, but let's discuss it there.
