### ISSUE TITLE
Non-breaking spaces

### ISSUE THREAD

**Issue by fisharebest** [nijel/weblate#674]
In French, it is customary to leave a space before certain puncuation.  For example:

English: `Are you sure you want to delete “%s”?`

French: `Voulez-vous vraiment supprimer « %s » ?`

Weblate correctly checks for the missing space before the question mark. (Nice!)

But, this should be a non-breaking space, and my translators prefer to use the HTML entity `&nbsp;`:

`Voulez-vous vraiment supprimer «&nbsp;%s&nbsp;»&nbsp;?`

Sometimes they use the unicode character `U+00A0`.

Is it possible to amend the check to allow `&nbsp;` or `U+00A0` as an alternative to a space?

**Comment by nijel** [comment]
The ```U+00A0``` should work fine, ```&nbsp;``` was supposed to work as well, but the implementation is buggy.

**Comment by samhocevar** [comment]
Note that `fr_FR` French indeed uses ` ` (U+00A0 NO-BREAK SPACE) before `:`, but ` ` (U+202F NARROW NO-BREAK SPACE) is preferred before `;` `?` `!`. It seems that `fr_BE` is slightly different and doesn’t use any spacing character before `;`. Wikipedia has a [summary](http://fr.wikipedia.org/wiki/Ponctuation#Les_espaces_autour_des_signes_de_ponctuation_.28r.C3.A8gles_actuelles.29).
