### ISSUE TITLE
enhancement: Commit this file

### ISSUE THREAD

**Issue by emmapeel2** [nijel/weblate#676]
It would be great to be able to commit one specific file to the repo, even maybe changing the commit message. 
Currently I can only commit all the changes at once, but my idea is to create a cleaner git log and just commit big changes, letting one liners for next commit if possible.

**Comment by nijel** [comment]
If you have appropriate permissions, you can commit single file. Just choose commit on the repository maintenance for the translation (the page looks same on the project/component or translation, but the operations perform only on that chosen object).

**Comment by emmapeel2** [comment]
Oh then it was bad timing or the permissions. I did click on the 'subproject/component' for the specific translation to commit but it went all over the changes...

**Comment by nijel** [comment]
Actually adding some frequent operations like commit directly to the tools menu makes IMHO sense, so that it's easier to find.

**Comment by emmapeel2** [comment]
thanks!
