### ISSUE TITLE
Enhancement: ability to hide completed components in user view

### ISSUE THREAD

**Issue by emmapeel2** [nijel/weblate#677]
I have many components in my project and I just browse over the first ones always, and they are all completed.

It would be great to be abe to hide-unhide the completed translations when i am a translator.

**Comment by emmapeel2** [comment]
thanks!

**Comment by nijel** [comment]
Also related to #568 (if there are some components you don't want to follow at all).

**Comment by emmapeel2** [comment]
thanks!

**Comment by emmapeel2** [comment]
Actually... it would be hard to also make this option act on the hover-on list ('Your translations') of the Top Menu when logged in? 
Finished components keep appearing there even when the option is selected...
(Low priority suggestion anyway!)

**Comment by nijel** [comment]
Please open separate issue for that, but that's definitely not hard ;-).

**Comment by emmapeel2** [comment]
ok then! it is now #1251
