### ISSUE TITLE
.po comments could be displayed more prominently

### ISSUE THREAD

**Issue by samhocevar** [nijel/weblate#678]
I put a lot of comments in `.pot` files to help translators with the context in which strings are used, especially when they are short. But I think comments aren’t very visible to translators, as they are mixed with a lot of additional information that is not directly useful to them:

![image](https://cloud.githubusercontent.com/assets/245089/6715629/fe59ef6e-cd9f-11e4-8b6b-c94522e192e5.png)

Maybe the comments could be displayed closer to the text area? Here is a mock up:

![image](https://cloud.githubusercontent.com/assets/245089/6715747/e44a469a-cda0-11e4-9b4a-36803c549a94.png)

**Comment by nijel** [comment]
The problem here is where to cut the line what is important and what not. In past both comment and context were shown more prominently, but people then complained it takes too much space. That's why it's placed currently in the sidebar.

**Comment by samhocevar** [comment]
Sure, I understand. There appears to be a loose convention that important comments directed at translators start with a `TRANSLATORS:` tag, as seen in several places in [the gettext manual](http://www.gnu.org/software/gettext/manual/gettext.html) and even in the [gettext Wikipedia article](http://en.wikipedia.org/wiki/Gettext). Maybe the existence of that tag could be where to draw the line?

(I don’t feel very strongly about this issue, so feel free to wontfix it)

**Comment by samhocevar** [comment]
Just a quick note: [this request for clarification](https://hosted.weblate.org/projects/wincompose/master/ru/translate/?checksum=b675391189e49c7ef809f17d862fbd6e#comments) just appeared from a contributor; they definitely appear to have missed the comment section.

**Comment by nijel** [comment]
I've tried to address this in c28df88e24726a88035d7eac9c9b14a4fe6dc1c8.
