### ISSUE TITLE
Vagrant box

### ISSUE THREAD

**Issue by hpatoio** [nijel/weblate#685]
I'm just wondering if someone has, and feel like sharing, a Vagrant box with everything is needed to run Weblate.

**Comment by nijel** [comment]
There seems to be something old on GitHub (found it accidentally):

https://github.com/nijel/weblate/compare/master...fluentglobe:master

**Comment by mobidev111** [comment]
How about creating a working box with docker-compose - my first shot at it is here: https://github.com/nijel/weblate/issues/808

**Comment by nijel** [comment]
The Docker support is documented here: https://docs.weblate.org/en/latest/admin/deployments.html#docker
