### ISSUE TITLE
Request for assistance - continuous translation.

### ISSUE THREAD

**Issue by grzeg1** [nijel/weblate#687]
The project (Runalyze) is using gettext po/pot files.
From what I've read in Weblate documents it's up to the user to update translation templates.
To assist in continuous translation I'd like weblate to call `xgettext` after each pull so the template is updated. But there's no option to call user script from github hook. 
I tried to look at the source code but it looks like git management is not done through external scripts, but internally. So (not being python expert) I have no clue how to set it up.
Can you please point me in the right direction?

**Comment by nijel** [comment]
Weblate currently does not try to integrate running xgettext (or similar tools) for simple reason, that it's hard to determine whether it's needed and running it for every commit is waste of time and produces useless commit (usually msgmerge creates some changes in po files even if there is real change).

If you really want to do this in Weblate, the right place to hook is beginning of the `SubProject.create_translations` method.

**Comment by grzeg1** [comment]
What exactly I want to do is fire some kind of script that would check if running `xgettext` and/or updating files is needed and if so, run the update.
Could you be so kind and implement an option to call user-defined script before processing github hook? I think there is already something like this for pre-commit.
I'll try my best with the code of `SubProject.create_translations` but it's my first encounter with Python so I'm not sure where I'll get :(

**Comment by nijel** [comment]
Hmm, it probably makes sense to provide hook for this as well, I've now added it to git (see commit above).

**Comment by grzeg1** [comment]
Thank you. I'll see what we can do with it and report back.

**Comment by grzeg1** [comment]
Thanks again. It seems to be working right. Now everything gets updated automatically.
