### ISSUE TITLE
Ambiguity in docs

### ISSUE THREAD

**Issue by FostUK** [nijel/weblate#688]
I've been going through setting up weblate for the first time and collating notes about the process (one thing I like to do is update docs :) ). I've gotten a little stuck and endlessly trawling the docs hasn't helped with these points:

1: Am I right in thinking 'components' got renamed to 'sub-projects' at some point?

2: The requirements for setting up a component or sub project are a little vague. Do I have to have an existing git repo with translation files in it or can I create an empty one and add strings to it via weblate? 

3: If a sub project has to have an existing git project, does it need some sort of remote ref? I'm getting "Failed to fetch repository: fatal: Couldn't find remote ref refs/heads/master fatal: The remote end hung up unexpectedly error: Could not fetch origin (1)" when I try to use a local git repo containing an xliff.

Hoping I can update the docs and make it easier for anyone else setting up for the first time if I can work this out!

**Comment by nijel** [comment]
You're right about 1, I've hopefully fixed remaining references to the subproject now.

For the rest, you need existing repository with translations.

**Comment by FostUK** [comment]
Awesome - thanks for the help. Any ideas on the issue of "Could not fetch origin" using a local repo? Looks like a git pull error that so I could prob check the exact command being called in the source.

**Comment by nijel** [comment]
You've probably specified some URL which git does not treat as local, if you want local one, it needs to be ```file://....```.

**Comment by FostUK** [comment]
I think it's possibly something with the repo setup as it's picking up the local file via absolute path or file:// and giving the same error. I'll have another look at it tonight.

**Comment by nijel** [comment]
Actually Weblate in this case is just showing the Git error message, it does not handle anything special here...
