### ISSUE TITLE
forbid anonymous access to everything

### ISSUE THREAD

**Issue by WTThomas** [nijel/weblate#695]
Hello,

it would be really great if there would be the possibility to disable anonymous access ***completely***.
Right now an anonymous user is always enabled to look at the statistics, activity page of users (including last login, registration date, made suggestions & translations), Tools (Language summary, Checks overview,...)

On my installation anonymous access looks like this:
![image](https://cloud.githubusercontent.com/assets/3327272/6963572/1f60a9e4-d941-11e4-94a8-386e7825fe92.png)

I think this is very bad for privacy. Somtimes, some participating users (including me ;-) ) don't want their translation-activities to be publicly visible to the whole world.

If it is already possible to disable the anonymous access completely can you please give me a hint where to to this? If not that would be a feature request by me for future versions.

Regards
Tom

P.S. I appreciate your efforts for this project and think this is ***the best*** tool to do translations!

**Comment by nijel** [comment]
This already exists - LOGIN_REQUIRED_URLS, see our docs for more
details:

http://docs.weblate.org/en/latest/admin/config.html#std:setting-LOGIN_REQUIRED_URLS

**Comment by marcperrin** [comment]
But even when a user is logged in, let's say we have 2 projects A & B and the user U has access to A but not B: U can still (at least in Languages summary and Statistics) see data relative to project B (actualy site-wide data) he should not be able to see.

**Comment by nijel** [comment]
That's true - sitewide stats and language summary is currently not filtered.

**Comment by marcperrin** [comment]
By the way, I've used LOGIN_REQUIRED_URLS, and a side-effect was to deny API access. 
I guess the doc for LOGIN_REQUIRED_URLS_EXCEPTIONS could suggest r'/api/(.*)$'? (maybe even include it in the default value for LOGIN_REQUIRED_URLS_EXCEPTIONS?)

**Comment by nijel** [comment]
Good point, I've just added it.

**Comment by nijel** [comment]
I've also documented that sitewide stats and language list does include counts for ACL projects as well.
