### ISSUE TITLE
ValueError at /admin/trans/subproject/add/ need more than 1 value to unpack

### ISSUE THREAD

**Issue by janmarek** [nijel/weblate#700]
I'm trying to create subproject in admin with these values in POST:

key | val
--------------------------------------- | ------------------
allow_translation_propagation	 | u'on'
report_source_bugs | u''
new_lang	 | u'none'
filemask	| u'translations/po/*.po'
pre_commit_script	| u''
extra_commit_file	| u''
_save	| u'Save'
committer_email	| u'noreply@weblate.org'
git_export	 | u''
file_format	| u'po-mono'
vcs	| u'git'
branch | u''
commit_message	| u'Translated using Weblate (%(language_name)s)\r\n\r\nCurrently translated at %(translated_percent)s%% (%(translated)s of %(total)s strings)'
csrfmiddlewaretoken 	| u'ZF2BZHbIonUgJlUPGPg14wIQU2Qk8anA'
post_update_script	| u''
new_base	| u''
template	| u'en_US'
save_history | u'on'
repo	| u'ssh://git@gitlab.firma.com:cosi/projekt.git'
slug	| u'zona'
edit_template	| u'on'
name	| u'zona'
license	| u''
repoweb	| u''
suggestion_autoaccept	| u'0'
project	| u'1'
license_url	| u''
merge_style	| u'rebase'
push	 | u''
committer_name	| u'Weblate'
check_flags	| u''

What am I doing wrong? Is it a bug or "just" missing validation of any of the fields?

**Comment by nijel** [comment]
Any chance to get full backtrace? It's hard to guess cause of problem this way.

**Comment by janmarek** [comment]
Yes. You can download it in this link: https://onedrive.live.com/redir?resid=A9831186FBEE2F7A!22966&authkey=!AHzsgId0CYe5ghg&ithint=file%2chtml

**Comment by nijel** [comment]
Thanks, should be fixed in git now.

**Comment by janmarek** [comment]
Thank you!
