### ISSUE TITLE
no search results even when present in original (?)

### ISSUE THREAD

**Issue by algazarra** [nijel/weblate#702]
I'm searching for "monitor" which is present in the original version, but I get 0 search results.

**Comment by nijel** [comment]
Do you use fulltext search? Then it might be just that you have enabled offloaded indexing and do not start the service.

**Comment by algazarra** [comment]
yes, and I was searching in a string translation where the original has the searched word.

![001_weblate](https://cloud.githubusercontent.com/assets/7598320/7086960/573f7654-df7e-11e4-99aa-e595f97d22c9.PNG)
![002_weblate](https://cloud.githubusercontent.com/assets/7598320/7086961/5742926c-df7e-11e4-8b4f-dc012ad4fa51.PNG)

**Comment by nijel** [comment]
Indeed it looks that the fulltext search is not working properly here. You can use substring search meanwhile to find the string...
