### ISSUE TITLE
search results for all translations

### ISSUE THREAD

**Issue by algazarra** [nijel/weblate#703]
I'm trying to see how "monitor" was translated across multiple languages at once. Is this possible?

**Comment by nijel** [comment]
There is sitewide search which you can use for this: https://hosted.weblate.org/search/?q=monitor&search=exact&source=on&type=translated

**Comment by algazarra** [comment]
TY
the layout could be organized differently to improve usability:

search term | Search Results (column with all translated versions
XXXXXXXX | EN YYYY
                      ES AAAAA
                      FR ZZZZZ
                      etc.

what do you think?

**Comment by nijel** [comment]
There are different groupings which would make sense, but I don't think it's really good fit. Maybe what you are actually looking for is  #411.

**Comment by algazarra** [comment]
#411 exactly! that would be great. first the original string, then translations, horizontally or vertically.
