### ISSUE TITLE
user can configure different base language than English

### ISSUE THREAD

**Issue by mfrasca** [nijel/weblate#705]
I'm very new to weblate, so I'm probably mentioning something which is already there.
imagine that my software is English based but 100% translated into French, and that I have bilingual French-Arabic translators. how can they help?
Or even, I have a 100% Czech translation and I want to base my Polish translation on it.

**Comment by nijel** [comment]
There is currently no way to disable English, but you can configure secondary languages, which will be show in addition to the English source, see https://docs.weblate.org/en/latest/user/profile.html#secondary-languages

**Comment by mfrasca** [comment]
nice. I had not noticed it. 
The secondary languages are not taken into account in Zen mode.

**Comment by mfrasca** [comment]
what about, when I'm reviewing a translated item, putting an other tab, next to `Nearby messages`, `Comments`, `Machine translation`, `Search`, `History`, where you can show, for the current item, some (selected) translations to other languages?

**Comment by nijel** [comment]
For the Zen mode, it's already reported: https://github.com/nijel/weblate/issues/483

As for another context tab below translation, I'm not sure if it would be better than current solution...

**Comment by mfrasca** [comment]
my idea, why it would be better...
as of now, I am selecting "Portuguese" as my secondary language just because I'm currently translating a project into Spanish and the Portuguese translations happens to be already 100% complete.
Then I see that German is more complete than Dutch and again I go to my profile settings and say my secondary language is German not because it is, but because it comes handy when reviewing Dutch.
me going to my profile settings and altering them for the sake of one project is not such a big deal, but it feels like I'm working around something I miss.

**Comment by nijel** [comment]
My current idea is to add option to hide source in case secondary language is there. What I'm afraid is that this way errors in translations will spread, which would not happen if everybody translates from same source...
