### ISSUE TITLE
Openshift and static files

### ISSUE THREAD

**Issue by nijel** [nijel/weblate#709]
Currently the Openshift setup does not properly handle static files placed in the web server root - ``favicon.ico`` and ``robots.txt``.

Seen at https://github.com/nijel/weblate/issues/679#issuecomment-85029278

Might be something for @dtschan...

**Comment by dtschan** [comment]
I'll look into this

**Comment by nijel** [comment]
Thanks @dtschan

**Comment by paulpach** [comment]
Just to confirm this worked for me.   Tx.
