### ISSUE TITLE
New column "Untranslated keys"

### ISSUE THREAD

**Issue by WTBenjamin** [nijel/weblate#710]
Wouldn't it be useful to introduce a new column "Untranslated keys", showing the percentage of untranslated keys. Similar to the column "Fuzzy".

![Translations](https://cloud.githubusercontent.com/assets/3327861/7115768/c5228f0c-e1eb-11e4-9dbb-1e4adaee5298.png)

Regards
Ben

**Comment by nijel** [comment]
Well it's just 100 - Translated and we're already fighting for space here...

**Comment by WTBenjamin** [comment]
You could add the column invisible, but with the possibility to be shown via the "Configure columns" popup.

Or you could make the percentage "94.9%" in the column "Translated" clickable like the values in the "Fuzzy" column. With these new links you could even remove the "Translate" buttons to save some space if you want to.
