### ISSUE TITLE
call django clearsessions on cronjob

### ISSUE THREAD

**Issue by paulpach** [nijel/weblate#714]
After a while,  my OpenShift quota filled up.

Digging deeper, I found the culprit was the django_sessions  database table.  It grew to 300 MB.

It turns out that django does not automatically clean up this table, and one is supposed to call
`django-admin.py clearsessions`

in a daily cron job  in order to keep this table in check.

I suggest adding this cronjob to your openshift configuration for weblate.

**Comment by nijel** [comment]
I store sessions in memcached to avoid this problem - the sessions simply expire at some point.

Anyway I've added the cron job to openshift and also documented this in our documentation.
