### ISSUE TITLE
Internal server error on latest commit

### ISSUE THREAD

**Issue by paulpach** [nijel/weblate#715]
The latest git commit gives an internal server error.   From the log:

[Thu Apr 16 09:28:23 2015] [error] [client 127.11.230.1] mod_wsgi (pid=485298): Target WSGI script '/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/wsgi/application' cannot be loaded as Python module.
[Thu Apr 16 09:28:23 2015] [error] [client 127.11.230.1] mod_wsgi (pid=485298): Exception occurred processing WSGI script '/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/wsgi/application'.
[Thu Apr 16 09:28:23 2015] [error] [client 127.11.230.1] Traceback (most recent call last):
[Thu Apr 16 09:28:23 2015] [error] [client 127.11.230.1]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/wsgi/application", line 25, in <module>
[Thu Apr 16 09:28:23 2015] [error] [client 127.11.230.1]     from .virtualenv import activate
[Thu Apr 16 09:28:23 2015] [error] [client 127.11.230.1] ValueError: Attempted relative import in non-package
76.215.40.140 - - [16/Apr/2015:09:28:16 -0400] "GET / HTTP/1.1" 500 631 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"

I reverted this commit: https://github.com/nijel/weblate/commit/7b7ee8a2465571f3d3359ca988419f19ebda7491

and it now works

**Comment by nijel** [comment]
Reverted in master as well.

**Comment by nijel** [comment]
I've tried to share code using execfile, please check if 2d5c3b4 does not break anything.

BTW: Is there some way to automatically test whether openshift installation works fine? I'd like to avoid such errors in future.
