### ISSUE TITLE
Change openshift setup to use mysql

### ISSUE THREAD

**Issue by paulpach** [nijel/weblate#716]
I would like to propose that the openshift setup is configured to use mysql instead of sqllite.

I have done this work for my own build and I was wondering if others would see value in it.

If you guys think it is a good idea,  I might spend some time to put together a pull request for it.  If not,  just close this and move on with your lives.

**Comment by nijel** [comment]
I think it's good idea as sqlite generally does not perform well in many situations.

**Comment by paulpach** [comment]
This was merged in #727
