### ISSUE TITLE
Duplicate msgid's in po files causes error page

### ISSUE THREAD

**Issue by lainbsd** [nijel/weblate#717]
When attempting to add a subproject or pull from a git repository that contains a po file with duplicate source strings an error page shows and (correctly as duplicates shouldn't enter Weblate I assume) nothing is imported.

```
ERROR Internal Server Error: /admin/trans/subproject/add/
AttributeError at /admin/trans/subproject/add/ type 
object 'Change' has no attribute ‘object'
```

Although po files should not contain such duplicates in the first place the po files created by Translate Toolkit will have duplicates if the source format had them, so this problem may exist when importing other file formats to Weblate, especially for CSV and formats that don't enforce unique keys. 

A notice on the UI side that the error is due to duplicate source strings might be preferable if this is reproducible.

**Comment by nijel** [comment]
Already fixed in 73eb8400, upgrade please.
