### ISSUE TITLE
404 on a dependency

### ISSUE THREAD

**Issue by paulpach** [nijel/weblate#721]
I don't know how much this matters but when I request my page:
http://weblate-blockstory.rhcloud.com

It requests
http://weblate-blockstory.rhcloud.com/media/js/chartist.min.js.map
but this produces a 404 Not found error.

To reproduce:
open google chrome
open the developer tools
click on network tab
open the url http://weblate-blockstory.rhcloud.com
observe the requests being made, and a 404 error on this particular resource.

**Comment by nijel** [comment]
Probably caused by the developer tools trying to get some mapping of minified javascript. I guess you get more errors like this as there are more minified javascripts.

**Comment by nijel** [comment]
I've fixed this in git while upgrading this library.
