### ISSUE TITLE
Problem with encoding

### ISSUE THREAD

**Issue by hpatoio** [nijel/weblate#737]
Weblate encodes string even if, IMO, it should not.

So for instance it gives me this

```
<source><![CDATA[<strong>BEST PRICES</strong>guaranteed on tours]]></source>
<target state="translated">&lt;strong&gt;Melhor preço&lt;/strong&gt; garantido</target>
```
Is there any setting I need to change or the `source` is wrong and doesn't need `CDATA` ?

**Comment by nijel** [comment]
What file format is that? If Android, it might be bug in translate-toolkit fixed in https://github.com/translate/translate/pull/3210

**Comment by hpatoio** [comment]
Hello. Is an XLIFF.

**Comment by hpatoio** [comment]
Is there a way I can force my installation to use the modified version of `translate` library ? I check out the version linked about and then where should I put it ?

**Comment by hpatoio** [comment]
Well. I've realized that string are escaped when they are saved but then are "converted" when read.
