### ISSUE TITLE
Fulltext search is not working

### ISSUE THREAD

**Issue by hpatoio** [nijel/weblate#740]
I can't find out what's wrong with fulltext search. I run many time `./manage.py rebuild_index --all` and `./manage.py update_index --all` many times but if I select `Fulltext` in the search dropdown I can't find strings that I find if I select `Substring`.
What can be wrong ?

**Comment by nijel** [comment]
What whoosh version do you use?

**Comment by hpatoio** [comment]
How do I find it ?

**Comment by nijel** [comment]
it's shown on about page or ```./manage.py list_versions```

**Comment by hpatoio** [comment]
Here we go. I've update Weblate yesterday. Then I only run the migrations.

```
 * Weblate weblate-2.2-655-gde771e2
 * Python 2.7.5
 * Django 1.8.1
 * python-social-auth 0.2.9
 * Translate Toolkit 1.12.0
 * Whoosh 2.7.0
 * Git 1.8.3.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.4.4
 * django-crispy-forms 1.4.0
```

**Comment by nijel** [comment]
That's the latest one, I've not yet used it in production, but it should work. You can try completely rebuilding the indices by ``./manage.py rebuild_index --all --clean``

**Comment by hpatoio** [comment]
No. No way. How do I check if the index has been build correctly and what's inside ?

**Comment by nijel** [comment]
Anyway this is most likely same as #702
