### ISSUE TITLE
Licensing and source of JavaScript files

### ISSUE THREAD

**Issue by joshuagay** [nijel/weblate#741]
It would be good if corresponding source to minified JS files were made available alongside the minified JS files. If this were done then you could pretty easily update the license statement of each of the JS files to make the site [compatible with LibreJS](https://www.gnu.org/software/librejs/free-your-javascript.html). Also, weblate is very cool, so thank you!

**Comment by nijel** [comment]
With #821 there is no need to ship minified JS files at all.

**Comment by nijel** [comment]
Okay, the sources are now there. As for the LibreJS compatibility, it was not clear to me how to implement it easily, so I skipped that part. Anyway patches are welcome (I think the license table would fit to about page).
