### ISSUE TITLE
can not add monolingual gettext subproject

### ISSUE THREAD

**Issue by ralphvanetten** [nijel/weblate#745]
I am trying monolingual gettext and when I add such a subproject it gives conflicting errors:

I've set **file format** to `Gettext PO file (monolingual)` and provided a **Monolingual base language file:**
It then gives the error message `You can not base file with bilingual translation!` which is IMHO incorrect because I have selected `Gettext PO file (monolingual)`. 

If I leave **Monolingual base language file:** empty, I get the error `You can not use monolingual translation without base file!` which is IMHO correct.

I am testing it with the latest master of weblate 2.3

**Comment by nijel** [comment]
You are using .pot file as base file, right? It's prohibited as of 3a13f61a, but in case you are really using it this way, I'd like to know more about your setup.

**Comment by ralphvanetten** [comment]
Ah, yes, not allowing a .pot file would make sense...

**Comment by nijel** [comment]
I've clarified the error message to say the actual problem.
