### ISSUE TITLE
how to add a subproject?

### ISSUE THREAD

**Issue by CristianGheonea** [nijel/weblate#748]
Hi there,

I did not find any forum so i will ask here.
How do i add a project if the source translation is in github?
This is the full address:
https://github.com/CristianGheonea/IPTV-Professional-Edition-Translation/blob/master/english.php
The documentation does not help at all!
I don't understand almost anything.
I look in google images for examples but i did found some old screen shots of old versions.
Many things changed since then..

**Comment by nijel** [comment]
You can add translation projects and components in admin interface, see https://docs.weblate.org/en/latest/admin/projects.html

**Comment by CristianGheonea** [comment]
Yes sir, i flllow the the documentation examples and instructions. It simply does not help.

I follow this tutorial to install weblate as the tutorial from the page did not help!
http://blog.jedf.com/2013/08/installing-weblate-from-sources-on_26.html
unfortunately, i can not find a tutorial to add a subproject with the source in github
I also try to add a project without github, still, no success.

**Comment by CristianGheonea** [comment]
can you post some screen shots of a model of subproject using github and local source or so?

**Comment by CristianGheonea** [comment]
I think i am close,
i set this:
Component name: iptv-pro
URL slug: iptv-pro
Project: Xtream-Codes IPTV
Version control system: GIT
Source code repository: https://github.com/CristianGheonea/IPTV-Professional-Edition-Translation
Repository push URL: https://github.com/CristianGheonea/IPTV-Professional-Edition-Translation/blob/%(branch)s/%(file)s#L%(line)s
Repository browser: https://github.com/CristianGheonea/IPTV-Professional-Edition-Translation
File mask: *.php
Edit base file: Checked
Base file for new translations: english.php
File format: PHP strings

Error messages:
Please correct the error below.
The mask did not match any files!

Where do i do wrong?

**Comment by CristianGheonea** [comment]
ok,
i add the ssh format at the source:
Source code repository: git@github.com:CristianGheonea/IPTV-Professional-Edition-Translation.git
the file english.php is found, still this error message comes up:
Format of 1 matched files could not be recognized. english.php

I use inside the php file multiple arrays with string keys.
is it possible that because of this the language file can't be added?
Is there a log i can get for you?

**Comment by CristianGheonea** [comment]
this is the error log of apache:
[Tue Jun 02 18:07:13 2015] [error] INFO xtream-codes-iptv/iptv-pro: updating repository
[Tue Jun 02 18:07:13 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: updating repository
[Tue Jun 02 18:07:15 2015] [error] INFO xtream-codes-iptv/iptv-pro: update took 1.97 seconds:
[Tue Jun 02 18:07:15 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: update took 1.97 seconds:
[Tue Jun 02 18:07:15 2015] [error] DEBUG xtream-codes-iptv/iptv-pro: update: Fetching origin
[Tue Jun 02 18:07:15 2015] [error] DEBUG:weblate:xtream-codes-iptv/iptv-pro: update: Fetching origin
[Tue Jun 02 18:07:15 2015] [error] INFO xtream-codes-iptv/iptv-pro: updating repository
[Tue Jun 02 18:07:15 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: updating repository
[Tue Jun 02 18:07:17 2015] [error] INFO xtream-codes-iptv/iptv-pro: update took 1.90 seconds:
[Tue Jun 02 18:07:17 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: update took 1.90 seconds:
[Tue Jun 02 18:07:17 2015] [error] DEBUG xtream-codes-iptv/iptv-pro: update: Fetching origin
[Tue Jun 02 18:07:17 2015] [error] DEBUG:weblate:xtream-codes-iptv/iptv-pro: update: Fetching origin
[Tue Jun 02 18:07:17 2015] [error] INFO xtream-codes-iptv/iptv-pro: merge remote into repo
[Tue Jun 02 18:07:17 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: merge remote into repo
[Tue Jun 02 14:07:18 2015] [error] [client 149.78.229.108] File does not exist: /usr/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/related-widget-wrapper.js, referer: http://translate.xtream-codes.com/admin/trans/subproject/add/?_to_field=id&_popup=1
