### ISSUE TITLE
unable to add a complex php file

### ISSUE THREAD

**Issue by CristianGheonea** [nijel/weblate#749]
Hello there,

According to:
http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/php.html
I should be able to use:
https://github.com/CristianGheonea/IPTV-Professional-Edition-Translation/blob/master/english.php
as main translation file in a sub project.
Unfortunately, every time when i try with different configurations, It fail adding the file and create the subproject.
Mainly, I receive 2 error messages when changing the parameter:
File format:
When i set it to: Automatic Detection, the error "Format of 1 matched files could not be recognized. english.php" pops up.

The error messages in apache2 error.log are:
[Wed Jun 03 05:05:48 2015] [error] INFO xtream-codes-iptv/iptv-pro: updating repository
[Wed Jun 03 05:05:48 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: updating repository
[Wed Jun 03 05:05:50 2015] [error] INFO xtream-codes-iptv/iptv-pro: update took 2.10 seconds:
[Wed Jun 03 05:05:50 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: update took 2.10 seconds:
[Wed Jun 03 05:05:50 2015] [error] DEBUG xtream-codes-iptv/iptv-pro: update: Fetching origin
[Wed Jun 03 05:05:50 2015] [error] DEBUG:weblate:xtream-codes-iptv/iptv-pro: update: Fetching origin
[Wed Jun 03 05:05:50 2015] [error] INFO xtream-codes-iptv/iptv-pro: updating repository
[Wed Jun 03 05:05:50 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: updating repository
[Wed Jun 03 05:05:52 2015] [error] INFO xtream-codes-iptv/iptv-pro: update took 1.87 seconds:
[Wed Jun 03 05:05:52 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: update took 1.87 seconds:
[Wed Jun 03 05:05:52 2015] [error] DEBUG xtream-codes-iptv/iptv-pro: update: Fetching origin
[Wed Jun 03 05:05:52 2015] [error] DEBUG:weblate:xtream-codes-iptv/iptv-pro: update: Fetching origin
[Wed Jun 03 05:05:52 2015] [error] INFO xtream-codes-iptv/iptv-pro: merge remote into repo
[Wed Jun 03 05:05:52 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: merge remote into repo
[Wed Jun 03 01:05:53 2015] [error] [client 80.246.130.135] File does not exist: /usr/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/related-widget-wrapper.js, referer: http://translate.xtream-codes.com/admin/trans/subproject/add/

when i set it to: "PHP strings" the error message i see in the web is:
"Chosen file format does not support adding new translations as chosen in project settings."
The error message i see in apache2 error.log is:
[Wed Jun 03 05:07:24 2015] [error] INFO xtream-codes-iptv/iptv-pro: updating repository
[Wed Jun 03 05:07:24 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: updating repository
[Wed Jun 03 05:07:26 2015] [error] INFO xtream-codes-iptv/iptv-pro: update took 2.46 seconds:
[Wed Jun 03 05:07:26 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: update took 2.46 seconds:
[Wed Jun 03 05:07:26 2015] [error] DEBUG xtream-codes-iptv/iptv-pro: update: Fetching origin
[Wed Jun 03 05:07:26 2015] [error] DEBUG:weblate:xtream-codes-iptv/iptv-pro: update: Fetching origin
[Wed Jun 03 05:07:26 2015] [error] INFO xtream-codes-iptv/iptv-pro: updating repository
[Wed Jun 03 05:07:26 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: updating repository
[Wed Jun 03 05:07:28 2015] [error] INFO xtream-codes-iptv/iptv-pro: update took 1.86 seconds:
[Wed Jun 03 05:07:28 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: update took 1.86 seconds:
[Wed Jun 03 05:07:28 2015] [error] DEBUG xtream-codes-iptv/iptv-pro: update: Fetching origin
[Wed Jun 03 05:07:28 2015] [error] DEBUG:weblate:xtream-codes-iptv/iptv-pro: update: Fetching origin
[Wed Jun 03 05:07:28 2015] [error] INFO xtream-codes-iptv/iptv-pro: merge remote into repo
[Wed Jun 03 05:07:28 2015] [error] INFO:weblate:xtream-codes-iptv/iptv-pro: merge remote into repo
[Wed Jun 03 05:07:28 2015] [error] ERROR:root:Duplicate key $_LANG->'edit_bouquet' in :413, first occurrence in line 406
[Wed Jun 03 05:07:28 2015] [error] ERROR:root:Duplicate key $_LANG->'delete_bouquet' in :414, first occurrence in line 412
[Wed Jun 03 05:07:28 2015] [error] ERROR:root:Duplicate key $_LANG->'manage_packages' in :530, first occurrence in line 211
[Wed Jun 03 05:07:28 2015] [error] ERROR:root:Duplicate key $_LANG->'connections' in :555, first occurrence in line 341
[Wed Jun 03 05:07:28 2015] [error] ERROR:root:Duplicate key $_LANG->'stream_name' in :628, first occurrence in line 197
[Wed Jun 03 05:07:28 2015] [error] ERROR:root:Duplicate key $_LANG->'notes' in :630, first occurrence in line 545
[Wed Jun 03 05:07:28 2015] [error] ERROR:root:Duplicate key $_LANG->'edit_epg' in :637, first occurrence in line 235
[Wed Jun 03 05:07:28 2015] [error] ERROR:root:Duplicate key $_LANG->'connections' in :679, first occurrence in line 341
[Wed Jun 03 05:07:28 2015] [error] ERROR:root:Duplicate key $_LANG->'cast' in :726, first occurrence in line 716
[Wed Jun 03 05:07:28 2015] [error] ERROR:root:Duplicate key $_LANG->'edit_user' in :765, first occurrence in line 466
[Wed Jun 03 05:07:28 2015] [error] ERROR:root:Duplicate key $_LANG->'group_exists' in :801, first occurrence in line 100
[Wed Jun 03 05:07:28 2015] [error] ERROR:root:Duplicate key $_LANG->'user_kicked' in :815, first occurrence in line 654
[Wed Jun 03 05:07:28 2015] [error] ERROR:root:Duplicate key $_LANG->'connection_killed' in :821, first occurrence in line 770
[Wed Jun 03 05:07:28 2015] [error] ERROR:root:Duplicate key $_LANG->'remove_argument' in :922, first occurrence in line 364
[Wed Jun 03 01:07:29 2015] [error] [client 80.246.130.135] File does not exist: /usr/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/related-widget-wrapper.js, referer: http://translate.xtream-codes.com/admin/trans/subproject/add/
[Wed Jun 03 01:07:29 2015] [error] [client 80.246.130.135] File does not exist: /usr/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/related-widget-wrapper.js, referer: http://translate.xtream-codes.com/admin/trans/subproject/add/

Indeed, there are duplicates... Still, this should not be a problem, right?

**Comment by nijel** [comment]
Weblate currently does not support automatically adding new translation for PHP file format, you need to chose manual action there.
