### ISSUE TITLE
failed openshift install with postgres enabled

### ISSUE THREAD

**Issue by dekoza** [nijel/weblate#753]
I followed the steps outlined [in documentation](http://docs.weblate.org/en/latest/admin/install.html#openshift) but I got error during initialization on step
```
Executing 'python ~/app-root/runtime/repo//openshift/manage.py migrate --noinput'
Installation failed!
```
When I ran the last command via `rhc -aweblate ssh  'python ~/app-root/runtime/repo//openshift/manage.py migrate --noinput'` I got this:

```
File "/var/lib/openshift/55754d4f4382ecf589000030/python/virtenv/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 204, in init_connection_state
    cursor.execute(self.ops.set_time_zone_sql(), [tz])
django.db.utils.ProgrammingError: syntax error at or near "NULL"
LINE 1: SET TIME ZONE NULL
                      ^
```

**Comment by dekoza** [comment]
[Possible culprit](https://github.com/nijel/weblate/blob/master/weblate/settings_openshift.py#L72)

**Comment by nijel** [comment]
Indeed the setting sounds wrong. @dtschan was there some particular reason for setting None here?

**Comment by dtschan** [comment]
Yes, this is supposed to let Django use the system timezone: https://docs.djangoproject.com/en/1.8/ref/settings/#time-zone.  Timezone on OpenShift varies depending on where your application is running.

**Comment by nijel** [comment]
Looking at Django code, the postgresql backend does not deal with this situation at all - it does not attempt to do any automatic detection, it just uses the value from settings...

**Comment by dtschan** [comment]
Maybe setting TIME_ZONE to 'UTC' is the better option. Considering you can easily migrate an OpenShift app between time zones. However I'm not sure if times will still be displayed correctly with this setting and can't check right now.

**Comment by nijel** [comment]
Anyway Weblate does display relative times in the web UI, so it really should not matter that much. It would probably just influence which timezone is stored in the database and exported in JSON/RSS feeds...
