### ISSUE TITLE
ACL on guests for accessing a project doesn't work

### ISSUE THREAD

**Issue by daniele-athome** [nijel/weblate#758]
I have added a project-specific permission to give access to anonymous users (the guests group), but it doesn't work: not logged users still hasn't access to the project. Can I make it visible read-only to guests via ACL?

**Comment by nijel** [comment]
It was supposed to work this way, but probably nobody tried it to use it in this way (extending privileges to anonymous users).

**Comment by nijel** [comment]
Fixed in git, thanks for spotting.

**Comment by daniele-athome** [comment]
Just tested. Thank you for fixing!
