### ISSUE TITLE
Filemask parsing gets confused because it looks for more than 2 char language codes

### ISSUE THREAD

**Issue by emmapeel2** [nijel/weblate#760]
I am trying to import the files for the Tails website, done with ikiwiki, and the structure of the pages gives errors when checking for translations.
Typical examples of the problem can be found while in this directory for example:
https://git-tails.immerda.ch/tails/tree/wiki/src/security

For example on that folder the importer will die when finding two files like
wiki/src/security/Numerous_security_holes_in_1.2.2.ca.po 
wiki/src/security/Numerous_security_holes_in_1.2.ca.po

and if trying to save the last component through the django admin interface, it will not allow me to do so.

Maybe the language code can just look for 2 alphabetic characters for this not to happen?

Other problematic files are 
first_steps.fr.po	
first_steps.index.de.po
first_steps.index.fr.po
first_steps.index.mdwn
first_steps.index.pt.po
first_steps.mdwn
first_steps.pt.po
and similar. you can browse the file tree at:
https://git-tails.immerda.ch/tails/tree/wiki/src/doc

and clone the wiki with git clone https://git-tails.immerda.ch/tails

thanks!

**Comment by nijel** [comment]
I don't see simple limitation which would fit all, for example see: https://github.com/moneymanagerex/moneymanagerex/tree/master/po

**Comment by emmapeel2** [comment]
maybe adding an option to limit the lang code?

**Comment by nijel** [comment]
How are you actually trying to import the po files? By [import_project](https://docs.weblate.org/en/latest/admin/management.html#django-admin-import_project)?

**Comment by emmapeel2** [comment]
I am importing them with the import command, yes.

I had a look at it but the parsing expression was a bit too much for me
(blush)

**Comment by emmapeel2** [comment]
I forgot to mention I am also having issues to save through the admin
interface afterwards, for example when I try to save

  wiki/src/security/Numerous_security_holes_in_1.2.fr.po

from the example, I get an error telling me to fix the file mask and I
cannot save it (after importing with the command import_project)
although I can edit and save

  wiki/src/security/Numerous_security_holes_in_1.2.2.fr.po

without problems

**Comment by nijel** [comment]
I've added new option --component-regexp to customize matching. This allowed me to import your translations fine. Example is part of the docs as well: https://docs.weblate.org/en/latest/admin/management.html#django-admin-import_project

**Comment by emmapeel2** [comment]
thanks!
