### ISSUE TITLE
Allowed username and rights

### ISSUE THREAD

**Issue by Mikanoshi** [nijel/weblate#761]
I found out today that one of the users changed and added translations, but he is a member of Users group which only have rights to add suggestions. I also couldn't save his profile in Django admin because he somehow managed to write Username in Chinese. User was registered 2015-03-11 using email auth.

**Comment by nijel** [comment]
Can you check what permissions does the user/group have? Also when did it happen and what version do you use? The permission handling was not consistent in some places before 1d86bf8eb11b05b6fba5ea07a479cd014fb874b0.

**Comment by nijel** [comment]
Just tried to reproduce this with current master and I failed - user in Users group, removing "Can save translation" permission and I failed to edit translation in any way from the restricted account...

**Comment by Mikanoshi** [comment]
Translations were made on June 7, last pulled commit is https://github.com/nijel/weblate/commit/884c3acd19264c97fe2f691ca294a007289533d7
Can't tell what commit was on 7, but most likely not the one from 2 months ago, I update weblate regularly.

Permissions:
![screen](https://cloud.githubusercontent.com/assets/5113439/8230204/8649d716-15d7-11e5-81e1-ce7898fb2f55.png)
What is that last permission for?
These are the translations of that user:
http://l10n.sensetoolbox.com/changes/?page=4&lang=zh_TW&project=sense-6-toolbox&subproject=s6t

**Comment by nijel** [comment]
So there is the "Can save translation" privilege, so he is supposed to be able to translate...

**Comment by Mikanoshi** [comment]
What's the difference then between this unit-save and translation-add/translation-change?

**Comment by nijel** [comment]
These are generic Django permissions and they limit only what you can do in admin interface. For Weblate all permissions are documented here: https://docs.weblate.org/en/latest/admin/auth.html#extra-privileges

**Comment by Mikanoshi** [comment]
So add/change translation permissions don't do anything, because I don't have Translations in admin anymore and have to manually disable them in database... Anyway, bug with username is legit, it was 泰祥 陳.
