### ISSUE TITLE
Newline marker (↵) can be copied into translations

### ISSUE THREAD

**Issue by chrysn** [nijel/weblate#764]
I have observed that funny characters (↵, "downwards arrow with corner leftwards") occasionally show up in translations before newlines. After ruling out that they are just a funny way of diff to indicate a newline character, I found that the weblate translation list uses them to visually indicate newlines in translations (for example, see [the ARandR translation for errors](https://hosted.weblate.org/projects/arandr/translations/de/translate/?q=xrandr&search=ftx&source=on&target=on&type=all&ignored=False)).

While copying the character over is a mistake made by the translator, I'd like to suggest that weblate take precautions against that, given that it is targeted towards translators who don't need a firm understanding of control characters to contribute.

One way this could be prevented is by inserting the character not into the HTML, but using CSS like `.nl:before { content: "\21b5"; }`. Such text (at least in the Epiphany browser) does not get copied in the clipboard.

**Comment by nijel** [comment]
Thanks for pointing me into this, I've never realized that there might be way to display text without making it copied. This is definitely worth testing in more browsing and implementing in case it works.

**Comment by chrysn** [comment]
just tested this with firefox and chromium -- they don't include the :before content when copying plain text either.

**Comment by nijel** [comment]
Thanks for suggestion, it indeed seems to work fine!
