### ISSUE TITLE
The language filter for importe files into weblate for translation

### ISSUE THREAD

**Issue by collex100** [nijel/weblate#765]
The language filter, when imported into weblate files for translation.

For example: in the application there are 20 languages, but we need to translate only one (import only one language for translation). 
When you import, point that you need to take from the list file to translate only file for Russian translation.

Is it possible to make such a function?

Thanks!

**Comment by nijel** [comment]
This is currently not possible, but might be implemented in future.

**Comment by nijel** [comment]
Implemented in 95cb8009, see #786.

**Comment by collex100** [comment]
It is awesome! Just perfect!  I am very grateful to you for your work! Thanks you very much!

**Comment by collex100** [comment]
./manage.py import_project nameproject git@github.com:name1/name2.git  master 'addons/**/i18n/*.po'
how can I use this command (which is above) for language filter (ru):
^[^.]+$

Thanks!

**Comment by nijel** [comment]
The import_project doesn't support this yet (feel free to open separate issue for that).
