### ISSUE TITLE
Hosted Weblate: Automatic pull requests to GitHub

### ISSUE THREAD

**Issue by SecUpwN** [nijel/weblate#767]
Good morning @nijel, first of all **HUGE THANKS** for [hosting](https://hosted.weblate.org/projects/aimsicd/strings/) our [Android IMSI-Catcher Detector](https://secupwn.github.io/Android-IMSI-Catcher-Detector/)! :+1:

Since it now seems that translations keep traveling in slowly but steadily, I would like to enable Weblate to automatically craft a pull request once a new translation has been finished. I already found the guide:

* [Pushing changes to GitHub as pull request](https://docs.weblate.org/en/latest/admin/continuous.html?highlight=pull%20request#pushing-changes-to-github-as-pull-request)

But this confuses me: `You need to configure the hub command line tool and set GITHUB_USERNAME for this to work.` How to enable automatic pull requests via the *hosted* weblate? Please guide me.

**Update 1:** This hint [on your site](https://weblate.org/en/hosting/) tells: `If you want Weblate to automatically push changes as well, add Weblate push user to collaborators and let us know you want to use this option. See documentation for more detailed instructions. ` - please add & **highlight** this in your documentation!

**Update 2:** Now *found* the cause! @nijel, please enable *pushing* from our hosted repo. Thanks!

**Comment by nijel** [comment]
Enabled, you now have first commits there: https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commits/development

**Comment by SecUpwN** [comment]
Thank you, @nijel! You've done a great job.
