### ISSUE TITLE
Add and delete entries

### ISSUE THREAD

**Issue by hpatoio** [nijel/weblate#768]
Hello. Is there a reason why translators cannot add and delete entries ? 

The tool that I use to extract the keys from the code doesn't find all the entries (for technical restriction) so would be nice if translators could add/delete keys.

**Comment by nijel** [comment]
Yes, the reason is that you are the first project who would like to have it this way :-). Isn't actually better to fix the key extraction than allowing translators to add/delete keys without any limitations?

**Comment by hpatoio** [comment]
The system to extract the keys from the code can't find all the keys (it's s Symfony2 project) It's a known limitation and for some case there is no solution.

That's why would be nice in my opinion if translators (maybe this feature can be enabled depending on the role the user has) could add entries. 

Delete is somehow related to this.

**Comment by nijel** [comment]
I still think Weblate is not best place to handle this as you can't do this without looking at the source code (to figure out missing strings). Also it sounds like a bug in key extraction and it should be fixed there rather than implementing workarounds in other tools.
