### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by whedro** [nijel/weblate#769]
Hi, 

I can't create subproject .... In syslog I have message below

Error:

Internal Server Error: /admin/trans/subproject/13/
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 616, in wrapper
return self.admin_site.admin_view(view)(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 233, in inner
return view(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1519, in change_view
return self.changeform_view(request, object_id, form_url, extra_context)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 34, in _wrapper
return bound_func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 30, in bound_func
return func.__get__(self, type(self))(*args2, **kwargs2)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 145, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1467, in changeform_view
self.save_model(request, new_object, form, not add)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1078, in save_model
obj.save()
File "/opt/weblate/weblate/trans/models/subproject.py", line 1283, in save

File "/opt/weblate/weblate/trans/models/subproject.py", line 930, in create_translations
self, lang, code, path, force, request=request
File "/opt/weblate/weblate/trans/models/translation.py", line 68, in check_sync
translation.check_sync(force, request=request)
File "/opt/weblate/weblate/trans/models/translation.py", line 470, in check_sync
if self.revision != self.get_git_blob_hash():
File "/opt/weblate/weblate/trans/models/translation.py", line 589, in get_git_blob_hash
ret = self.repository.get_object_hash(self.get_filename())
File "/opt/weblate/weblate/trans/vcs.py", line 558, in get_object_hash
return self.execute(['ls-tree', 'HEAD', real_path]).split()[2]
IndexError: list index out of range

Request repr(): 
<WSGIRequest
path:/admin/trans/subproject/13/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'allow_translation_propagation': [u'on'], u'report_source_bugs': [u''], u'enable_suggestions': [u'on'], u'new_lang': [u'add'], u'filemask': [u'app/Resources/translations/client.*.po'], u'pre_commit_script': [u''], u'extra_commit_file': [u''], u'_save': [u'Ulo\u017ei\u0165'], u'committer_email': [u'.................'], u'git_export': [u''], u'file_format': [u'po-mono'], u'vcs': [u'git'], u'branch': [u'development'], u'commit_message': [u'Translated using Weblate (%(language_name)s)\r\n\r\nCurrently translated at %(translated_percent)s%% (%(translated)s of %(total)s strings)'], u'csrfmiddlewaretoken': [u'..................'], u'post_update_script': [u''], u'new_base': [u'app/Resources/translations/client.pot'], u'template': [u'app/Resources/translations/client.sk.po'], u'save_history': [u'on'], u'agreement': [u''], u'repo': [u'http://...................../web.git'], u'slug': [u'client'], u'name': [u'Client'], u'license': [u''], u'repoweb': [u'http://...................../app/Resources/translations/%(file)s?at=refs/heads/%(branch)s'], u'suggestion_autoaccept': [u'0'], u'project': [u'1'], u'license_url': [u''], u'merge_style': [u'merge'], u'push': [u'http://...................../web.git'], u'committer_name': [u'Weblate'], u'check_flags': [u'']}>,
COOKIES:{'csrftoken': '.........................',
'sessionid': '.................................'},
META:{'CONTENT_LENGTH': '3849',
'CONTENT_TYPE': 'multipart/form-data; boundary=---------------------------4257182931351',
'CONTEXT_DOCUMENT_ROOT': '/opt/weblate/weblate/media/',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': u'.............................',
'DOCUMENT_ROOT': '/opt/weblate/weblate/media/',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HOME': '/var/opt/weblate',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
'HTTP_CACHE_CONTROL': 'max-age=259200',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': 'csrftoken=....................; sessionid=.........................',
'HTTP_DNT': '1',
'HTTP_HOST': 'weblate..........',
'HTTP_REFERER': 'http://...................../admin/trans/subproject/13/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0',
'PATH_INFO': u'/admin/trans/subproject/13/',
'PATH_TRANSLATED': '/opt/weblate/weblate/wsgi.py/admin/trans/subproject/13/',
'QUERY_STRING': '',
'REMOTE_ADDR': '.........',
'REMOTE_PORT': '53049',
'REQUEST_METHOD': 'POST',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/admin/trans/subproject/13/',
'SCRIPT_FILENAME': '/opt/weblate/weblate/wsgi.py',
'SCRIPT_NAME': u'',
'SERVER_ADDR': '37.205.11.109',
'SERVER_ADMIN': '.....................',
'SERVER_NAME': '.....................',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '<address>Apache/2.4.7 (Ubuntu) Server at ..................... Port 80</address>\n',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': '.....................|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'weblate',
'mod_wsgi.queue_start': '1436348222277319',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f2cbc10c4f0>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f2cbc594a80>,
'wsgi.input': <mod_wsgi.Input object at 0x7f2cbcd31370>,
'wsgi.multiprocess': True,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>

Language: None
User: u'.....................'

Versions:
* Weblate weblate-2.3-319-g7ddc406
* Python 2.7.6
* Django 1.8
* python-social-auth 0.2.7
* Translate Toolkit 1.12.0
* Whoosh 2.7.0
* Git 1.9.1
* Pillow (PIL) 1.1.7
* dateutil 1.5
* lxml 3.3.3
* django-crispy-forms 1.4.0
* pyuca N/A
* pyLibravatar N/A
* Mercurial 2.8.2

Maybe I do something wrong ... but before I create without any problem ...
What I doing wrong ?

Thanks, 

best regards,
Whedro

**Comment by nijel** [comment]
I see you're changing existing translation component, what all have you changed?

**Comment by whedro** [comment]
Hi, at first I setting repository and default maskSave.. it was okThen I create .pot file a setting owner weblate:weblateAfter that, I change in component fields about default translate file‎, template and type translate file.Saving finished with error message, that no found files by mask.I create file client.de.po a tried to save again.This step finish with "monkey error"‎ .. :)And in log was message what o sent before..Thank,M.                                                                                                                                                                                                                                                                                                                                        Odesláno ze smartphonu se systémem BlackBerry 10.                                                                                                                                                                                                                Od: Michal ČihařOdesláno: streda, 8. júla 2015 12:22Komu: nijel/weblateOdpovědět: nijel/weblateKopie: whedroPředmět: Re: [weblate] IndexError: list index out of range (#769)I see you're changing existing translation component, what all have you changed?

—Reply to this email directly or view it on GitHub.

**Comment by nijel** [comment]
Ah, these files are not yet committed to Git, right? Then this is something Weblate can not handle. It's usually not a good idea to manipulate with the repository which Weblate uses, better do these changes upstream and let Weblate pull these changes.
