### ISSUE TITLE
[Bitbucket] POST changed to Webhooks

### ISSUE THREAD

**Issue by Rvanlaak** [nijel/weblate#771]
I've succesfully integrated Weblate with my Bitbucket repo, 

https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-bitbucket

But, Weblate does not seem to support the new Webhooks:

https://confluence.atlassian.com/display/BITBUCKET/Manage+Webhooks;jsessionid=D54B2DFCBAD15425D4E4511045ACF686.node2

**Comment by nijel** [comment]
It should work just fine with that, just enable sending push events there.

Or do you get some error in the logs?

**Comment by Rvanlaak** [comment]
I think it has to do something with how my components are configured right now. We have > 10 translation domains, that probably all have to be their own component. This means there are that same number of repos if I'm right?

**Comment by nijel** [comment]
Ah, now I see the difference .... but you can still use POST service, which will work. The new webhooks are indeed not supported right now.

**Comment by Rvanlaak** [comment]
The problem is that it is not possible anymore to add POST services, only webhooks can be added. So existing POST services will keep working, but new users are screwed :+1:

**Comment by nijel** [comment]
It's still possible to add them right now (at least it works for me), there is just warning that it will not be possible in future.

Anyway I've just added needed support for new webhooks to Weblate.

**Comment by Rvanlaak** [comment]
Incredible fast response! Think I'm going to make my weblate installation a git fork, instead of installing it via the tarball :+1: Will this result in database inconsistencies? Or is the database api really stable?

**Comment by nijel** [comment]
All database changes are handled by Django migrations, that will work just fine.
