### ISSUE TITLE
[Project] Watch for new components

### ISSUE THREAD

**Issue by Rvanlaak** [nijel/weblate#773]
The separation of components within a project is great. In combination with the `manage.py` tool we can import all components from our translation directory `app/Resources/translations/**.*.xliff`.

I see the `import_project` command reuses the vcs clone of the first component for the other components. But, what if new components are added, by adding a new `.xliff` file? Would be great if weblate is able to re-scan the `/translations` directory for new components, or always keep them in sync when the `git pull` action is executed.

**Comment by nijel** [comment]
If that's what you meant, you can use  weblate://<project>/<existing-component> to share VCS repo when running import_project. See https://docs.weblate.org/en/latest/admin/management.html?highlight=import_project#django-admin-import_project
