### ISSUE TITLE
Error with .xlf Files

### ISSUE THREAD

**Issue by werkraum-admin** [nijel/weblate#780]
Environment:

Request Method: POST

Django Version: 1.8.2
Python Version: 2.7.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.sitemaps',
 'social.apps.django_app.default',
 'crispy_forms',
 'weblate.trans',
 'weblate.lang',
 'weblate.accounts',
 'weblate')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
 'weblate.accounts.middleware.RequireLoginMiddleware')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/weblate/weblate/trans/views/edit.py" in translate
  524.                 this_unit_url, next_unit_url
File "/opt/weblate/weblate/trans/views/edit.py" in handle_translate
  309.         go_next = perform_translation(unit, form, request)
File "/opt/weblate/weblate/trans/views/edit.py" in perform_translation
  236.         form.cleaned_data['fuzzy']
File "/opt/weblate/weblate/trans/models/unit.py" in translate
  988.         saved = self.save_backend(request)
File "/opt/weblate/weblate/trans/models/unit.py" in save_backend
  540.             (saved, pounit) = self.translation.update_unit(self, request, user)
File "/opt/weblate/weblate/trans/models/translation.py" in update_unit
  849.             pounit, add = self.store.find_unit(unit.context, src)
File "/opt/weblate/weblate/trans/formats.py" in find_unit
  525.             return self._find_unit_template(context)
File "/opt/weblate/weblate/trans/formats.py" in _find_unit_template
  482.                     'Could not find template unit for new unit!'

Exception Value: Could not find template unit for new unit!

And i have the problem that provided language Files with predefined source arent shown at all in weblate. The Id and amount of translations is correct but the sources is empty.

**Comment by nijel** [comment]
Maybe your base files do not match the translated ones? Can you make them available so that I can take deeper look?
