### ISSUE TITLE
Overview: New translation: Disable New translation for Qt

### ISSUE THREAD

**Issue by GreenLunar** [nijel/weblate#783]
Replace the current *Start new translation* box with a message that says that creation of QT TS files is possible only from originate version control repository.

Please also add an explanation to why it is not yet possible, and add a link where contributors can fix this problem.

**Comment by nijel** [comment]
Currently it sends mail with request to owner of the project (what in case of PSI is you). Did you get these?

Anyway the wording on the page should be more clear indeed.

**Comment by GreenLunar** [comment]
May you please set Justin as the owner of the project, or is it possible to change owners via Weblate?

**Comment by GreenLunar** [comment]
> Did you get these?

Yes, otherwise I would not have known about it.

**Comment by nijel** [comment]
It's not (yet) possible to change owner for you (see #719 and #720), what's his username?

**Comment by GreenLunar** [comment]
*jkarneges*

**Comment by nijel** [comment]
I don't see him in Weblate....

**Comment by GreenLunar** [comment]
That is his username at GitHub.  Should I ask him to login to Weblate using GitHub?

**Comment by nijel** [comment]
Yes, I need somebody with Weblate login who will take care of possible problems (merge failures or new language requests).

**Comment by GreenLunar** [comment]
@jkarneges please ask, whenever you want, to take over the administration of Psi @ Weblate.
