### ISSUE TITLE
Disable weblate generating new language

### ISSUE THREAD

**Issue by exzhawk** [nijel/weblate#786]
I have delete all languages other than en_US and zh_CN in django admin panel.
But when i create a new component from git repo which contains en_US.po, zh_CN.po, de_DE.po, weblate auto generate a language "de_DE".
Is it possible to disable this feature?
I've looked up the documentation but can not find a config to do so.

**Comment by nijel** [comment]
Currently there is no way to avoid this, Weblate scans for new translations on every repository update.

**Comment by nijel** [comment]
This could be solved by adding regexp mask to component configuration to filter languages.

**Comment by exzhawk** [comment]
I can't find the "regexp mask" in component configuration page.

**Comment by nijel** [comment]
It's feature to be implemented :-).

**Comment by exzhawk** [comment]
I created a asdf.po file but weblate didn't generate a new language called "asdf".
So the de_DE(generated) is based on a language list but not the one in django admin panel.
It seems possible to delete this "language list" to disable generated language. Maybe it's a ttkit side thing?
