### ISSUE TITLE
[Monolingual] Remove translation units after they are removed from source

### ISSUE THREAD

**Issue by Rvanlaak** [nijel/weblate#788]
In case a translation has been removed from the source language (eg. English) then the translation keys also should be removed from all other languages.

Would be great if there was a special synchronize command for that, so the related changes could be pushed in one commit. That would allow the developer to do this upfront, before the translator will start working on all new keys.

Based this on the fact new keys are added according to the FAQ: https://docs.weblate.org/en/latest/faq.html#does-weblate-update-translation-files-besides-translations

**Comment by nijel** [comment]
It should work like this - once the monolingual base file changes, it's scanned and translatable units are updated. It's not working like that for you? See also https://docs.weblate.org/en/latest/admin/projects.html#monolingual-components
