### ISSUE TITLE
Improve support for script hooks

### ISSUE THREAD

**Issue by exzhawk** [nijel/weblate#790]
I'm trying to use weblate on a project, which use a non-standard language file format. Though it's kind of similar with known format, weblate failed to recognize some strings of the file.
So is it possible to add/replace a new language file format? If possible, what interface should I implement? Or should I hack into translate-toolkit side rather than weblate itself?

**Comment by nijel** [comment]
Weblate adds thin layer on top of translate-toolkit, so if the change is in syntax of the files, you would probably better hack translate-toolkit.

Anyway the Weblate wrapper is here (it is there mostly for hiding differences in formats supported by ttkit): https://github.com/nijel/weblate/blob/master/weblate/trans/formats.py

**Comment by exzhawk** [comment]
I'm trying to use POST_UPDATE_SCRIPTS and PRE_COMMIT_SCRIPTS.
In my understanding, I can use POST_UPDATE_SCRIPTS to convert my non-standard file to standard format, so weblate recognize and translate it. Then, before commit&push, use PRE_COMMIT_SCRIPTS to convert file back to original non-standard file. Am I doing it right?
And when trying this approach, I'm having another issue. POST_UPDATE_SCRIPTS seems take no argument, so how can I write a script to processing files matching file mask?

**Comment by nijel** [comment]
Indeed the POST_UPDATE_SCRIPT takes no parameters. I can make Weblate pass some parameters in the environment...

**Comment by exzhawk** [comment]
Then how to use it... Seems the script itself have to find a way to know which file should be processed.
Maybe passing file names like PRE_COMMIT_SCRIPTS or setting a parameter like CURRENT_VCS_ROOT will make it easier to use.

**Comment by nijel** [comment]
The pre pre/post commit script receives filename as a parameter, so that should work right now.

**Comment by nijel** [comment]
I've added support for exporting some properties to environment in 93c4289.

**Comment by nijel** [comment]
See docs for more details: https://docs.weblate.org/en/latest/admin/continuous.html#processing-repository-with-scripts

**Comment by nijel** [comment]
If you want something more to be exported, just let me know.

**Comment by exzhawk** [comment]
POST_UPDATE_SCRIPTS doesn't run when creating a new component.
I think regarding creation of a new component/repo as an update action and applying POST_UPDATE_SCRIPTS is reasonable.

**Comment by exzhawk** [comment]
b99c01fdb99ff5bf85195e12ac6eba8845f30a41 seems not working. Post-update script didn't run on creating component.

**Comment by nijel** [comment]
@exzhawk Can you please open separate bug for that?
