### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'True'

### ISSUE THREAD

**Issue by whedro** [nijel/weblate#791]
Hi, could you help me with this ? (i think, that was start to generate error bellow after update components) ....

Internal Server Error: /translate/resitnow/core/es/ Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/weblate/weblate/trans/views/edit.py", line 524, in translate
    this_unit_url, next_unit_url
  File "/opt/weblate/weblate/trans/views/edit.py", line 283, in handle_translate
    translation.check_sync()
  File "/opt/weblate/weblate/trans/models/translation.py", line 470, in check_sync
    if self.revision != self.get_git_blob_hash():
  File "/opt/weblate/weblate/trans/models/translation.py", line 589, in get_git_blob_hash
    ret = self.repository.get_object_hash(self.get_filename())
  File "/opt/weblate/weblate/trans/models/translation.py", line 568, in repository
    return self.subproject.repository
  File "/opt/weblate/weblate/trans/models/subproject.py", line 551, in repository
    if cache.get(cache_key) is None:
  File "/usr/local/lib/python2.7/dist-packages/django/core/cache/backends/memcached.py", line 84, in get
    val = self._cache.get(key)
  File "/usr/local/lib/python2.7/dist-packages/memcache.py", line 1089, in get
    return self._get('get', key)
  File "/usr/local/lib/python2.7/dist-packages/memcache.py", line 1073, in _get
    return _unsafe_get()
  File "/usr/local/lib/python2.7/dist-packages/memcache.py", line 1061, in _unsafe_get
    value = self._recv_value(server, flags, rlen)
  File "/usr/local/lib/python2.7/dist-packages/memcache.py", line 1235, in _recv_value
    val = int(buf)
ValueError: invalid literal for int() with base 10: 'True'

Request repr(): 
<WSGIRequest
path:/translate/resitnow/core/es/,
GET:<QueryDict: {u'offset': [u'0'], u'sid': [u'b99bf24c-36bc-11e5-9098-7567b63ed167']}>,
POST:<QueryDict: {u'checksum': [u'87c70325ee82485860a3e03612e6a1f2'], u'content': [u''], u'commit_message': [u''], u'csrfmiddlewaretoken': [u'PrNqqMivTUErbBPLhxc5d9vP4604Pi2N'], u'save': [u'Ulo\u017ei\u0165'], u'target_0': [u'Activa']}>,
COOKIES:{'csrftoken': 'PrNqqMivTUErbBPLhxc5d9vP4604Pi2N',
 'django_language': 'sk',
 'sessionid': '0ee1eejrswmulyysowpamrud0b4mkev0'},
META:{'CONTENT_LENGTH': '157',
 'CONTENT_TYPE': 'application/x-www-form-urlencoded',
 'CONTEXT_DOCUMENT_ROOT': '/opt/weblate/weblate/media/',
 'CONTEXT_PREFIX': '',
 u'CSRF_COOKIE': u'PrNqqMivTUErbBPLhxc5d9vP4604Pi2N',
 'DOCUMENT_ROOT': '/opt/weblate/weblate/media/',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HOME': '/var/opt/weblate',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'sk-SK,sk;q=0.8,cs;q=0.6,en-US;q=0.4,en;q=0.2',
 'HTTP_CACHE_CONTROL': 'max-age=0',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'django_language=sk; csrftoken=PrNqqMivTUErbBPLhxc5d9vP4604Pi2N; sessionid=0ee1eejrswmulyysowpamrud0b4mkev0',
 'HTTP_HOST': '<host>',
 'HTTP_HTTPS': '1',
 'HTTP_ORIGIN': '<host>',
 'HTTP_REFERER': '<http refferer>',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36',
 'PATH_INFO': u'/translate/resitnow/core/es/',
 'PATH_TRANSLATED': '/opt/weblate/weblate/wsgi.py/translate/resitnow/core/es/',
 'QUERY_STRING': 'sid=b99bf24c-36bc-11e5-9098-7567b63ed167&offset=0',
 'REMOTE_ADDR': '<remote ip>',
 'REMOTE_PORT': '55441',
 'REQUEST_METHOD': 'POST',
 'REQUEST_SCHEME': 'http',
 'REQUEST_URI': '/translate/resitnow/core/es/?sid=b99bf24c-36bc-11e5-9098-7567b63ed167&offset=0',
 'SCRIPT_FILENAME': '/opt/weblate/weblate/wsgi.py',
 'SCRIPT_NAME': u'',
 'SERVER_ADDR': '<host ip>',
 'SERVER_ADMIN': '......',
 'SERVER_NAME': '<host>',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SIGNATURE': '<address>Apache/2.4.7 (Ubuntu) Server at ...... Port 80</address>\n',
 'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
 'mod_wsgi.application_group': '<host>|',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.enable_sendfile': '0',
 'mod_wsgi.handler_script': '',
 'mod_wsgi.input_chunked': '0',
 'mod_wsgi.listener_host': '',
 'mod_wsgi.listener_port': '80',
 'mod_wsgi.process_group': 'weblate',
 'mod_wsgi.queue_start': '1438261999958999',
 'mod_wsgi.request_handler': 'wsgi-script',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.version': (3, 4),
 'wsgi.errors': <mod_wsgi.Log object at 0x7f70822ed670>,
 'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f708200d738>,
 'wsgi.input': <mod_wsgi.Input object at 0x7f70820d3070>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>

Language: None
User: u'lucia'

Versions:
 * Weblate weblate-2.3-448-g367feaa
 * Python 2.7.6
 * Django 1.8.3
 * python-social-auth 0.2.12
 * Translate Toolkit 1.13.0
 * Whoosh 2.7.0
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.4.4
 * django-crispy-forms 1.4.0
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.4.2

Thanks, 

Best regards
Michal

**Comment by whedro** [comment]
Hi, I read this error one more time and I found problem .. :) .. It's my fault ...
After upgrade memcache.py on new version, it looks like fine...
This is new one:    https://raw.githubusercontent.com/linsomniac/python-memcached/master/memcache.py

Michal

**Comment by nijel** [comment]
Indeed python-memcached 1.56 is broken, 1.57 has fixed this: https://github.com/linsomniac/python-memcached/commit/664bd3e23fe500fbde4c70636e2d24c8fd2f35af
