### ISSUE TITLE
Add tool for generating translator credits

### ISSUE THREAD

**Issue by nijel** [nijel/weblate#798]
As we have all information in Weblate, it might be useful to be able to generate translator credits to be suitable for documentation like http://docs.phpmyadmin.net/en/latest/credits.html#translators

**Comment by paour** [comment]
It would be really nice to make is easily embeddable in web pages, either as an image (like you already do for translation status) or an iframe; or as a format that can be easily parsed and integrated by a bit of Javascript.

**Comment by nijel** [comment]
I'm not sure about this - with current data we have, it will take some time to generate the report. So most likely it will be available for authenticated users only by default.

However it will be definitely available in some machine processable format.
