### ISSUE TITLE
Confusing placement of edit source icon next to context

### ISSUE THREAD

**Issue by l3d00m** [nijel/weblate#799]
Steps to reproduce:  
-Go to translate string view  
-Click on the edit icon next to Context: ...
-Context edit form shows up, but only for a few milliseconds, then gets hidden again

Happens on hosted.weblate.org server (running 2.4-dev)

**Comment by nijel** [comment]
Well, the edit icon is placed confusingly when there is context or comment as well, but it's for editing source strings, not context.

**Comment by l3d00m** [comment]
Thanks for your answer.

**Comment by nijel** [comment]
Reopening for fixing the UI confusion, the placement of edit source icon when context or comment is shown is really unfortunate.
