### ISSUE TITLE
Add XLIFF export [$5]

### ISSUE THREAD

**Issue by nijel** [nijel/weblate#810]
As XLIFF is more or less industry standard, it might be good idea to provide export to it from any format translated in Weblate.

**Comment by Rvanlaak** [comment]
:+1:

**Comment by nijel** [comment]
@Rvanlaak You can also fund the feature on Bountysource ;-).

**Comment by Rvanlaak** [comment]
It seems like it already is supported right? What are you planning to improve? Are these interface / translation flow changes?

**Comment by nijel** [comment]
There is no Xliff export right now. You can only download the translation in the native format (so if you happen to use Xliff you can download it, but not when using something else).

**Comment by rvanlaak** [comment]
Awesome :+1:
