### ISSUE TITLE
Post-update script doesn't run on creating component.

### ISSUE THREAD

**Issue by exzhawk** [nijel/weblate#811]
Tested repo contains simple Java properties files: https://github.com/InfinityStudio/WAILA-Translation-Chinese
Tested script is a simple script just escaping some char and print a message "escape".
Log when adding a component:
[19/Aug/2015 15:01:31]"POST /admin/trans/subproject/ HTTP/1.1" 200 5708
[19/Aug/2015 15:01:33]"POST /admin/trans/subproject/ HTTP/1.1" 302 0
[19/Aug/2015 15:01:34]"GET /admin/trans/subproject/ HTTP/1.1" 200 12748
[19/Aug/2015 15:01:34]"GET /admin/jsi18n/ HTTP/1.1" 200 6834
[19/Aug/2015 15:01:35]"GET /admin/trans/subproject/add/ HTTP/1.1" 200 29525
[19/Aug/2015 15:01:36]"GET /admin/jsi18n/ HTTP/1.1" 200 6834
INFO test/testw13: updating repository
INFO:weblate:test/testw13: updating repository
INFO test/testw13: update took 2.55 seconds:
INFO:weblate:test/testw13: update took 2.55 seconds:
DEBUG test/testw13: update: Fetching origin
DEBUG:weblate:test/testw13: update: Fetching origin
INFO test/testw13: updating repository
INFO:weblate:test/testw13: updating repository
INFO test/testw13: update took 2.21 seconds:
INFO:weblate:test/testw13: update took 2.21 seconds:
DEBUG test/testw13: update: Fetching origin
DEBUG:weblate:test/testw13: update: Fetching origin
INFO test/testw13: merge remote into repo
INFO:weblate:test/testw13: merge remote into repo
INFO test/testw13: updating repository
INFO:weblate:test/testw13: updating repository
INFO test/testw13: update took 2.20 seconds:
INFO:weblate:test/testw13: update took 2.20 seconds:
DEBUG test/testw13: update: Fetching origin
DEBUG:weblate:test/testw13: update: Fetching origin
INFO test/testw13: updating repository
INFO:weblate:test/testw13: updating repository
DEBUG test/testw13: update: Fetching origin
DEBUG:weblate:test/testw13: update: Fetching origin
INFO test/testw13: updating repository
INFO:weblate:test/testw13: updating repository
INFO test/testw13: update took 3.28 seconds:
INFO:weblate:test/testw13: update took 3.28 seconds:
DEBUG test/testw13: update: Fetching origin
DEBUG:weblate:test/testw13: update: Fetching origin
INFO test/testw13: merge remote into repo
INFO:weblate:test/testw13: merge remote into repo
INFO test/testw13: checking zh_CN.lang (zh_CN) [1/1]
INFO:weblate:test/testw13: checking zh_CN.lang (zh_CN) [1/1]
INFO test/testw13/zh_CN: processing zh_CN.lang, revision has changed
INFO:weblate:test/testw13/zh_CN: processing zh_CN.lang, revision has changed
INFO test/testw13: updating completed
INFO:weblate:test/testw13: updating completed
[19/Aug/2015 15:02:49]"POST /admin/trans/subproject/add/ HTTP/1.1" 302 0
[19/Aug/2015 15:02:49]"GET /admin/trans/subproject/ HTTP/1.1" 200 13271

The script DO work when manually click pull button.
Log when clicking pull button:
[19/Aug/2015 16:34:13]"GET /js/git/test/testw13/zh_CN/ HTTP/1.1" 200 2316
INFO test/testw13: updating repository
INFO:weblate:test/testw13: updating repository
INFO test/testw13: update took 2.73 seconds:
INFO:weblate:test/testw13: update took 2.73 seconds:
DEBUG test/testw13: update: Fetching origin
DEBUG:weblate:test/testw13: update: Fetching origin
INFO test/testw13: merge remote into repo
INFO:weblate:test/testw13: merge remote into repo
escape
INFO test/testw13: checking zh_CN.lang (zh_CN) [1/1]
INFO:weblate:test/testw13: checking zh_CN.lang (zh_CN) [1/1]
INFO test/testw13/zh_CN: processing zh_CN.lang, revision has changed
INFO:weblate:test/testw13/zh_CN: processing zh_CN.lang, revision has changed
INFO test/testw13: updating completed
INFO:weblate:test/testw13: updating completed
[19/Aug/2015 16:34:26]"GET /update/test/testw13/zh_CN/ HTTP/1.1" 302 0
[19/Aug/2015 16:34:26]"GET /projects/test/testw13/zh_CN/ HTTP/1.1" 200 30619

The "escape" message is printed by my script intentionally.

Result of `./manage.py list_versions `
 * Weblate weblate-2.3-668-g549dbd0
 * Python 2.7.10
 * Django 1.8.3
 * python-social-auth 0.2.11
 * Translate Toolkit 1.13.0
 * Whoosh 2.7.0
 * Git 2.5.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.4.4
 * django-crispy-forms 1.4.0
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.4.2

**Comment by nijel** [comment]
The problem is that by time the notification can be sent (the object is stored in the database), there are no changes detected in the git repository (it has been cloned/updated before).
