### ISSUE TITLE
first name / full name confusion

### ISSUE THREAD

**Issue by benkovsk** [nijel/weblate#812]
We use weblate (latest git master) with django-auth-ldap, and pull first name, last name and email from LDAP on user login. All auth backends except of django_auth_ldap.backend.LDAPBackend are commented out in the settings.

Weblate on the Account page displays 'Full name' entry, but the content is actually user's First name. ID of the form field is 'id_first_name' :). Last name is nowhere to be seen on the account page.  As a result, the commits are signed only with user's first name :(. 

Also, logged-in user's name in the top right page corner is their first name.

**Comment by nijel** [comment]
Indeed Weblate uses only first_name to store full name. The reason for this is that there are countries which do not have first/last name concept and trying to fit these to two field model doesn't work. Also see #401.

I believe something like following configuration should fix it:

```
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "name",
    "email": "mail"
}
```

**Comment by nijel** [comment]
...what is also documented in https://docs.weblate.org/en/latest/admin/auth.html#ldap-authentication
