### ISSUE TITLE
User unable to change email 

### ISSUE THREAD

**Issue by benkovsk** [nijel/weblate#813]
We use weblate (latest git master) with django-auth-ldap. All auth backends except of django_auth_ldap.backend.LDAPBackend are commented out in the settings.

There's no way for a user to change his email address in such scenario. The address can be changed only in the administrative interface (or pulled from LDAP).

**Comment by nijel** [comment]
Weblate verifies emails, so if you want to use different email than the one provided by LDAP, you need to enable email authentication (```'social.backends.email.EmailAuth'```) to ```AUTHENTICATION_BACKENDS```. If you don't want users to be able to register, there is ```REGISTRATION_OPEN```...
