### ISSUE TITLE
Ignore "BOM" characters on file upload

### ISSUE THREAD

**Issue by fisharebest** [nijel/weblate#815]
Some of my translators work offline, and edit .PO files using desktop software (POEdit, notepad.exe, etc.)

Some of these editors (e.g. notepad.exe) will add a "[BOM](https://en.wikipedia.org/wiki/Byte_order_mark)" character at the start of any file containing UTF8 characters.

When this file is uploaded, weblate gives a "success" message which says that 0 strings were processed.  It is not obvious to the user that there is an error with the file.

This request is for weblate to ignore the BOM (\xEF \xBB \xBF) when it appears at the start of uploaded files.

**Comment by nijel** [comment]
Not sure if we can persuate translate-toolkit to do this...
