### ISSUE TITLE
missing template file

### ISSUE THREAD

**Issue by werkraum-admin** [nijel/weblate#816]
Environment:

```
Request Method: POST
Request URL: http://134.119.42.21/translate/gymtotal/gymtotal/ca/?sid=b80a4d84-47e2-11e5-a0c7-00163e03940c&offset=0

Django Version: 1.8.4
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.sitemaps',
 'social.apps.django_app.default',
 'crispy_forms',
 'weblate.trans',
 'weblate.lang',
 'weblate.accounts',
 'weblate')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
 'weblate.accounts.middleware.RequireLoginMiddleware')


Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/weblate/weblate/trans/views/edit.py" in translate
  524.                 this_unit_url, next_unit_url
File "/opt/weblate/weblate/trans/views/edit.py" in handle_translate
  309.         go_next = perform_translation(unit, form, request)
File "/opt/weblate/weblate/trans/views/edit.py" in perform_translation
  236.         form.cleaned_data['fuzzy']
File "/opt/weblate/weblate/trans/models/unit.py" in translate
  998.         saved = self.save_backend(request)
File "/opt/weblate/weblate/trans/models/unit.py" in save_backend
  540.             (saved, pounit) = self.translation.update_unit(self, request, user)
File "/opt/weblate/weblate/trans/models/translation.py" in update_unit
  853.             pounit, add = self.store.find_unit(unit.context, src)
File "/opt/weblate/weblate/trans/formats.py" in find_unit
  535.             return self._find_unit_template(context)
File "/opt/weblate/weblate/trans/formats.py" in _find_unit_template
  492.                     'Could not find template unit for new unit!'

Exception Type: Exception at /translate/gymtotal/gymtotal/ca/
Exception Value: Could not find template unit for new unit!
```

Really need help with this

**Comment by nijel** [comment]
What file format do you use? Maybe it's same as #460.

**Comment by werkraum-admin** [comment]
its in .xlf

source file: 

<code>
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<xliff version="1.0">
	<file source-language="en" target-language="en" datatype="plaintext" original="messages" date="2015-07-22T12:53:24Z">
		<header>
			<generator>LFEditor</generator>
		</header>
		<body>
		<trans-unit id="close" approved="yes">
			<source>Close</source>
			<target>Close</target>
		</trans-unit>
		<trans-unit id="forgot.password" approved="yes">
			<source>Forgot your password?</source>
			<target>Forgot your password?</target>
		</trans-unit>
		<trans-unit id="getaccess.content" approved="yes">
			<source><![CDATA[
          <p>You currently don't have access to this content.</p>
          <p>In the future, the following options will be available for different groups of people: Students, Coach C, Coach B, Coach A (according with the classification of the German Olympic Committee) and Coaches of the National Teams.</p>
          <p>But it will also be possible to book only certain topics, which are displayed in a kind of personal library (MyGym).</p>
          <p>If you are a student of the University of Freiburg, login with the access data that were provided in CampusOnline or Ilias.</p>
          <p>If you are one of the participants in a particular training course, login with the data, which were announced during the course.</p>
          ]]>
      </source>   
      <target><![CDATA[
          <p>You currently don't have access to this content.</p>
          <p>In the future, the following options will be available for different groups of people: Students, Coach C, Coach B, Coach A (according with the classification of the German Olympic Committee) and Coaches of the National Teams.</p>
          <p>But it will also be possible to book only certain topics, which are displayed in a kind of personal library (MyGym).</p>
          <p>If you are a student of the University of Freiburg, login with the access data that were provided in CampusOnline or Ilias.</p>
          <p>If you are one of the participants in a particular training course, login with the data, which were announced during the course.</p>
          ]]>
      </target>   
		</trans-unit>
		<trans-unit id="getaccess.freecontent.description" approved="yes">
			<source>You can find a list of all free contents</source>
			<target>You can find a list of all free contents</target>
		</trans-unit>
		<trans-unit id="getaccess.freecontent.link" approved="yes">
			<source>here</source>
			<target>here</target>
		</trans-unit>
		<trans-unit id="getaccess.register" approved="yes">
			<source>If you would like to be informed when payed-content can be purchased, please register</source>
			<target>If you would like to be informed when payed-content can be purchased, please register</target>
		</trans-unit>
		<trans-unit id="getaccess.register.link" approved="yes">
			<source>here</source>
			<target>here</target>
		</trans-unit>
		<trans-unit id="getaccess.register.note" approved="yes">
			<source>Please subscribe there to the newsletter.</source>
			<target>Please subscribe there to the newsletter.</target>
		</trans-unit>
		<trans-unit id="login" approved="yes">
			<source>Login</source>
			<target>Login</target>
		</trans-unit>
		<trans-unit id="login.error.account-expired" approved="yes">
			<source>Your account has expired. Please contact us to renew it.</source>
			<target>Your account has expired. Please contact us to renew it.</target>
		</trans-unit>
		<trans-unit id="login.error.account-not-started" approved="yes">
			<source>Your account is not activated yet.</source>
			<target>Your account is not activated yet.</target>
		</trans-unit>
		<trans-unit id="login.error.wrong-credential" approved="yes">
			<source>Registration failed. Please check username and password.</source>
			<target>Registration failed. Please check username and password.</target>
		</trans-unit>
		<trans-unit id="logout" approved="yes">
			<source>Logout</source>
			<target>Logout</target>
		</trans-unit>
		<trans-unit id="logout.msg1" approved="yes">
			<source>Nice that you were here. I hope I see you soon again!</source>
			<target>Nice that you were here. I hope I see you soon again!</target>
		</trans-unit>
		<trans-unit id="logout.msg2" approved="yes">
			<source>Please click on the button to log out.</source>
			<target>Please click on the button to log out.</target>
		</trans-unit>
		<trans-unit id="logout.sombody" approved="yes">
			<source>Logout §name§</source>
			<target>Logout §name§</target>
		</trans-unit>
		<trans-unit id="no.account" approved="yes">
			<source>Not yet a member of Gymtotal?</source>
			<target>Not yet a member of Gymtotal?</target>
		</trans-unit>
		<trans-unit id="password" approved="yes">
			<source>Password</source>
			<target>Password</target>
		</trans-unit>
		<trans-unit id="passwordstrength.good" approved="yes">
			<source>Good password</source>
			<target>Good password</target>
		</trans-unit>
		<trans-unit id="passwordstrength.short" approved="yes">
			<source>Too short password</source>
			<target>Too short password</target>
		</trans-unit>
		<trans-unit id="passwordstrength.strong" approved="yes">
			<source>Strong password</source>
			<target>Strong password</target>
		</trans-unit>
		<trans-unit id="passwordstrength.weak" approved="yes">
			<source>Weak password</source>
			<target>Weak password</target>
		</trans-unit>
		<trans-unit id="register.account" approved="yes">
			<source>Register</source>
			<target>Register</target>
		</trans-unit>
		<trans-unit id="user" approved="yes">
			<source>User</source>
			<target>User</target>
		</trans-unit>
		<trans-unit id="your.password" approved="yes">
			<source>Your Password</source>
			<target>Your Password</target>
		</trans-unit>
		<trans-unit id="your.username" approved="yes">
			<source>Your Username</source>
			<target>Your Username</target>
		</trans-unit>
		</body>
	</file>
</xliff>
</code>

**Comment by werkraum-admin** [comment]
* Weblate weblate-2.3-687-g30965f3
 * Python 2.7.6
 * Django 1.8.4
 * python-social-auth 0.2.12
 * Translate Toolkit 1.13.0
 * Whoosh 2.7.0
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.4.4
 * django-crispy-forms 1.5.0
 * pyuca N/A
 * pyLibravatar N/A

**Comment by werkraum-admin** [comment]
this error occurs only if i set the base file:
data-mask: Resources/Private/Language/*.locallang.xlf
base-file-mask: Resources/Private/Language/locallang.xlf
