### ISSUE TITLE
ACL doesn't play well with cache

### ISSUE THREAD

**Issue by jportoles** [nijel/weblate#828]
Every time a user is given a permission or added into a group via the django admin site panel, for a project that has ACL active, I have to restart memcached for the changes to take effect. It looks like something that could be potentially fixed at a software level.

**Comment by nijel** [comment]
What version are you using? This should have been fixed by bb346288 (also see #758).

**Comment by jportoles** [comment]
2.3, it indeed it looks like that commit addresses this, so feel free to close the issue, we should just upgrade to 2.4 some time :)
