### ISSUE TITLE
Parameter for main component on import_project command

### ISSUE THREAD

**Issue by rvanlaak** [nijel/weblate#829]
The [`import_project` command](https://docs.weblate.org/en/latest/admin/management.html#import-project-project-gitrepo-branch-filemask) is quite extensive and powerful. While using it, I saw the following console output:

    INFO Creating component validators as main one

This probably is the last file found by the command. Would be nice if the main component could be set via an extra `--main-component` parameter.

**Comment by nijel** [comment]
You can create it first manually, and then use ``weblate://project/component`` as repository URL.

**Comment by nijel** [comment]
..but having option to specify it from command line indeed looks useful.

**Comment by nijel** [comment]
Implemented.

**Comment by rvanlaak** [comment]
:+1:
