### ISSUE TITLE
Exception on saving monolingual XLIFF translation

### ISSUE THREAD

**Issue by rvanlaak** [nijel/weblate#830]
An exception occured when a translation was saved:

```
Exception at /translate/demo/adminbackend/en/
Could not find template unit for new unit!
Request Method:	POST
Request URL:	https://demo.nl/weblate/translate/demo/adminbackend/en/?sid=89dbd564-50ab-11e5-8351-001e8c1fb675&offset=0
Django Version:	1.8.4
Exception Type:	Exception
Exception Value:	
Could not find template unit for new unit!
Exception Location:	/var/www/weblate/weblate/trans/formats.py in _find_unit_template, line 497
Python Executable:	/usr/bin/python
Python Version:	2.7.3
Python Path:	
['/var/www/weblate',
 '/usr/local/lib/python2.7/dist-packages/Weblate-2.4-py2.7.egg',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/pymodules/python2.7']
Server time:	Tue, 1 Sep 2015 13:15:41 +0000
```

```
Environment:


Request Method: POST
Request URL: https://demo.nl/weblate/translate/demo/adminbackend/en/?sid=266016bc-50ab-11e5-a66a-001e8c1fb675&offset=0

Django Version: 1.8.4
Python Version: 2.7.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.sitemaps',
 'social.apps.django_app.default',
 'crispy_forms',
 'compressor',
 'weblate.trans',
 'weblate.lang',
 'weblate.accounts',
 'weblate')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
 'weblate.accounts.middleware.RequireLoginMiddleware')


Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/var/www/weblate/weblate/trans/views/edit.py" in translate
  524.                 this_unit_url, next_unit_url
File "/var/www/weblate/weblate/trans/views/edit.py" in handle_translate
  309.         go_next = perform_translation(unit, form, request)
File "/var/www/weblate/weblate/trans/views/edit.py" in perform_translation
  236.         form.cleaned_data['fuzzy']
File "/var/www/weblate/weblate/trans/models/unit.py" in translate
  998.         saved = self.save_backend(request)
File "/var/www/weblate/weblate/trans/models/unit.py" in save_backend
  540.             (saved, pounit) = self.translation.update_unit(self, request, user)
File "/var/www/weblate/weblate/trans/models/translation.py" in update_unit
  847.             pounit, add = self.store.find_unit(unit.context, src)
File "/var/www/weblate/weblate/trans/formats.py" in find_unit
  540.             return self._find_unit_template(context)
File "/var/www/weblate/weblate/trans/formats.py" in _find_unit_template
  497.                     'Could not find template unit for new unit!'

Exception Type: Exception at /translate/demo/adminbackend/en/
Exception Value: Could not find template unit for new unit!
```

**Comment by nijel** [comment]
What file format do you use? How is the translation component configured?

BTW: Might be similar issue to  #816.

**Comment by Rvanlaak** [comment]
We use the XLIFF format, because the translation toolkit advises it as the primary translation format. We initially did not import the project with `--file-format=xlf`, could that be the problem? The error does still occur after I changed the format from auto to xliff via the admin backend.

**Comment by Rvanlaak** [comment]
![fireshot capture 1 - change component i _ - https___dev scribbr nl_weblate_admin_trans_subproject_2_](https://cloud.githubusercontent.com/assets/2707563/9606308/ebc2dffe-50c2-11e5-8db7-70c95c90c0cb.png)

**Comment by Rvanlaak** [comment]
Does the screenshot explain something @nijel

**Comment by nijel** [comment]
I think there must be some bug in handling monolingual files. However what surprises me, that I didn't hit it yet with dozens of monolingual translations on Hosted Weblate. Needs some time to diagnose this.

**Comment by Rvanlaak** [comment]
Can I provide you with some extra details on the exception? Or maybe perform some steps for you on my installation? We're on the latest `master`.

**Comment by nijel** [comment]
Most importantly I need to find time to debug this ;-).

**Comment by Rvanlaak** [comment]
Did you find some time to fix the monolingual translations?

**Comment by nijel** [comment]
Not yet, I have more urgent stuff to do right now.

**Comment by Rvanlaak** [comment]
And related to #460 which already is from march 2014 :+1: Seems like monolingual components aren't used much? For me it seems monolingual components are the way to go for 80% of the applications right?

**Comment by nijel** [comment]
On Hosted Weblate, about 1/3 is monolingual and 2/3 bilingual, so my numbers differ :-). I haven't looked for some generic stats if something is available.

On the other side I see there different file formats (mostly Android, JSON, Java or iOS translations). This bug seems to be specific to particular file formats (#460 is about Qt, #816 and #830 about XLIFF). Generally it seems that formats which are widely used as both monolingual and bilingual are affected. 

Still this is free software, so anybody can dig into this and submit patch or you can [post a bounty on this issue](https://www.bountysource.com/issues/26360162-exception-when-saving-translation?utm_campaign=plugin&utm_content=tracker%2F253393&utm_medium=issues&utm_source=github) to motivate somebody working on it.

PS: The "Base file for new translations:" is not really needed.

**Comment by daniele-athome** [comment]
I don't know if this can be of help, but I've updated translate-toolkit to the latest version (1.13.0, also upgraded babel along it) and it fixed this issue (on Android resource files).

**Comment by nijel** [comment]
For Android resources this is expected, the support for it improves in every translate-toolkit release (also thanks to Weblate users who push fixes there), but I don't think it will help with other formats.

**Comment by Rvanlaak** [comment]
This issue is XLIFF specific, the toolkit doesn't allow Weblate to add new translations in case of monolingual components. At least, it is the toolkit right?

**Comment by rvanlaak** [comment]
Will test this later today and let you know :+1:

**Comment by rvanlaak** [comment]
Was able to test this today, and the bug indeed is resolved. Unfortunately there is some expected behaviour as you can see in #939
