### ISSUE TITLE
Catch exception when running under different user

### ISSUE THREAD

**Issue by rvanlaak** [nijel/weblate#831]
Related to https://github.com/nijel/weblate/issues/493#issuecomment-136708004 , `import_project` was executed by another user than the web user.

Would be nice if this exception could be more explanative. Something like an extra page with more information and a link to the documentation about how to solve this, because this probably is an exception that happens quite often.

**Comment by nijel** [comment]
Another example of similar error (coming from Whoosh):

```IOError: [Errno 13] Permission denied: 
'/var/lib/weblate/whoosh/_source_0.toc.1441382077.08'```

**Comment by nijel** [comment]
Generally these things happen when management command is executed as different user than the one serving website.

**Comment by Rvanlaak** [comment]
Yes, understand that. But my point is that it is quite easy to catch these errors and give the user a proper 'howto solve this' page. Don't think that will save you a lot of issues and time? :+1:

**Comment by nijel** [comment]
Yes, that would be helpful, that's why this issue is open ;-). I was just adding another example where things can go wrong.

**Comment by nijel** [comment]
Weblate now checks if it has proper access to the important directories, so it should warn properly in this case.
