### ISSUE TITLE
RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated

### ISSUE THREAD

**Issue by whedro** [nijel/weblate#838]
Don't miss / (Aby sa nezabudlo) .. :)

/usr/local/lib/python2.7/dist-packages/south/modelsinspector.py:20: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

**Comment by nijel** [comment]
That's not coming from Weblate own code, it's from [python-social-auth][1]. You can get rid of it by uninstalling South, which is not used anyway.

[1]:https://github.com/omab/python-social-auth

**Comment by whedro** [comment]
Thanks.. (uninstaling and remove from settings ...)

**Comment by whedro** [comment]
Hi nigel ..
I have this message again
/usr/local/lib/python2.7/dist-packages/south/modelsinspector.py:20: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic


/opt/weblate/manage.py update_index

**Comment by nijel** [comment]
As you can see, it's coming from third party module. AFAIR south is imported by older versions of python-social-auth, so try upgrading that (but I might be wrong...).

**Comment by whedro** [comment]
pip install python-social-auth --upgrade
Collecting python-social-auth
  Downloading python_social_auth-0.2.13-py2-none-any.whl (272kB)
    100% |████████████████████████████████| 274kB 1.4MB/s
Requirement already up-to-date: python-openid>=2.2 in /usr/local/lib/python2.7/dist-packages (from python-social-auth)
Collecting requests>=2.5.1 (from python-social-auth)
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB)
    100% |████████████████████████████████| 503kB 797kB/s
Requirement already up-to-date: six>=1.2.0 in /usr/local/lib/python2.7/dist-packages (from python-social-auth)
Requirement already up-to-date: oauthlib>=0.3.8 in /usr/local/lib/python2.7/dist-packages (from python-social-auth)
Requirement already up-to-date: PyJWT>=1.0.0 in /usr/local/lib/python2.7/dist-packages (from python-social-auth)
Collecting requests-oauthlib>=0.3.1 (from python-social-auth)
  Downloading requests_oauthlib-0.6.0-py2.py3-none-any.whl
Installing collected packages: requests, requests-oauthlib, python-social-auth
  Found existing installation: requests 2.7.0
    Uninstalling requests-2.7.0:
      Successfully uninstalled requests-2.7.0
  Found existing installation: requests-oauthlib 0.5.0
    Uninstalling requests-oauthlib-0.5.0:
      Successfully uninstalled requests-oauthlib-0.5.0
  Found existing installation: python-social-auth 0.2.12
    Uninstalling python-social-auth-0.2.12:
      Successfully uninstalled python-social-auth-0.2.12
Successfully installed python-social-auth-0.2.13 requests-2.9.1 requests-oauthlib-0.6.0


but without change .... :(

**Comment by whedro** [comment]
where I found, which module generate this error ?

**Comment by nijel** [comment]
I think you can just safely uninstall south package which is causing this - it's not used and not even compatible with recent Django versions...
