### ISSUE TITLE
add support for new language hooks

### ISSUE THREAD

**Issue by stanislav-brabec** [nijel/weblate#840]
Adding a new translations now could requite an additional manual work.

However there are many ways to update languages list, adding a support for several of them will cover major part of Open Source projects. It would be nice to make possible to add hooks for them, so Weblate could add new languages automatically.

Here is the list of basic hooks:
- file named LINGUAS in the translations directory
- file named LINGUAS in po directory (in such case, all translation subprojects needs to have the same list of existing translations)
- line starting with ALL_LINGUAS= in configure.ac, configure.in (and configure, if it exists in the git repo) (in such case, all translation subprojects needs to have the same list of existing translations)

In general, the hook inputs should be:
- the source tree itself
- list of all existing languages
- the language that is being added
- list of other sub-projects that operate on the same tree (e. g. two directories po, po-locations with ALL_LINGUAS method imply, that adding of translation to po will require adding a file to po-locations).

The output would be a list of files that were changed or added.

Here is a shell hook I successfully use in the SUSE translation-update-upstream project (cwd is a directory with po files, OLDPWD is a top directory of the project, LNG is the name of language being added). This hook is not good enough for Weblate, as it adds languages unsorted.

```shell
# Update all known mechanisms to add language:
function linguas_update {
	if test -f LINGUAS -o -f ../po/LINGUAS ; then
	    if test -f LINGUAS ; then
		if sed '/^#/d' <LINGUAS | grep -q '[a-zA-Z0-9] [a-z]' ; then
		    echo "Adding $LNG to LINGUAS in to a list in single-line list mode."
		    sed -i "s/^[^#].* [a-z].*\$/& $LNG/" LINGUAS
		else
		    echo "Adding $LNG to LINGUAS."
		    echo $LNG >>LINGUAS
		fi
	    else
		echo "Not adding $LNG to LINGUAS - secondary domain, global LINGUAS."
	    fi
	else
	    if test -f $OLDPWD/configure.ac ; then
		if grep -q 'ALL_LINGUAS=' $OLDPWD/configure.ac ; then
		    echo "Adding $LNG to configure.ac."
		    sed -i 's/ALL_LINGUAS="/&'$LNG' /;s/\(ALL_LINGUAS=\)\([^"]\|$\)/\1"'$LNG' "\2/' $OLDPWD/configure.ac
		fi
	    fi
	    if test -f $OLDPWD/configure.in ; then
		if grep -q 'ALL_LINGUAS=' $OLDPWD/configure.in ; then
		    echo "Adding $LNG to configure.in."
		    sed -i 's/ALL_LINGUAS="/&'$LNG' /;s/\(ALL_LINGUAS=\)\([^"]\|$\)/\1"'$LNG' "\2/' $OLDPWD/configure.in
		fi
	    fi
	    if test -f $OLDPWD/configure ; then
		if grep -q 'ALL_LINGUAS=' $OLDPWD/configure ; then
		    echo "Adding $LNG to configure."
		    sed -i 's/ALL_LINGUAS="/&'$LNG' /;s/\(ALL_LINGUAS=\)\([^"]\|$\)/\1"'$LNG' "\2/' $OLDPWD/configure
		fi
	    fi
	fi
}
```

**Comment by nijel** [comment]
I've added support for this based on your script.
