### ISSUE TITLE
support more than one ssh key?

### ISSUE THREAD

**Issue by danielnaber** [nijel/weblate#842]
I cannot use the public ssh key shown in the admin area in more than one github project as github then complains `Key is already in use`.

Also, the admin interface is a bit confusing as the `Public SSH key` textarea is editable but cannot actually be saved. It might make more sense to make it non-editable?

**Comment by nijel** [comment]
I've just changed the textarea to be read only, thanks for suggestion.

As for multiple keys, it might be added in future. For now, you can create separate user on GitHub, add him the Weblate SSH key and grant him permissions to access projects you want (this is approach we use for Hosted Weblate).

**Comment by danielnaber** [comment]
Thanks, that workaround sounds good enough. Maybe it should be mentioned at https://docs.weblate.org/en/latest/admin/projects.html#private.

**Comment by nijel** [comment]
Dne Wed, 09 Sep 2015 03:36:12 -0700
Daniel Naber <notifications@github.com> napsal(a):

> Thanks, that workaround sounds good enough. Maybe it should be mentioned at https://docs.weblate.org/en/latest/admin/projects.html#private.

Good idea, I've just added it.

-- 
	Michal Čihař | http://cihar.com | http://blog.cihar.com

**Comment by nijel** [comment]
We could add per component setting with ssh key selection using [FilePathField](https://docs.djangoproject.com/en/1.8/ref/models/fields/#filepathfield). Offering all files matching ``id_[^.]*`` (or something similar). The admin interface could then provide option to enter additional field for key name...

**Comment by nijel** [comment]
Now covered even better by docs (including HTTPS access using tokens) : https://docs.weblate.org/en/latest/admin/projects.html#vcs-repos

I'd really like to avoid having multiple SSH keys for now.
