### ISSUE TITLE
No Android offered in weblate 2.3.1

### ISSUE THREAD

**Issue by danielnaber** [nijel/weblate#843]
I'm using weblate 2.3.1 from bitnami and it works fine for Java property files but Android resources files are not automatically detected (`Format of translation base file could not be recognized.`) nor can I select them in the `File format` drop down. The drop down has 11 items + automatic detection, but no Android. What am I doing wrong?

**Comment by nijel** [comment]
The version of installed translate-toolkit is probably too old, what version is there? You can get list of Wammu deps by ```manage.py list_versions```.

**Comment by danielnaber** [comment]
http://myserver:8080/weblate/about/ says it's Translate Toolkit 1.13.0. Calling manage.py on the command line doesn't work (`ImportError: No module named django.core.management`). I got weblate from https://bitnami.com/stack/weblate/installer

**Comment by nijel** [comment]
Hmm, maybe then just some of dependencies are missing. Maybe [Babel](https://pypi.python.org/pypi/Babel) is not installed?

**Comment by danielnaber** [comment]
It's not listed on the "about" page. Maybe I need to report this at bitnami?

**Comment by nijel** [comment]
Can you login to the system and check if it's installed? It won't get reported on the about page (as it's not direct dependency on Weblate, but rather translate-toolkit one).

**Comment by nijel** [comment]
But asking Bitnami support sounds like a good idea.

**Comment by danielnaber** [comment]
I'm not familiar enough with Python, but `find . -iname "*babel*"` returns nothing. I'll ask in the bitnami forum.

**Comment by nijel** [comment]
If you have access to shell, ``pip install Babel`` should do it.

**Comment by danielnaber** [comment]
Thanks! `./python/bin/pip install Babel` did it and translating Android files works now. I have commented in the bitnami forum so they know about this.
