### ISSUE TITLE
Some translations lost after hitting "Rebase" on web UI

### ISSUE THREAD

**Issue by mvdan** [nijel/weblate#847]
A translator was doing some translations and I hit the "Rebase" button, since I wanted to pull translations without a merge commit.

Most translations that the translator had done had been commited and weren't lost, but a few were lost. I'm guessing this is because they were uncommited changes, and since `git rebase` refuses to work with uncommited changes, perhaps Weblate discarded the changes instead of commiting them.

**Comment by nijel** [comment]
Rebase really shouldn't do something like that, it really just calls git rebase under the hood after committing all changes. Do you know which translation has been lost, so that I can look it up the logs?

**Comment by mvdan** [comment]
Sorry for not responding earlier.

It was the dutch translation of f-droid in the hosted service, on the day this issue was reported: https://hosted.weblate.org/projects/f-droid/f-droid/nl

The user that noticed this was Sylvie.

**Comment by nijel** [comment]
I believe the problem has been fixed with changes made for #861. There was possibility that not committed changes has been lost due to Weblate not commiting deterministically in this case.
