### ISSUE TITLE
Automatically give permission based on email wildcard

### ISSUE THREAD

**Issue by NicOOM** [nijel/weblate#852]
Hello, 

What would be great to have is a pre-registration system where we could allow emails address in advance to be able to register on weblate in stead of openning it to everyone. When connected, these users would have permissions on some specific project setuped in advance.

Example :
A weblate setup to be close to anyone unless you have a account. The administrators add a project, "Translate Toto site" for example. And we would be able to setup permission to that project to all "@toto.com" emails address.

**Comment by nijel** [comment]
You mean to add list of emails in advance, or to specify email wildcard who should get permission?

**Comment by NicOOM** [comment]
Yes typically we are using weblate to have translation from our clients. It would be great to be able to allow all the email address of the client (a wildcard yes) without having to create users individually and having to send the login/password (like we do now).

**Comment by nijel** [comment]
Thanks for clarification, I've updated the title accordingly.
