### ISSUE TITLE
Subproject setup error on docker

### ISSUE THREAD

**Issue by crisp2u** [nijel/weblate#855]
I'm trying to follow the instruction to setup an instance of weblate in a docker container. So far so good webslate is up and runnign but when I try to add a subproject I get this error "OSError at /admin/trans/subproject/add/
[Errno 2] No such file or directory: '/app/data/whoosh'". More details here: http://dpaste.com/0K090KS

Any clues ?

**Comment by nijel** [comment]
Can you please post full stacktrace? This would really help me to figure out what went wrong...

**Comment by crisp2u** [comment]
DPaste link is not enough ? I'm not familiar with Pyton and Django and I used the build in error reporting

**Comment by nijel** [comment]
Sorry, I somehow didn't see the link :-).

**Comment by crisp2u** [comment]
Wow, that was fast, under 4 minutes :-) Do you know how I can rebuild the docker container using this fix ? Currently requirements.txt lists Weblate at 2.3. Do I need to wait for another release ?

Thanks!

**Comment by nijel** [comment]
Anyway I think 2.4 should work correct as way, my fix was really for corner case....

**Comment by crisp2u** [comment]
I'll try also 2.4, in the meantime i found the answer here: https://pip.pypa.io/en/stable/user_guide/#requirements-files. I might even try to learn some Python. It's on my todo list anyway :-).

**Comment by nijel** [comment]
I've updated the docker repo to new requirements as well: https://github.com/nijel/weblate-docker/commit/4e82d4193b8fcad558f57c955a2b0fdcff760fd3
