### ISSUE TITLE
Searching does not work

### ISSUE THREAD

**Issue by tpokorra** [nijel/weblate#856]
I upgraded from weblate 2.1 to 2.2 to 2.3 to 2.4.

Now the search does not work anymore.

The error message looks very much similar to what @nijel reported here:
https://bitbucket.org/mchaput/whoosh/issues/421/error-when-adding-field

Is there an easy workaround for this? Perhaps can I reset the whoosh index? How would I do that?

**Comment by nijel** [comment]
The workaround is to [rebuild index][1]:

  ./manage.py rebuild_index --clean

[1]:https://docs.weblate.org/en/latest/admin/management.html#rebuild-index-project-project-component
