### ISSUE TITLE
Ignore languages that are symlinks to other languages

### ISSUE THREAD

**Issue by mvdan** [nijel/weblate#858]
Android isn't consistent when it comes to language codes sometimes. For Hebrew, for example, on some devices use `values-he` and some use `values-iw`. Hence, some apps like mine do a symlink as follows `values-iw/ -> values-he/`.

The result is that `res/values-iw/strings.xml` is the same file as `res/values-he/strings.xml`. I would expect weblate to see that and ignore `iw`. Instead, I get an `iw (generated)` language in the web interface alongisde `Hebrew`.

Just to clarify, by the files being equal I mean their realpaths - not their contents.

**Comment by mvdan** [comment]
Proof: https://hosted.weblate.org/projects/f-droid/f-droid/

[Screenshot](http://i.imgur.com/1D5vyP3.png)

**Comment by mvdan** [comment]
Should this be working now? I still see `iw (generated)` on https://hosted.weblate.org/projects/f-droid/f-droid/.

**Comment by nijel** [comment]
It was fixed in Git, but not yet deployed. I've pushed the changes to production right now.

**Comment by mvdan** [comment]
Thanks, works now!
