### ISSUE TITLE
Same language but different language codes 

### ISSUE THREAD

**Issue by haifengkao** [nijel/weblate#859]
The language codes of an android project are something like 
`values-zh`
`values-en`

but for ios projects, they are like
`zh-Hant`
`en`

How do I set the same language for different language codes?
e.g.
English: `en`, `values-en`
Traditional Chinese: `zh-Hant`, `values-zh`

Besides,
Is it possible to put all android language codes into the default language codes, so I don't have to look it up on the internet?

**Comment by nijel** [comment]
For Android use values-* in the mask, so that only language code is matched. As for zh and zh-Hant, these IMHO should be treated as different languages.

**Comment by haifengkao** [comment]
It's more messy than you think.
In android, we have
```
values-zh-rCN
values-zh-rTW
values-zh-rHK
```
, which correspond to 
```
zh-Hans
zh-Hant
zh-HK
``
in iOS.

They are the same languages, but different codes.

**Comment by nijel** [comment]
The zh-rHK / zh-HK will work, for the latter the mapping is not there as zh-CN could be actually different than zh-Hans.

**Comment by haifengkao** [comment]
1. How to make zh-rHK / zh-HK work?
2. You are right. The language codes are very messy.
zh-Hant (Chinese written using the Traditional Chinese script)
zh-Hans (Chinese written using the Simplified Chinese script)
zh-cmn-Hans-CN (Chinese, Mandarin, Simplified script, as used in
      China)
cmn-Hans-CN (Mandarin Chinese, Simplified script, as used in
      China)
zh-yue-HK (Chinese, Cantonese, as used in Hong Kong SAR)
yue-HK (Cantonese Chinese, as used in Hong Kong SAR)
zh-Hans-CN (Chinese written using the Simplified script as used in
      mainland China)

But I am not a board member of RFC, I don't really care about the theoretical differences.
In practice, zh-CN is zh-Hans until Cantonese win their own independence.

It would be nice if weblate can allow us to adjust the language code correspondences if the political facts change.

**Comment by nijel** [comment]
Because we strip -r when parsing the language code (see https://github.com/nijel/weblate/blob/master/weblate/lang/models.py#L92).

As for other Chinese variants, I'm not really sure that merging these is good idea, though it's probably what most people expect these days...

**Comment by haifengkao** [comment]
You can let us choose what to merge. Otherwise it's really inconvenient to handle both Android and iOS projects.

**Comment by nijel** [comment]
Implemented change that will work for new installations. If you want to migrate existing one, you will have to manually adjust existing translations to use new language code.

**Comment by haifengkao** [comment]
thanks!
