### ISSUE TITLE
Fails to rebase on squashed commits if new files are added

### ISSUE THREAD

**Issue by mvdan** [nijel/weblate#860]
I squash weblate's commits before pushing to my repo. Upon rebasing on the weblate web UI, it often works just fine. But if new files are added, like a new language, it breaks:

```
Error message:

Failed to merge in the changes. (1)

Repository status:

rebase in progress; onto 24ffbb2
You are currently rebasing branch 'master' on '24ffbb2'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

        both added:      F-Droid-Privileged/src/main/res/values-ast/strings.xml

no changes added to commit (use "git add" and/or "git commit -a")
```

Seems like an easy thing to work around.

**Comment by nijel** [comment]
I don't really see the easy way to work around this - all Weblate does is to call git...

**Comment by mvdan** [comment]
Assuming that the two added files are exactly the same, it would simply be making rebase use either of them. But in the generic rebase procedure, you can't assume that they are equal. You are right - there isn't an easy workaround.

All I could find about it is this:
https://stackoverflow.com/questions/9950466/why-does-git-show-a-conflict-between-two-apparently-identical-added-files

It does make sense that rebase would silently accept two added files which are exactly equal. I wonder if in that rebase the two files had a trailing newline difference. I didn't edit them manually, all I did was squash the commits.

**Comment by mvdan** [comment]
Actually, the issue was that someone had modified the source strings - `values/strings.xml` - and I was just ignoring those changes in my squashed commit. I was doing that on purpose, and Weblate was right to not rebase since the changes were different.

**Comment by nijel** [comment]
Thanks for clarification.
