### ISSUE TITLE
"Push" action extremely slow

### ISSUE THREAD

**Issue by efdee** [nijel/weblate#861]
We are currently using Weblate to allow people to translate xliff files from our repository. We have a high amount of subprojects (+- 300) divided over 4 projects. Per project there is one subproject that refers to the actual Git repository - the other subprojects just refer to this subproject for the repository (weblate://project/subproject style).

A pull action from initiated from the Repository Maintenance screen takes about 15-20 seconds, which is a long time but acceptable considering the amount of subprojects we have.

A push action however takes about 5 minutes, even if there are no commits waiting to happen. I don't see anything happening in the Weblate logs. Can you suggest any way to optimize this or even just to figure out what it's trying to do?

Thanks.

**Comment by nijel** [comment]
What version are you using? There have been some improvements to repository management in 2.4, though they were mostly for the pull times...

**Comment by efdee** [comment]
2.3. We are planning an upgrade soon though.

Pull times are still acceptable. Push times seem more of a problem though.

I'll report back with my experiences after doing the upgrade.

**Comment by efdee** [comment]
We're on 2.4 now, but the same issue persists. Is there some way I can monitor what's going on during those 5 minutes of pushing?

Also, from reading the logfiles, I get the impression that when I execute a 'pull' on a project, it does a pull for every subproject separately, even if they all link to the same repository (so one subproject with the actual repository and the others all linking to weblate://project/subproject). So the end result is something like:

> DEBUG project/subproject: update: Fetching origin
> INFO project/subproject: updating repository
> INFO project/subproject: update took 0.06 seconds:
> DEBUG project/subproject: update: Fetching origin
> INFO project/subproject: updating repository
> INFO project/subproject: update took 0.06 seconds:
> DEBUG project/subproject: update: Fetching origin
> INFO project/subproject: updating repository
> INFO project/subproject: update took 0.06 seconds:

repeated 100 times or so.

**Comment by nijel** [comment]
Indeed it currently performs operation for every translation and doesn't delay them till the end. This should be fixed....

**Comment by nijel** [comment]
I've made lot of improvements to the pull/commit logic, can you please try current git version?

I'm not sure if there is much more space for improvements now - most of other changes would improve performance for some situations, but it would also made it worse for others.

**Comment by efdee** [comment]
Our first tests seem to indicate that the 5 minute waiting time on our push actions has been reduced to a mere 10 seconds. This is very encouraging. I will report back soon after some more testing.

**Comment by nijel** [comment]
This should be fixed now.
