### ISSUE TITLE
No error message for user with syntax error in XML

### ISSUE THREAD

**Issue by danielnaber** [nijel/weblate#862]
(Note: I'm still on 2.3) I'm translating Android files and one file had a syntax error (`&` instead of `&amp;`) and changes in the English source where not detected. The log said:

    WARNING clipnow/mobile-app/de: failed parsing store: xmlParseEntityRef: no name, line 205, column 13

It would be nice to show these errors in the user interface and not just in the log, as it's confusing if there are suddenly no updates anymore.

**Comment by nijel** [comment]
AFAIR with 2.4, you should get mail notification as well, but still this should go to the changes log as well...
