### ISSUE TITLE
Improve language selection in profile

### ISSUE THREAD

**Issue by shanewims** [nijel/weblate#863]
Localisation Engineer typically works with all languages supported by the product. The current language selection method assumes user (translator) only works with a few languages. I work across 16 languages. The drop down list method of selecting languages is difficult to work with as forgetting to hold down shift key while selecting languages means that previous selections are lost and the whole language selection process has to be done again.

![language_selection](https://cloud.githubusercontent.com/assets/3809504/10244159/5f6bf90a-68f5-11e5-9081-096f36d50e4a.png)

**Comment by nijel** [comment]
Indeed current selection is not optimal, but given number of languages, simple checkboxes will make the page explode.

**Comment by shanewims** [comment]
Can it be implemented on SUSE hosted version of Weblate? SLE language set was 27 at most, usually around 16 for more recent version. If we want professional translators and localisation engineers to use this system, it needs to be as easy to use as possible.

**Comment by nijel** [comment]
My current idea is to use the dual list selection here. There are several Bootstrap plugins for that: http://crlcu.github.io/multiselect/#demo-search http://www.virtuosoft.eu/code/bootstrap-duallistbox/

**Comment by shanewims** [comment]
That looks like a good solution. Thanks.

**Comment by nijel** [comment]
Great, this will scale good for high number of languages.

**Comment by nijel** [comment]
Implemented by #915 by @ejjoman.
