### ISSUE TITLE
Provide custom views

### ISSUE THREAD

**Issue by nijel** [nijel/weblate#865]
The dashboard view should be configurable, we need at least following options:

* show all (accessible) translations (current way)
* show all translations in projects user has joined (see #568, should be default)
* show components matching given pattern
* show projects matching given pattern
* show selected translations within project/component

All of these will still filter for user language.

This should be configured in the user profile, the views would be defined in the admin interface.

**Comment by nijel** [comment]
The view defining models could have following fields:

* member_only (boolean) to filter for membership projects
* match_component (regexp) to filter component slug
* match_project (regexp) to filter project slug

**Comment by matejcik** [comment]
together with @stanislav-brabec and @jitka we designed an approach that seems reasonable

we would change the "Your translations" button on dashboard to be a drop-down selector, with the following options:
+ _Your translations_ -- shows only projects you are subscribed to
+ _Your languages_ -- shows all projects
+ an item for every _component list_

all of those are filtered based on user's primary languages

we would also add "component lists", that is, global named lists of project components. the SUSE instance would probably have two components list, one "openSUSE" and one "SLE"

we would add a user configuration option, selecting which of the possible views should they see by default. the default value of this option would be "your translations", i.e., subscribed projects

I'm not sure how valuable is the regexp based filtering. For languages, it doesn't make much sense when the list of languages is constant. For projects, you have subscriptions, and maybe more useful would be something like auto-subscribe based on regexp?

Regexp matching for components makes sense. But then again we probably need both _enumerated list_ and _matching_ functionality, and making it an enumerated list looks better as a first step? :)

**Comment by nijel** [comment]
Sounds good. In future I'd like to decouple subscription from project membership, but that doesn't have to be implemented right now.
