### ISSUE TITLE
Can search be restricted to one language

### ISSUE THREAD

**Issue by shanewims** [nijel/weblate#866]
Sometimes when localisation engineer is trying to fix a bug and is trying to narrow down location of string, they might want to restrict the search for a string (or part of a string) to one language or file.

Is it possible to do this? Currently search seems to get hits in all target languages and files. For YAST and LCN this over 100 files in 15 languages, so search results could be overwhelming.

**Comment by nijel** [comment]
You can currently search site wide or in single translation (eg. https://hosted.weblate.org/projects/weblate/website/cs/#search). Limiting site wide search to single language indeed makes sense.
