### ISSUE TITLE
CSS for admin dashboard not found.

### ISSUE THREAD

**Issue by fengkaijia** [nijel/weblate#872]
I was unable to load CSS required by Django Admin dashboard.

```
Failed to load resource: the server responded with a status of 404 (Not Found)
https://***/static/admin/css/dashboard.css

Failed to load resource: the server responded with a status of 404 (Not Found)
https://***/static/admin/css/base.css
```

I checked ```/path/to/weblate/weblate/static/``` there's no ```admin``` folder in it.

**Comment by fengkaijia** [comment]
Well I found out ```./manage.py collectstatic``` is required. This command is unclear in docs (the full one).

**Comment by fede91it** [comment]
Also executing that command the /admin folder was not created.

What I'm wrong?
