### ISSUE TITLE
How do I set source language?

### ISSUE THREAD

**Issue by chrisk414** [nijel/weblate#876]
Hi, There! I'm new to Weblate and I think it's wonderful product.
However, I have one question.
I'm using Korean as source language but there seem to be no option to set the source language.
When I click on "Start new translation" and choose of the "English" language, it comes with 100% translated. When I choose languages other than English, it start with 0% translated, of which expected.
I think the problem is because the source language is assumed as English always.
How do I fix this problem?

Thank you very much!

-chris

ps. I'm using Weblog 2.3 from Bitnami

**Comment by nijel** [comment]
Indeed source language is currently assumed English and there is no way to change it right now.

**Comment by ihoru** [comment]
It's a pity :( I would like to change source language also...

**Comment by nijel** [comment]
Source language can be set per project since 2.5, see milestone of this issue.
