### ISSUE TITLE
Second language preview doesn't show up.

### ISSUE THREAD

**Issue by chrisk414** [nijel/weblate#877]
Our source language is Korean and I create a new language, called "English-development" 
It's a interim English language we create before handing it over to publisher. 
Publisher will then look at this interim English as a reference to translate to proper target English. 
Therefore the publisher will need to set this interim English as the second language to show up in the translation input screen. But for some reason, this interim English won't show up in the translation input screen no matter what I do. (I'm not talking about personal profile secondary language option box. It shows up there fine) 
Other language I added by "Start new translation" show up properly as expected when I set them as secondary language and when it has some translation. 
Could you please help?

Here is how I create sub-project.
"sub-project" references .pot file (Korean source template) and .po file (from Korean to the interim English-development) In personal profile, Everything seems to work fine except this English-development will not show up as secondary language in the translation input screen. 

Thank you very much!

-chis

ps. I'm using weblog 2.3 from Bitnami.

**Comment by nijel** [comment]
This might be actually related to #876, though I'm not aware of any special handling of this case.

**Comment by nijel** [comment]
What are the actual filenames of the .po files?

**Comment by chrisk414** [comment]
Hi, Nijel, Thanks for taking a look.
They are, LSMapStrings.pot and LSMapStrings.po 
Will the name matter?

Cheers!

**Comment by nijel** [comment]
Yes, filename does matter, because Weblate uses it to determine file language.

**Comment by nijel** [comment]
O believe this was fixed together with option to specify source language (#876).
