### ISSUE TITLE
Creating sub-projection without .po file?

### ISSUE THREAD

**Issue by chrisk414** [nijel/weblate#878]
Hi, there! I'm new to Weblate and this is a newbie question.
I had hard time creating a sub-project because it requires at least one .po file.
Hmm.. It seems little odd that it needs to have at least one translation before starting translation. 
I would like to start the translation from .pot file and add new language clicking on "Start new translation"
Is there a reason why there has to be at least one .po file when creating a sub-project?

Cheers!

-chris

**Comment by nijel** [comment]
The reason is that originally Weblate didn't support adding new languages, so it didn't make sense to create project without one. When this feature is available, it indeed makes sense to loosen this limitation.

**Comment by chrisk414** [comment]
Yeah, that would be great!
It didn't makes sense to me at first and I figured out the hard way.
Hope it won't bite other new users. ^^

Cheers!

**Comment by nijel** [comment]
Fixed this after seeing another new user hitting this wall...
