### ISSUE TITLE
How to modify or add source langauge string

### ISSUE THREAD

**Issue by blackspotent** [nijel/weblate#884]
Hi, 
I now have translation project setup and it seems to work correctly.
But I stuck hot to handle modfiying source string or adding/deleting a new source string.
Source string may have spelling errors and it often needs modification, or I may add new strings or delete some. 
There is no way to do this from Weblate UI and I wonder how to solve the problem.
If I make modification to source language (perhaps to .pot??) , the changes has to show up on all other .po files. I guess I can make changes to all .pot and .po files manually and push it to repository and "pull" from Weblate but it seems way to much work involved doing this manually and it's error prone.

And will there be a way to do this from the UI directly in the future?

Thank you very much for the help.

Cheers!

-chris

**Comment by nijel** [comment]
If you're using bilingual translation files, then you're out of luck (it usually means that the source string is included in the source code). With monoiingual ones, you should be able to edit source strings (unless you disable this option).

**Comment by blackspotent** [comment]
Hi, Nijel, Thanks for the reply.

Hmm..
Let say I use monolingual translation and I need to add/remove an entry? Doesn't monolingual have the same problem adding or changing the ID itself as bilingual? 
Monolingual seems to have the same property as Bilingual Translation in that it uses ID instead of Source String. It's like Source String promoted to ID and Source Language demoted to becomes just another language. I'm not even sure if we even need Source Language. It become a logical concept and any language(your native language) could be thought of as Source Languae, no?

I still need to figure out how to add/delete an translation entry and also modify the ID/Source String. I think this is very common usecase of translation work, right? Who would make all translation list at once? New entries are constrantly made and they may also be modified during the course of translations.  Unfortunately, I seems like it's not possible within Weblate.

If it can't be done within Weblate could you please explain how this can be done properly? My initial thought is that it seems quite complicated and error prone. As adding/modifying entry may casue conflict with existing translation and it's probably simpler to "Reset" from the repository and strat fresh every time after any modification to entries is made. But  I'm not sure resetting may case problem for History or Comments in Weblate. Also when an entry is modfied, I would like to know if there is a way to notify the translator to let him/her know just about the modified entries.  
If we can do this within Weblate, we can easily handle them including notifications. I really hope that you would make this possible in the near future. 
Well. in the mean time, I would really appreciate if you can explan the work flow. 
Sure, I'll use monolingual if it will make it simpler.

Thank you very much for your help and the wonderful product.

Cheers!

-chris

**Comment by nijel** [comment]
Weblate is just an interface for translating, so it does not handle adding/removing strings from the project. This is usually something what is done by the developers. With monolingual translations, you usually have one master file they adjust (in English) and translators then add it to the translated ones. With bilingual translations, the strings are usually extracted from the source code (eg. using xgettext) and then the translation files updated to match new strings (eg. msgmerge).

This is somewhat described in our documentation as well: https://docs.weblate.org/en/latest/admin/continuous.html

**Comment by nijel** [comment]
You can now allow adding new source strings in the component configration, see https://docs.weblate.org/en/latest/admin/projects.html#manage-strings

**Comment by xoxfaby** [comment]
What about modification? Is there a setting I'm missing to be able to do this? I feel like it should be possible to change a source string across all languages so I don't have to add a new source string and then copy the value from each language.
