### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by quinox** [nijel/weblate#893]
When updating a translation I see the following in the info.log file:

> 2015-10-26 16:01:50,053 INFO root:45 proc=25412 thread=139745800910784 Using Python PO
> 2015-10-26 16:02:38,996 WARNING py.warnings:1282 proc=25418 thread=139745800910784 virtual/local/lib/python2.7/site-packages/django/db/models/fields/__ init __.py:1282: RuntimeWarning: DateTimeField Translation.lock_time received a naive datetime (2015-10-26 16:03:38.993160) while time zone support is active.

Directly followed by a 500 error page:
```python
Internal Server Error: /translate/bjj-fightgear/django/nl/
Traceback (most recent call last):
  File "virtual/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "virtual/local/lib/python2.7/site-packages/weblate/trans/views/edit.py", line 474, in translate
    user_locked = translation.is_user_locked(request.user)
  File "virtual/local/lib/python2.7/site-packages/weblate/trans/models/translation.py", line 295, in is_user_locked
    elif self.lock_time < datetime.now():
TypeError: can't compare offset-naive and offset-aware datetimes
```

My requirements.txt:
```
Django==1.7.10
Weblate==2.4
pytz==2015.6
six==1.10.0
Python 2.7.6
```

I have ```USE_TZ = True``` in my settings.

**Comment by nijel** [comment]
Weblate does not (yet) nicely play with USE_TZ = True, see #892.
