### ISSUE TITLE
uwsgi via nginx for domain subdirectory

### ISSUE THREAD

**Issue by TimKraemer** [nijel/weblate#895]
Hey there,
weblate runs perfectly on domain root. But now I'm trying to get it installed in a subdirectory of my domain. e.g. `domain.tld/weblate`.

I'm receiving:
```
DoesNotExist at /
Site matching query does not exist.
```

nginx.conf
```
    location /weblate { try_files $uri @weblate; }
    location @weblate {
        include uwsgi_params;
        uwsgi_pass unix:/tmp/weblate_uwsgi.sock;
        uwsgi_read_timeout 3600;
        uwsgi_param SCRIPT_NAME /weblate;
        uwsgi_modifier1 30;
    }
```
from settings.py
```
URL_PREFIX = '/weblate'
```

Nginx should forward the subfolder info via `SCRIPT_NAME` parameter so Django should see it. The `URL_PREFIX' should do the rest. Did I forget something?

error log here: http://dpaste.com/1QDHFZV

**Comment by nijel** [comment]
What is your setting for ``SITE_ID`` in settings.py? If you have changed it, you will have to define the site object by running ``./manage.py changesite --site-id=SITE_ID --set-name=NAME``.

**Comment by TimKraemer** [comment]
`./manage.py changesite --site-id=1 --set-name=weblate` was the solution! Thank you!

**Comment by nijel** [comment]
I wonder why it was non existing, Django should have created it on database setup...
