### ISSUE TITLE
Moving a component to another project drops all suggestions

### ISSUE THREAD

**Issue by wichert** [nijel/weblate#896]
I had an unfortunate situations recently: as part of some reorganising I recently moved a component to another project in a weblate instance. After doing this we discovered that all suggestions for texts in that component were lost, resulting in a lot of lost work.

**Comment by nijel** [comment]
Unless you've manually executed cleanup, the suggestions are still in the database. The problem is that Weblate doesn't track them per component, but rather per project, so it's quite complex to determine matching suggestions. (And honestly I've not realized need to handle this at component move.)

However something like this (to be executed in ``./manage.py shell``) should recover your suggestions (completely untested code):

```python
from weblate.trans.models import Suggestion, Project

old_project = Project.objects.get(slug='old')
new_project = Project.objects.get(slug='new')

for suggestion in Suggestion.objects.filter(project=old_project):
    Suggestion.objects.create(
        project=new_project,
        target=suggestion.target,
        user=suggestion.user,
        language=suggestion.language,
    )
```

**Comment by wichert** [comment]
Suggestions are stored in the `trans_suggestion` table I assume? That table is empty, so somewhere along the line those suggestions must have been removed.

**Comment by nijel** [comment]
Yes, that's it. Maybe you have the cleanup job in the cron (what is recommended setup).

**Comment by wichert** [comment]
I do indeed - there is a daily crontab which runs `cleanuptrans`.

**Comment by nijel** [comment]
Also if you have database backups, you can restore just the suggestions table and use the above script to link it to new project...

**Comment by wichert** [comment]
Unfortunately I was an idiot and hadn't realised that people were adding data that wasn't saved out to the PO files, so I never setup database backups :(

**Comment by wichert** [comment]
I did manage to find a system backup which works. Can I also do this at the SQL level by just changing the `project_id` column?

**Comment by nijel** [comment]
Yes, that should work as well (the above code did copy the suggestions, but as you have none which were left in the old one, changing project_id will work fine).

**Comment by wichert** [comment]
That Python trick did not seem to work fully: Weblate now shows there are messages with suggestions, but when you look at the message itself it doesn't show a suggestion.

**Comment by nijel** [comment]
Indeed I've missed one field in the code:

```python
from weblate.trans.models import Suggestion, Project

old_project = Project.objects.get(slug='old')
new_project = Project.objects.get(slug='new')

for suggestion in Suggestion.objects.filter(project=old_project):
    Suggestion.objects.create(
        project=new_project,
        target=suggestion.target,
        contentsum=suggestion.contentsum,
        user=suggestion.user,
        language=suggestion.language,
    )
```

**Comment by wichert** [comment]
Thanks, that worked.
