### ISSUE TITLE
Install on openshift with mysql gives error code 504

### ISSUE THREAD

**Issue by Peakhunter** [nijel/weblate#903]
The install did not complete.
rhc -aweblate app create -t python-2.7 -t mysql-5.5 --from-code https://github.com/nijel/weblate.git --no-git --scaling

**Comment by nijel** [comment]
Any console log? Any error log?

**Comment by cmyk** [comment]
I just got: Creating application 'weblate' ... Server returned an unexpected error code: 504
And now it seems to go through but hangs with this:
```
Waiting for your DNS name to be available ...     retry # 1 - Waiting for DNS: weblate-peakhunter.rhcloud.com
    retry # 2 - Waiting for DNS: weblate-peakhunter.rhcloud.com
    retry # 3 - Waiting for DNS: weblate-peakhunter.rhcloud.com
    retry # 4 - Waiting for DNS: weblate-peakhunter.rhcloud.com
    retry # 5 - Waiting for DNS: weblate-peakhunter.rhcloud.com
    retry # 6 - Waiting for DNS: weblate-peakhunter.rhcloud.com
    retry # 7 - Waiting for DNS: weblate-peakhunter.rhcloud.com
```

**Comment by cmyk** [comment]
Now it ran through, after trying like a dozen times. I seems openshift is not very stable.

**Comment by nijel** [comment]
Hmm, it really doesn't look like problem in anything we can influence...

**Comment by cmyk** [comment]
Now it went through with setting up the app but is stuck with installing weblate:
```
Executing 'pip install -U -r /tmp/requirements.txt'
    Running setup.py install for Django
    Running setup.py install for Whoosh
    Running setup.py install for translate-toolkit
    Running setup.py install for lxml
```
Jeez, is this service usable at all?

**Comment by cmyk** [comment]
Now, for some unknown reason, the installation went through and I was able to log into weblate with the admin user.
This only worked with the sqlite install so far.
But the performance report page shows a red sign for Database backend: django.db.backends.sqlite3

Btw. documentation links are all broken.

**Comment by cmyk** [comment]
When I use this command:
```rhc -aweblate app create -t python-2.7 -t mysql-5.5 --from-code https://github.com/nijel/weblate.git --no-git```

it's just hangs building the lxml.etree extension:
```
      building 'lxml.etree' extension
      gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/libxml2 -I/var/lib/openshift/5630e19189f5cf79930000d7/app-root/runtime/dependencies/python/virtenv/build/lxml/src/lxml/includes -I/opt/rh/python27/root/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
```

**Comment by suspect-zero** [comment]
I believe that this is due to the amount of memory that is available on the small gear (512MB), also take into consideration that some of the memory for that gear is going towards running mysql, which leaves less for python to use.  I was able to install weblate on a medium gear without issue.  When trying to install it on a small gear, i could not even ssh into the gear while it was running the python install script(s), the gear also showed "site unavailable" a few times and takes considerably longer to even try to install.  I would suggest only running this web application on a medium (or possibly larger) gear size due to it's memory usage.

**Comment by cmyk** [comment]
@suspect-zero thanks. That makes sense.
