### ISSUE TITLE
How to translate iOS .lproj

### ISSUE THREAD

**Issue by cmyk** [nijel/weblate#905]
I am trying to add files to weblate from our git repo.
I used *.lproj/Localizable.strings 
![screen shot 2015-10-28 at 17 34 31](https://cloud.githubusercontent.com/assets/62413/10796013/926a3784-7d9c-11e5-9501-0956049cb6b3.png)

It takes forever for the page to finally *not* load (I get a proxy error from openshift). And the component isn't added at all.
tail -f app-root/logs/python.log  shows this:
```
[Wed Oct 28 16:43:24 2015] [error] INFO peakhunter/peakhunter-ios: update took 0.24 seconds:
[Wed Oct 28 16:43:24 2015] [error] INFO:weblate:peakhunter/peakhunter-ios: update took 0.24 seconds:
[Wed Oct 28 16:43:24 2015] [error] DEBUG peakhunter/peakhunter-ios: update: Fetching origin
[Wed Oct 28 16:43:24 2015] [error] DEBUG:weblate:peakhunter/peakhunter-ios: update: Fetching origin
[Wed Oct 28 16:43:24 2015] [error] INFO peakhunter/peakhunter-ios: merge remote into repo
[Wed Oct 28 16:43:24 2015] [error] INFO:weblate:peakhunter/peakhunter-ios: merge remote into repo
[Wed Oct 28 16:43:24 2015] [error] INFO peakhunter/peakhunter-ios: checking Base.lproj/Localizable.strings (Base) [1/10]
[Wed Oct 28 16:43:24 2015] [error] INFO:weblate:peakhunter/peakhunter-ios: checking Base.lproj/Localizable.strings (Base) [1/10]
[Wed Oct 28 16:43:24 2015] [error] INFO peakhunter/peakhunter-ios/base: processing Base.lproj/Localizable.strings, revision has changed
[Wed Oct 28 16:43:24 2015] [error] INFO:weblate:peakhunter/peakhunter-ios/base: processing Base.lproj/Localizable.strings, revision has changed
```

I have no clue how to handle the html files with weblate.

**Comment by nijel** [comment]
Not sutr how your project is set up, but usually the configuration is:

File mask:    ``Resources/en.lproj/Localizable.strings``
Monolingual base language file:     ``Resources/*.lproj/Localizable.strings``

**Comment by Peakhunter** [comment]
Thanks Michal. I figured it out, and it's working fine with the Localizable.strings.
What would be the best way to handle those html files?

**Comment by nijel** [comment]
You need some means to extract the translatable content from them, I'd try po4a for that.
