### ISSUE TITLE
base (generated)

### ISSUE THREAD

**Issue by cmyk** [nijel/weblate#909]
Why is there a base (generated)?
And how do I get rid of it?
![screen shot 2015-10-29 at 14 52 33](https://cloud.githubusercontent.com/assets/62413/10820294/c0d19486-7e4c-11e5-8ceb-81beab168183.png)

**Comment by nijel** [comment]
The ``base`` string was matched in the file mask as the language, and Weblate generated language definition for that...

**Comment by cmyk** [comment]
Sorry about that. I still have a lot to learn. Great project, btw.
