### ISSUE TITLE
Giving user access to subproject

### ISSUE THREAD

**Issue by blackspotent** [nijel/weblate#912]
Hi, after struggling to set them up, I finally got it ready for our translator to use our system.
We have several publisher woking on the translation for different languages and they shouldn't be able to access each other's translation.
However, Korean and English(for development) are common so that they can share them.

Is there way to make user permission to subprojects? It seems quite basic functionality when there are multiple translator working on at the same time.

I don't want to setup multiple project yet because it probably means having multiple repository and duplicating Korean and English to each repository, making maintenance difficult. 

Thank you very much for your help.

Cheers!

-chris

**Comment by nijel** [comment]
You can always share the repository (weblate://project/component). Anyway ACL per component is indeed not yet there, we need to think more about extending permission system (see #868 or #867).

**Comment by blackspotent** [comment]
Thank you very much.

I’ll take a look sharing repository.
I tried Zanata, Pootle and others but Weblate is the best and the most stable. Any addition will make it even better.
One feature I really miss is to add/delete/modify translation entries as entries can be added/deleted/modified throughout the life cycle of translation.
Currently I’m doing all kinds of things manually and it’s very difficult to use.
I hope it’s not an impossible feature to add. ^^

Cheers!

-chris


[cid:image001.png@01D1133F.CA3CE1B0]
BLACK SPOT Entertainment Inc.
Chris Kim | CEO | E-mail : chris@blackspotent.com<mailto:chris@blackspotent.com> | Mobile : +82-10-7195-1901
Web : www.blackspotent.com<http://www.blackspotent.com/> | Tel : +82-31-8017-8560 | Fax : +82-31-8017-8561
GyeongGi-Do BunDang-Gu, PanKyoYuk-Ro 230 SamHwan-Hipex B-Tower #817, Korea

**Comment by blackspotent** [comment]
Hi, Nijel, 
Any chance that subproject permission being implmented soon?

Cheers!

**Comment by nijel** [comment]
It's not on roadmap for 2.5, so most likely it won't be implemented this year.

**Comment by blackspotent** [comment]
Sigh... I see.. It's pretty critical for us and I hope it will be part of 2.6. ^^ 
Cheers!

**Comment by nijel** [comment]
Everybody has different priorities :-). For me the priority is what is needed for Hosted Weblate and especially for paying customers there...

**Comment by blackspotent** [comment]
Sure. Understood. ^^

**Comment by nijel** [comment]
Please check if PR #963 does what you want and if it does not, suggest changes so that it would fit your use case.

**Comment by nijel** [comment]
I believe that #963 did implement all what is needed.
