### ISSUE TITLE
Rename html to templates folder, use subfolder

### ISSUE THREAD

**Issue by quinox** [nijel/weblate#918]
I load Weblate from my virtual. This works great, three suggestions to make it even better:

* Weblate's template folder should be called `templates` so it's automatically picked up by Django (saves me the trouble of having to use the `TEMPLATE_DIRS` variable)

* More blocks in templates to override. For example, blocks inside the navbar's and tools' dropdown elements would make it easier to add links to non-weblate pages without having to override the whole `index.html`/`project.html` files. On the login page it would be nice to have a block in the right column for custom elements. F.E.:
```html
{% extends "weblate/index.html" %}
{% block tools_menu %}
    <li>My custom first link</li>
    {{ block.super }}
    <li>My custom last link</li>
{% endblock %}
```
 
* The templates should be inside a subfolder, fe `weblate/templates/weblate/index.html`. This way it's clear when I'm overriding a template where it originally came from.

**Comment by nijel** [comment]
The html name comes from old Django, where it was default. I've never bothered to change it :-). All changes you suggest seem okay to me...
