### ISSUE TITLE
Example for monolingual CSV files

### ISSUE THREAD

**Issue by TimKraemer** [nijel/weblate#924]
Hi,
I'm desperately trying to import some monolingual CSV files, but I'm failing to find a working format, it recognizes only the last line of my CSV.
It would be nice, if you could provide me two working mono-lingual csv file as an example.

My approaches:
I had success with bilingual CSV files looking like this (tab seperator, end-of-line: newline, no quoting):
```
ID(1)	english text one	german text eins
ID(2)	english text two	german text zwei
```

But no success with mono-lingual:
```
ID(1)	english text one
ID(2)	english text two
```
```
ID(1)	german text eins
ID(2)	german text zwei
```

I  tried adding headers, no change:
```
source	translation
ID(1)	english text one
ID(2)	english text two
```

I tried quotations and comma seperators, stilll only the last line
```
"source","translation"
"ID(1)","english text one"
"ID(2)","english text two"
```

**Comment by nijel** [comment]
What Weblate and translate-toolkit versions do you use? Weblate 2.4 did bring some improvements in CSV support...

**Comment by TimKraemer** [comment]
I'm testing with the latest git version:
```
./manage.py list_versions
 * Weblate weblate-2.4-254-ga1d0b28
 * Python 2.7.6
 * Django 1.8.5
 * python-social-auth 0.2.13
 * Translate Toolkit 1.10.0
 * Whoosh 2.5.7
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.3.3
 * django-crispy-forms 1.5.2
 * compressor 1.5
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 2.8.2
```

**Comment by nijel** [comment]
I've added some CSV files to testsuite and they seem to work fine:

https://github.com/nijel/weblate-test/tree/master/csv-mono

Though they are using comma and not tabs as your ones.
