### ISSUE TITLE
Failed to update repository: fatal: bad revision 'origin/master..' (128)

### ISSUE THREAD

**Issue by ddxdental** [nijel/weblate#925]
Trying to add a second component and received the following error:

`Failed to update repository: fatal: bad revision 'origin/master..' (128)`

Not sure what is going on. What I do know is that the first component I added is using all the same git repository URLs and branch as the second, and the first added with no issue.

I do see the component directory added to the file system (data/vcs/project/component) along side my first component. The directory does contain a .git working directory. The app log file contains nothing alarming:

```
2015-11-06 14:32:26,478 INFO project/component: updating repository
2015-11-06 14:32:27,335 INFO project/component: update took 0.86 seconds:
2015-11-06 14:32:27,337 DEBUG project/component: update: Fetching origin
```

If I do a git pull from the shell in the new component directory, it pulls in the data and then the component adds in the weblate admin UI.

Any tips?

Thanks,

Mike

**Comment by ddxdental** [comment]
Bah!

Doing a pull req from the command line doesn't resolve the issue.  I get the following error when accessing this component from the Weblate UI:

`fatal: no upstream configured for branch 'master' (128)`

It doesn't help that I'm pretty new to git.

Thanks,

Mike

**Comment by ddxdental** [comment]
Doing a `git push -u origin master` seems to clean things up

**Comment by nijel** [comment]
Can you please provide some version infomation (at least Weblate and Git, you can collect all using ``./manage.py list_versions``)?

**Comment by ddxdental** [comment]
* Weblate weblate-2.4-264-g9ac3501
 * Python 2.7.10
 * Django 1.7.9
 * python-social-auth 0.2.1
 * Translate Toolkit 1.12.0
 * Whoosh 2.7.0
 * Git 2.5.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.2
 * lxml 3.4.4
 * django-crispy-forms 1.5.2
 * compressor 1.5
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.4

**Comment by SamanthaAdrichem** [comment]
I had this issue in the latest version, it happend to me because i didn't fill in the repository branch field. When i did that, all was fine.

**Comment by nijel** [comment]
Keeping branch empty should work fine, I've recently set up several repos like that. However there were some fixes in git meanwhile, which are not part of 2.5...
