### ISSUE TITLE
Import Complex Sphinx Translations into Weblate

### ISSUE THREAD

**Issue by ddxdental** [nijel/weblate#926]
X-posting a question from Stackoverflow (hope that is not annoying, not sure if they key Weblate folks check out that spot) http://stackoverflow.com/questions/33592779/import-complex-sphinx-translations-into-weblate

I'm using `import_project` to bring in components from a sphinx document set.  Where this is falling apart is my sub directory structure:

     - docs
      - _locale
       - fr
        - LC_MESSAGES
         - file.po
         - file2.po
          - directory
           - file.po
           - file2.po        
          - directory2
           - file.po
           - file2.po

The import command `./manage.py import_project --file-format po project-name git@bitbucket.org:xxx/xxx.git master 'docs/_locale/*/LC_MESSAGES/**.po'` doesn't look at the `directory` and it's sub files.  Further because the sub directory files has like named files, there is a conflict how the `import_project` would map files to components (if I run `import_project` for each sub directory).
 

Any tips?

Thanks,

Mike

**Comment by nijel** [comment]
If there is not many directories, you can do this in several imports, but there is no way to do this in one command right now.
