### ISSUE TITLE
Wrong pt_BR support on weblate instances

### ISSUE THREAD

**Issue by elchevive** [nijel/weblate#929]
Hi,

When I go to weblate official site (weblate.org), it displays the page in pt_BR correctly.

If I go to a weblate instance (be hosted.weblate.org or l10n.opensuse.org) it display the page in pt (not pt_BR). After registering and changing the user configuration to pt_BR, all works well.

Regards

**Comment by nijel** [comment]
So it's just the autodetection that fails. Once you choose language manually, everything is correct?

**Comment by elchevive** [comment]
Yes, its the autodetect only.

On official site its OK, on the translations sites it's wrong
