### ISSUE TITLE
Download the whole project from the application to the desktop to store the folder structure

### ISSUE THREAD

**Issue by collex100** [nijel/weblate#931]
Please tell me, is it possible to download (from the application to the desktop) whole project translation to store the folders structure and files translation?

**Comment by nijel** [comment]
Maybe it's better to directly download the VCS repository? What are you trying to achieve?

**Comment by collex100** [comment]
I want that any user can download the current translating directly from Weblate. Otherwise, it should be done continuously by hand. :(

**Comment by nijel** [comment]
The translations can be downloaded in the Files menu for every translation...

**Comment by collex100** [comment]
Yes I know. But it is necessary to do each file individually. Not practical. One click to download whole project (300 files and folders). And one click upload to the application was translated.

**Comment by nijel** [comment]
In this case, it might be simply better to use the repository directly. Maybe I'm just missing the point here...

**Comment by collex100** [comment]
I do not understand your answer. :) Make a download the whole project with one button, Is it possible?

**Comment by nijel** [comment]
Why just don't download it from the upstream repository? I don't want to turn Weblate into distributing platform (witj possible bandwidth consequences).

**Comment by collex100** [comment]
I understood. OK. Thank you! I will do as you advise.

**Comment by elchevive** [comment]
Hi,

Sorry for commenting on an closed question, but I get the point that collex100 asked. For example, openSUSE is deploying weblate as its only translation system (https://l10n.opensuse.org/). Many files we translate comes from different git repositories (right now, ~10, but it will increase when the change finish)

Sometimes we, the language coordinators do some quality manteinance in some files here and there. For this it's better to have the files offline (just like we have right now, a svn with all .po files). In Weblate you can download a file, one by one, and has to upload it one by one. 

It would be very nice to allow donwload all files from a particular language and upload them back after this 'manteinance'.
https://lists.opensuse.org/opensuse-translation/2016-03/msg00040.html

Regards,

Luiz

**Comment by nijel** [comment]
Weblate 2.6 will have API, which (in connection with client scripts) I believe will be better fit for such tasks than web interface. See #416
