### ISSUE TITLE
Add/Delete/Modify Translation Entry

### ISSUE THREAD

**Issue by blackspotent** [nijel/weblate#934]
Hi, I'm promoting this as a feature request from my other emails.

I think this will save us huge amount of time creating a custom tool to workaround the problem.

> As the title say, one feature I really miss is to add/delete/modify translation entries as entries can be  added/deleted/modified throughout the life cycle of translation. Currently I’m doing all kinds of things  manually and it’s very difficult to use. I hope it’s not an impossible feature to add. ^^ 

Cheers!

**Comment by nijel** [comment]
I believe there is already https://github.com/nijel/weblate/issues/884 covering this.
