### ISSUE TITLE
(Doc) collectstatic --link possibly troublesome (symlinks)

### ISSUE THREAD

**Issue by mchubby** [nijel/weblate#935]
Hello,

The installation documentation at ``docs/admin/install.rst``provides instructions for serving static files.

``./manage.py collectstatic --noinput --link`` creates symlinks in the STATIC_ROOT tree.

It would be insightful to caution about the consequences of using links, because some webservers will refuse to serve them, even if the target is valid. An extra paragraph suggesting to run the same command without --link would be welcome IMHO.

The only drawback I can think of is that files in this directory may become out of sync when Django or other components are upgraded, until you run the command again.

**Comment by nijel** [comment]
Indeed using the command without --link is probably safer choice...
