### ISSUE TITLE
Punctuation for Bodo (brx)

### ISSUE THREAD

**Issue by achadwick** [nijel/weblate#940]
Could Devanagari punctuation be added for `brx` and possibly other languages which use Devnagari? The buttons are only showing English punctuation and other special characters for me (en_GB.UTF-8).

I've noticed that in the absence of nice punctuation buttons, our translator(s) sometimes use `U+007C | vertical line` in place of [danda or doublle danda](https://en.wikipedia.org/wiki/Danda). See <https://hosted.weblate.org/translate/mypaint/mypaint/brx/?checksum=2c56907bc6cb3516dbf2eb5ec1548bed>. Because this is happening, sometimes the trailing stop check is triggered at times when the translator has written something that must read correctly to them: <https://hosted.weblate.org/translate/mypaint/mypaint/brx/?type=allchecks>.

This may just be a case of the correct script not being associated with the language.

It may be a good idea to allow `|` for `।`, and `||` for `॥`, but I can't read or write Devanagari - I'm not sure how much of a hack this would be.

**Comment by nijel** [comment]
The special chars definitions is in separate file, so it's quite easy to adjust: https://github.com/nijel/weblate/blob/master/weblate/trans/specialchars.py

**Comment by achadwick** [comment]
They're full-stop and comma equivalents, roughly. Which file is used for variants of those? specialchars.py seems to be all about quotes and dashes.

**Comment by nijel** [comment]
It should include these as well - it just that no language needed them so far...

**Comment by nijel** [comment]
Sorry, closed wrong issue by the commit.
