### ISSUE TITLE
Empty translation is exported as empty string for android project

### ISSUE THREAD

**Issue by mkaiser30** [nijel/weblate#942]
Hi,

in my android project I have some not yet finished translations. Unfortunately these are exported to git with an empty string as value.

Is there a possibility to not export these strings at all? Then the app would just use the default string.

- Martin

**Comment by nijel** [comment]
When did this happen? The file should be created empty by Weblate (see eg. https://gitlab.com/agilob/sudokusolver/commit/1879118d5977d064bbfe2a0e91087006ed830c3f) and translations are added to it once they are edited.

**Comment by mkaiser30** [comment]
oh, then it could be that this was my fault. When I was going through the translations step by step it could be that I hit Alt+Enter instead of Alt+PgDn.

But thanks for clarification.

**Comment by nijel** [comment]
Hmm, but that still should not save empty string in this case...

**Comment by mkaiser30** [comment]
Ok, i will try to support you with this. Unfortunately I can't remember exactly what I did.
I can have a look into DB or whatever you think is required.

I have weblate 2.3 from bitnami

**Comment by nijel** [comment]
I have pretty clear idea why it did happen, so no need for more information, but thanks for the offer :-).
