### ISSUE TITLE
Custom own checks have to be put in the weblate/trans/checks module

### ISSUE THREAD

**Issue by lln-ijinus** [nijel/weblate#948]
Because of the __init__.py in the weblate/trans/checks module, custom checks must be put this module.

I explain : to create check you need to import a class from this module (for example from weblate.trans.checks.base import TargetCheck), but when you do this, the 'CHECKS' array is created from the CHECK_LIST setting, before the new class is created and so it can't find this new class.
If the check class is in the  weblate/trans/checks module it is ok, but that's all !

At least it could be mentioned in the doc (http://weblate.readthedocs.org/en/weblate-2.4/admin/checks.html#writing-own-checks), but I think it would be better to find another way to build the CHECK array.

**Comment by nijel** [comment]
This rather should be fixed. I didn't realize this when writing the loader...

**Comment by lln-ijinus** [comment]
Ok, thanks !
And also thanks a lot for this piece of software and all the doc
