### ISSUE TITLE
No match percentage is given for fuzzy matches.

### ISSUE THREAD

**Issue by shanewims** [nijel/weblate#952]
For billing purposes, high fuzzy percentage matches cost less to translate than low fuzzy translation matches.

High fuzzy match = 95%-99%
Low fuzzy match = 75%-94%

(although these figures should be user configurable)

There is no indication in Weblate of whether a string is a high fuzzy or low fuzzy match. This information should also be captured in total wordcount statistics for the project.

(Feedback from translation vendor)

**Comment by nijel** [comment]
This information is usually not available in the underlaying translation file, so Weblate has no clue about that...
