### ISSUE TITLE
Unable to save when JSON entry is empty or missing

### ISSUE THREAD

**Issue by msteiger** [nijel/weblate#955]
I'm trying to translate JSON-based content based on two files: [menu.lang](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/i18n/menu.lang) has all IDs and [menu_gl.lang](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/i18n/menu_gl.lang) contains the actual translations.

Now, if the entry does not exist or the value string is empty in the menu_gl.lang file, the save action does not write the translated string to the menu_gl.lang file - it silently hops to the next entry:

![image](https://cloud.githubusercontent.com/assets/1820007/11816389/8181bcba-a350-11e5-88bd-969116912123.png)

A similar problem that could be related is that a new file `menu_ja.lang` is not recognized as a new language.

Disclaimer: this issue occurs in **Weblate 2.1** - I could not find any related commits since then though.

**Comment by nijel** [comment]
There has been quite a lot of fixes for JSON support meanwhile, so it's possible that it's already fixed...

**Comment by msteiger** [comment]
Great - I will report back as soon as Weblate 2.5 is out.

**Comment by nijel** [comment]
Tried to test this and it seems to be fixed.
