### ISSUE TITLE
Unable to create initial database structure

### ISSUE THREAD

**Issue by msteiger** [nijel/weblate#956]
I followed the installation guide for Weblate 2.4 on a CentOS 7 VM by installing the weblate package through pip. There are two issues with it:

* the `manage.py` file was missing. I copied it from the 2.4 source files.
* Launching `./manage.py -migrate ` gives me "Table 'weblate.trans_project' doesn't exist"

The "weblate" database exists and the user privileges are granted as described in the docs. When I create a dummy table with HeidiSQL the error changes to "Unknown column 'trans_project.id' in 'field list'". It seems to be able read from the DB connections.

Stacktrace (shortened):

    File "/usr/lib/python2.7/site-packages/weblate/sitemaps.py", line 27, in <module>
      'queryset': Project.objects.all_acl(None),
    File "/usr/lib/python2.7/site-packages/weblate/trans/models/project.py", line 46, in all_acl
      return self.get_acl_status(user)[0]
    File "/usr/lib/python2.7/site-packages/weblate/trans/models/project.py", line 62, in get_acl_status
      project.id for project in projects if project.has_acl(user)
    
Full stacktrace here: http://pastebin.com/FH1BJUHf

**EDIT**: the problem occurs for both MySQL and sqlite3

**Comment by msteiger** [comment]
I used the create table query from an existing Weblate 2.1 installation to create the `trans_project` table:

    CREATE TABLE IF NOT EXISTS `trans_project` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(100) NOT NULL,
    `slug` varchar(50) NOT NULL,
    `web` varchar(200) NOT NULL,
    `mail` varchar(75) NOT NULL,
    `instructions` varchar(200) NOT NULL,
    `push_on_commit` tinyint(1) NOT NULL,
    `set_translation_team` tinyint(1) NOT NULL,
    `enable_acl` tinyint(1) NOT NULL,
    `enable_hooks` tinyint(1) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `name` (`name`),
    UNIQUE KEY `slug` (`slug`)
    ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

Then, the migrate scripts starts off with several deprecation warnings and crashes at

```
Operations to perform:
  Apply all migrations: lang, sessions, admin, sites, auth, default, contenttypes, accounts, trans
Running migrations:
  Rendering model states... DONE
  Applying lang.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying trans.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
    django.db.utils.OperationalError: (1050, "Table 'trans_project' already exists")
```

I can debug some more, but I need some advice on where to look or what to try.

**Comment by nijel** [comment]
This problem should be fixed since 9f09814f0ec328855f8e2247f4c2a49fee889b53. It didn't happen earlier as behavior of Django 1.9 has changed in this and it now triggers the bug.

**Comment by msteiger** [comment]
Ah great - thanks! Will weblate 2.5 be released soon (in 2015)?

btw: the missing `manage.py` file could still be an issue

**Comment by nijel** [comment]
The manage.py is installed as weblate to /usr/bin (or /usr/local/bin), however installation using pip is not really covered by our docs to mention this...

**Comment by nijel** [comment]
Created #962 to track the documentation issue.

**Comment by msteiger** [comment]
I just checked again and it isn't in any of those locations. The only hit on the entire filesystem is the Django template file:

    /usr/lib/python2.7/site-packages/django/conf/project_template/manage.py

**Comment by nijel** [comment]
It's installed either as /usr/bin/weblate or /usr/local/bin/weblate (depending on default prefix for pip you have).

**Comment by msteiger** [comment]
Oh - that's right! I didn't realize that it was renamed - thanks!
