### ISSUE TITLE
question about github hooks

### ISSUE THREAD

**Issue by ahmedre** [nijel/weblate#959]
hi,
apologies in advance, this is more of a question - i am trying to get notifications from github when my project changes so that weblate can update. i added a hook, and can confirm in the logs that i am getting the request with a 200 response code:

```
192.30.252.45 - - [17/Dec/2015:01:01:24 -0500] "POST //hooks/github/ HTTP/1.1" 200 63 "-" "GitHub-Hookshot/35ff2c9"
```

however, i get no updates (i.e. repository status stays the same, etc). note, however, that if instead, i (manually) do:

```
curl -i http://{weblate_url}/hooks/update/project_name/[component_name]/
```

then i also get a 200, and correctly get the update after some time (after i changed the repository method to rebase instead of merge, that is). am i missing something for making the github hook work? as far as i know (and i could be mistaken), you added `/hooks/github` as a `POST` only endpoint for github. is it because my github `user/project` are different than `project_name/component_name` maybe?

thanks!

**Comment by nijel** [comment]
The matching is done based on repository URL. You can check server logs, to find out which one triggered the update and check your translation component setup if that matches...
