### ISSUE TITLE
How do I store multi-line string as singlel-ine strings in .po file?

### ISSUE THREAD

**Issue by chrisk414** [nijel/weblate#961]
Hi, I have a source .po file with msgstr string with single-line string.
For example, 
msgid "test"
msgstr "Hi\n There!"

Weblate will import thin as multi-line string and when I export .po file I get the followings.

msgid "test"
msgstr ""
"Hi\n"
"There1"

How do I get back the string in original form? 

Thank you very much for your help. (I'm using weblate v2.3)

-chris

**Comment by nijel** [comment]
You can use pre commit hooks to fix this - examples/hook-unwrap-po, see https://docs.weblate.org/en/latest/admin/config.html#pre-commit-scripts

**Comment by chrisk414** [comment]
Hi, Nijel, 

I took a look at the hook and it uses msgcat command with --no-wrap option. 
It seems like msgcat will split the string into multiple line no matter what if the string contains "line break" in the original string. What I would like is to output it as single-line with "\n" in it. 

Cheers!

**Comment by nijel** [comment]
Hmm, I don't know tool for that then... The problem is that there is no way to tweak output from translate-toolkit (the library we're using for manipulation translation files).

**Comment by chrisk414** [comment]
Well.. that’s ok, I can make a convertor myself. 
Thanks. ^^
-chris
