### ISSUE TITLE
link problem

### ISSUE THREAD

**Issue by whedro** [nijel/weblate#966]
Hi, 

after update project and install all changes, weblate pages are wrong path (css and js files) ..
This is example link ... 
http://<url>/static/CACHE/js/954e12349f17.js

I tried restart apache and memcached service ... but without change.
What I doing wrong ?
Thanks ..

(Mery Christmas and Happy new year for Nijel and everyone) .. :)

Michal

**Comment by nijel** [comment]
Did you follow upgrading instructions? Handling of static files has been changed...

**Comment by whedro** [comment]
Hi,
I tried to use general upgrade instructions .... 'cos upgrade between 2.4 to 2.5 i can't find (if exists).
If you mean change static folder (in 2.4), so I have this change .. in 2.4 work everything OK ...
Michal

**Comment by nijel** [comment]
Indeed the changes were part of upgrade to 2.4, I thought you've upgraded to 2.4 as 2.5 is not yet released. I'm not aware of any related changes in 2.5, maybe you've updated some of the requirements as well?

PS: What is your setting for STATIC_URL? This is what should be used in constructing this URL...

**Comment by whedro** [comment]
Hi nijel,
all changes, what I doing is "git pull" and "./manage.py migrate"...
I looked to commits after begun problem, but I find nothing, what created problem

URL_PREFIX = ''
STATIC_URL = '%s/static/' % URL_PREFIX

**Comment by whedro** [comment]
Sorry, I forgot tell you, I use version 2.5-dev.....

**Comment by nijel** [comment]
What version of django-compressor do you use?

**Comment by whedro** [comment]
django-compressor==1.5

**Comment by nijel** [comment]
That one works fine for me, STATIC_URL looks correct as well. Do you have COMPRESS_URL set?

**Comment by whedro** [comment]
I don't have this parameter in setting.py ..

**Comment by nijel** [comment]
Hmm, I'm running out of ideas what could be wrong. Maybe try asking somebody who knows more about django-compressor....

**Comment by whedro** [comment]
Hi nijel, 
I found it ...
Problem was parameter DEBUG..
I change parameter  DEBUG to False and problem with cache folder was after apache service restart ...
I try to configure weblate again with example file and looked diff between my setting and example ...

Do you know, why is this problem after change parameter DEBUG to FALSE ?
Thanks

Michal

**Comment by nijel** [comment]
Not sure, I'll look at that deeper...

**Comment by whedro** [comment]
Any news ? :)

**Comment by nijel** [comment]
Not yet, busy with other things :-). Anyway it will be quite tricky as it works fine for me with DEBUG enabled...

**Comment by nijel** [comment]
After more testing this seems to be caused by incompatible versions of Django and django-compressor. Using Django 1.9 and django-compressor < 2.0 causes this.
