### ISSUE TITLE
Automatic translation across projects

### ISSUE THREAD

**Issue by Yingminzhou** [nijel/weblate#969]
As described above, I want to reuse some existing translations from previous project, but failed as the description is not so detailed in the document. Could you please offer me some advice so that I can achieve this? Thanks very much.

**Comment by nijel** [comment]
You mean something like [automatic translation](https://docs.weblate.org/en/latest/user/translating.html?highlight=automatic#automatic-translation)?

**Comment by Yingminzhou** [comment]
Yes, but the dictionary comes from another project within the same weblate instance. And what we want to do is to match the sentences in a new project with the same existing sentences in a previous project that we have translated before.
Does weblate offer us such options? I tried the methods described in the document, but I could not see the "automatic translation" button.
If so, could you please offer me some detailed instructions?
Thanks.

**Comment by nijel** [comment]
You need permissions for this, what is not the case by default for regular users.

**Comment by Yingminzhou** [comment]
I logged in as the Admin role, but did not find the button either.
I am so confused.
Thanks for your kind help.

**Comment by Yingminzhou** [comment]
I found the button in the single component, but we can only use the existing components within the same project.
What we want to do is to use the existing components from another project but within the same weblate instance.
Is there any settings that could help us achieve this?
Thanks.

**Comment by nijel** [comment]
Indeed currently this can be used only inside single project, so AFAIK it's visible only if project has more components. Extending it to be able to do this across projects should not be hard.

**Comment by Yingminzhou** [comment]
Thanks. I got it.

**Comment by nijel** [comment]
Providing this as general availability is not a good idea, but having option to use strings from other owned projects sounds like a good idea.
