### ISSUE TITLE
Can a Translation Memory be loaded to the tool for concordance search?

### ISSUE THREAD

**Issue by shanewims** [nijel/weblate#970]
Concordance Search is a translation tool feature which allows the translator to search for a word or phrase and get a display within the translation tool of how this word or phrase has been translated previously. This is to help ensure consistency.
 
Novell Localisation Workbench for example has that feature which allows you to either run a concordance search in a loaded TM or in .nlw’s (the database file format used by Novell Localisation Workbench).

**Comment by nijel** [comment]
Currently this is possible only using [tmdb server](https://docs.weblate.org/en/latest/admin/machine.html#tmserver).

**Comment by nijel** [comment]
The basic translation memory feature (using externally provided TMX data) will be in Weblate 2.20, see https://docs.weblate.org/en/latest/admin/machine.html, more to come in upcoming releases.
