### ISSUE TITLE
similarity strings appear even with empty MACHINE_TRANSLATION_SERVICES 

### ISSUE THREAD

**Issue by vfede** [nijel/weblate#973]
we are on weblate 2.2
we have this issue that keep translating strings with a "similar" string, e.g. it translated the new string "Continue with Facebook" with a previously added string "Log in with Facebook".
We would like to disable this behaviour, but it keeps doing that with MACHINE_TRANSLATION_SERVICES set with an empty array and even when commented out from config.
the fault is because of 'weblate.trans.machine.weblatetm.WeblateSimilarTranslation' enabled somewhere? or something else enabled anywhere? thanks

**Comment by nijel** [comment]
The machine translation does not do any automatic translation, it just gives translator suggestions on bottom of the page. So the translation must be coming from somewhere else - maybe your translation files already contain that?

**Comment by vfede** [comment]
ok thanks for the tips, the fact is, when a new msgid is added in a .PO file, something also add a msgstr from a very similar string and mark it fuzzy. I will investigate more.

**Comment by nijel** [comment]
That's expected - fuzzy strings are for review. Once you generate .MO files, they are not included...

**Comment by vfede** [comment]
yes, that's one solution, but I still can't understand what component executes the similarity search and add the msgstr for a new string, keep searching...

**Comment by nijel** [comment]
msgmerge is doing that by default

**Comment by vfede** [comment]
is there a way to disable this behaviour? we do not want any similar string to be used as translation for new strings. thank you very much for the help untill now.

**Comment by nijel** [comment]
Yes, it has --no-fuzzy-matching...
