### ISSUE TITLE
Apache serving weblates static files

### ISSUE THREAD

**Issue by ptr1120** [nijel/weblate#978]
I have just upgraded to the new version of weblate. Thanks for the great work. The documentation for configuring Apache web server (under: https://docs.weblate.org/en/latest/admin/install.html#running-weblate-under-path) describes the configuration for the static files:
```
<Directory /usr/share/weblate/data/static/>
        Require all denied
 </Directory>
```
But with this configuration the web server gives the error:
"client denied by server configuration: xxx/data/static/weblate-128.png"....

Should the configuration not allow the serving of static files like this:
```
<Directory /usr/share/weblate/data/static/>
Require all granted
 </Directory>
```
, or am I missing something?

Best regards,
peter

**Comment by nijel** [comment]
You're right, I just blindly accepted fix when upgrading syntax from Apache 2.2 to 2.4 as I don't use Apache...
