### ISSUE TITLE
Locked by another user

### ISSUE THREAD

**Issue by sittiesevilla** [nijel/weblate#983]
Hello,

I was wondering if you happen to know how to resolve this in weblate.  Some of my team members are experiencing strings being locked by another user, but when I check it on my end, it is completely accessible and the strings are unlocked.  We have already tried refreshing the page, clearing the cache, and have the other team member log out of weblate, nothing has helped.  Hope you can assist me on this.

Many thanks in advance for looking into this.

Warm regards,
Sittie

**Comment by nijel** [comment]
Currently translation is locked when somebody is editing. This is to avoid people interfering each other work (eg. rewriting translations). See #245 for ideas to improve locking.

**Comment by nijel** [comment]
Also see documentation on this topic: https://docs.weblate.org/en/latest/admin/translating.html#translation-locking

**Comment by sittiesevilla** [comment]
Thanks Michal for looking into this.  What happened is -- when user A opens a string, it prompted him that the string is being locked by another user B.  However, user B has already logged out of weblate to make sure that the strings can be checked/accessed by user A.  But whenever user A opens the strings or saves the translation, weblate informs him that string is locked by user B.  What we did so far is to refresh the page (5 or 6 times), and it enables you to unlock one string.  Then it goes back to strings being locked again.  And when you refresh it again and again and again, you unlock a second string.  So you basically need 1 hour to work on 15 strings.

**Comment by nijel** [comment]
Indeed the locks should be released on logout...

**Comment by sittiesevilla** [comment]
And the weird thing about it is I am able to access the strings and able to save my suggestions/translations without any problem.  Is this something user specific?

**Comment by nijel** [comment]
The locks automatically expire after some time, so you might be looking at the translation later?

**Comment by sittiesevilla** [comment]
Just now, our Italian translator is trying to work on a string but she logged in again, it prompted her that the string is still locked despite the proofreader already logging off and unlocking the weblate.  I am also attaching here a screenshot that is roughly taken at the same time today for your reference.  It also has a screenshot of my dashboard showing strings are completely accessible.
![for michal](https://cloud.githubusercontent.com/assets/15007995/12611648/debb77b4-c528-11e5-8050-dab0207b96a4.png)

**Comment by nijel** [comment]
Will look into that. Just to be sure - do you make the screenshots withing short timeframe? Default lock interval is 60 seconds, so the locks expire quite fast...

**Comment by sittiesevilla** [comment]
We have tried in our Russian Team, waiting for around 3 days -- that was Friday when they noticed the string being locked.  So the translator unlocked the strings, logged off, and closed her window (weblate).  Then on Monday when the proofreader logged in, it said that the strings are locked by the translator.

**Comment by nijel** [comment]
That's really strange, the automatic lock should expire fast...

**Comment by sittiesevilla** [comment]
It's really strange, Michal.  It appears locked on the proofreader's end, but appears unlocked on my and the translator's side.

**Comment by nijel** [comment]
I've improved the locking code to not hold locks for inactive users, hopefully that will help in your situation. I will deploy it to production later today.

**Comment by nijel** [comment]
Changes are now deployed on Hosted Weblate.

**Comment by sittiesevilla** [comment]
Thank you so much, Michal!

**Comment by sittiesevilla** [comment]
Hello again Michal,

It seems like the issue has recurred.  When you updated the locking codes, everything was perfectly okay.  I received feedback from the team that they were able to save translations and click on a string without any problems.  But it seems like the problem has recurred last Friday.  I am attaching here a screenshot of our Russian proofreader where the strings are shown locked but the translator has already logged off weblate since Thursday.  The other screenshot is from our Chinese proofreader who can't also access the strings, but the translator has also already logged off about a week ago.  Hope you can take a look at this.

Many thanks in advance for your help.

BR,
![russian_proofreader](https://cloud.githubusercontent.com/assets/15007995/12720811/77c967ce-c937-11e5-976b-f1d8fb345924.png)
![chinese_proofreader](https://cloud.githubusercontent.com/assets/15007995/12720812/7addebec-c937-11e5-95a6-e22a3b3c76d7.png)


Sittie

**Comment by nijel** [comment]
Should be finally fixed with 618647d417b7f45809b59531cbb09309244d07a0

**Comment by sittiesevilla** [comment]
Thank you, Michal!
