### ISSUE TITLE
Question about Java bundles

### ISSUE THREAD

**Issue by mkjaxxo** [nijel/weblate#985]
Hi Weblate team,

we want to use Weblate within our build process. Is it possible to get several messages.properties and plugin.properties from a Git repo for one component?
Currently we understand the concept this way that we need one base file with all available strings as template file. But we do not have such a file. We only have a folder structure with messages.properties and plugin.properties in it.
Any suggestions for solving this issue?

Many thanks and best regards

Markus

**Comment by nijel** [comment]
You can import as many components as needed into Weblate and keep the things separated. Something similar (but with Gettext PO files) is doing for example Noosfero project: https://hosted.weblate.org/projects/noosfero/

**Comment by mkjaxxo** [comment]
Thanks you nijel. Ok, so one file would be one "component". Will look into this. Thanks.
