### ISSUE TITLE
Error in parameter type: Select a valid choice. todo is not one of the available choices.

### ISSUE THREAD

**Issue by ihoru** [nijel/weblate#986]
After last update I found this error:
Error in parameter type: Select a valid choice. todo is not one of the available choices.
on this url: https://hosted.weblate.org/translate/weblate/master/ru/?type=todo
after clicking "Strings needing attention" from here: https://hosted.weblate.org/projects/weblate/master/ru/

**Comment by ihoru** [comment]
The similar message appeared here:
https://hosted.weblate.org/translate/weblate/master/ru/?type=nottranslated

**Comment by nijel** [comment]
Fixed now, thanks for spotting.

**Comment by ihoru** [comment]
Thank you!
