### ISSUE TITLE
Better naming for secondary languages

### ISSUE THREAD

**Issue by qmar** [nijel/weblate#992]
My usecase is as follows:

I write an Android app which has the default language set to english. By myself I provide english and polish translations. I have a customer which can translate from polish to russian. He does not know english.

Is there a way to setup weblate to let him translate from polish to english? I cannot change the base strings file - I don't want my e.g. french users to see the app in polish, so I have to keep the english as base.

**Comment by nijel** [comment]
Let him add Polish as a secondary language: https://docs.weblate.org/en/latest/user/profile.html#secondary-languages

**Comment by qmar** [comment]
@nijel Thank you so much! Works like a charm! It would take me ages to find it by myself.

**Comment by nijel** [comment]
Is there some keyword which would make you find it easier? Maybe we could improve documentation to show this feature more prominently...

**Comment by qmar** [comment]
@nijel Maybe call it "native language" instead of secondary? I've seen it before in the profile settings, but never thought what it means.
