### ISSUE TITLE
Add a BIG red box asking translators not to translate placeholders

### ISSUE THREAD

**Issue by sknorr** [nijel/weblate#997]
I just had the case that a translator had translated placeholder XML tags from `<placeholder-1/>` to `<Platzhalter-1/>`. Obviously, after that, build failed.

I can't blame the translator, they are probably doing that for the first time or so. It would be great if there was a box below the textarea for the translated string that would warn against translating/modifying placeholders, at least for new contributors.

And yes, I can reset translations easily, but doing so for 10's of languages would take a lot of time.

**Comment by nijel** [comment]
I don't think there is much more to do now:

- the placeholders are highlighted in the source (see https://twitter.com/WeblateOrg/status/691936163171549184)
- once something is broken, there is notification (which could be made better, see #894)

**Comment by sknorr** [comment]
@nijel, I am not sure that highlighting stuff in the source is enough as long as people can still change the translation. I'd really rather like for people to either be warned or to not be able to edit those strings (maybe that would actually be possible if you converted the `<textarea>`s to `<div contenteditable>`?).

**Comment by nijel** [comment]
That would be option as well, but especially with XML it's hard to decide when string should be translatable or not. For examle is ``<a href="something">`` supposed to be translated?

**Comment by sknorr** [comment]
True. One could go for the (very complicated) approach of making the tag names and attribute names read-only, but allowing translators to edit attribute values... but even that would not cover all cases adequately.

A project-specific configuration (file) with regexes might help... i.e., in the case you mentioned, `a` tags would get an editable `href` value but you couldn't change anything about e.g. their `style` attribute. And other tags would be completely immutable. But this proposal is probably a bit crazy. :)

I also just took a look where the `<placeholder-1>` etc. tags are coming from in "my" project and it seems the PO generator already creates those. Not sure if it is the best approach to use pseudo-XML as placeholders... does Weblate recognize this as a placeholder, even?

**Comment by nijel** [comment]
If the string is valid XML then it does recognize them, otherwise it won't. Maybe it's better to stick with something more traditional what translators will know and not try to alter (eg. ``%s``)?

**Comment by sknorr** [comment]
> If the string is valid XML then it does recognize them, otherwise it 
> won't. Maybe it's better to stick with something more traditional 
> what translators will know and not try to alter (eg. %s)?
> 

Does `<placeholder-1>something</placeholder-2>` count as valid XML?

**Comment by nijel** [comment]
No, it is not :-)
